### ISSUE TITLE
Test data has features with unseen categorical values

### ISSUE THREAD

**Issue by marcoslbueno** [automl/auto-sklearn#1055]
## Describe the bug ##
One categorical feature in my test dataset (OpenML id 40981) has a new category, i.e. a value that was not seen in the training data. When I try to compute predictions on such test data, Auto-sklearn raises an error.

## To Reproduce ##
```
import openml
import pandas as pd
import autosklearn.classification
from sklearn.model_selection import KFold
import sklearn.metrics

did = 40981
data = openml.datasets.get_dataset(did) 
name = openml.datasets.get_dataset(did).name
X, y, _, _ = data.get_data(dataset_format='dataframe', target=data.default_target_attribute)

kf = KFold(n_splits=3, shuffle=False)
    
for k, (train_idx, test_idx) in enumerate(kf.split(X,y)):
    
    print("* * * \n\tFitting fold = ",k+1,"\n")
    
    X_train, y_train = X.iloc[train_idx,:], y[train_idx]
    X_test, y_test = X.iloc[test_idx,:], y[test_idx]
    
    autosk = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=30,
    )
    autosk.fit(X_train, y_train, dataset_name=name)
    
    autosk_proba_predictions = autosk.predict_proba(X_test)
    autosk_loss = sklearn.metrics.log_loss(y_test, autosk_proba_predictions)
    print("Autosklearn log loss:", autosk_loss)
```

## Actual behavior, stacktrace or logfile ##
```
/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/base.py:209: FutureWarning: From version 0.24, get_params will raise an AttributeError if a parameter cannot be retrieved as an instance attribute. Previously it would return None.
  warnings.warn('From version 0.24, get_params will raise an '
AutoSklearnClassifier(load_models=None, per_run_time_limit=3,
                      time_left_for_this_task=30)
Traceback (most recent call last):
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/data/validation.py", line 423, in _check_and_encode_features
    X = self.feature_encoder.transform(X)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py", line 604, in transform
    Xs = self._fit_transform(X, None, _transform_one, fitted=True)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/compose/_column_transformer.py", line 458, in _fit_transform
    return Parallel(n_jobs=self.n_jobs)(
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/pipeline.py", line 719, in _transform_one
    res = transformer.transform(X)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py", line 700, in transform
    X_int, _ = self._transform(X)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/sklearn/preprocessing/_encoders.py", line 124, in _transform
    raise ValueError(msg)
ValueError: Found unknown categories ['3'] in column 1 during transform

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/estimators.py", line 636, in predict_proba
    pred_proba = super().predict_proba(
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/estimators.py", line 456, in predict_proba
    return self.automl_.predict_proba(
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/automl.py", line 1337, in predict_proba
    return super().predict(X, batch_size=batch_size, n_jobs=n_jobs)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/automl.py", line 858, in predict
    X = self.InputValidator.validate_features(X)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/data/validation.py", line 158, in validate_features
    X = self._check_and_encode_features(X)
  File "/Users/marcoslpbueno/automlpy/env/lib/python3.8/site-packages/autosklearn/data/validation.py", line 427, in _check_and_encode_features
    raise ValueError(
ValueError: During fit, the input features contained categorical values in columns['A1', 'A4', 'A5', 'A6', 'A8', 'A9', 'A11', 'A12'], with categories [array(['0', '1'], dtype=object), array(['1', '2'], dtype=object), array(['1', '10', '11', '12', '13', '14', '2', '3', '4', '5', '6', '7',
       '8', '9'], dtype=object), array(['1', '2', '3', '4', '5', '7', '8', '9'], dtype=object), array(['0', '1'], dtype=object), array(['0', '1'], dtype=object), array(['0', '1'], dtype=object), array(['1', '2', '3'], dtype=object)] which were encoded by Auto-sklearn automatically.Nevertheless, a new input contained new categories not seen during training = Found unknown categories ['3'] in column 1 during transform. The OrdinalEncoder used by Auto-sklearn cannot handle this yet (due to a limitation on scikit-learn being addressed via: https://github.com/scikit-learn/scikit-learn/issues/17123)
```

## Environment and installation: ##

Please give details about your installation:

* macOS Big Sur 11.1
* virtual environment
* Python version 3.8.5
* Auto-sklearn version 0.12.0

**Comment by mfeurer** [comment]
This is a limitation of scikit-learn discussed in https://github.com/scikit-learn/scikit-learn/issues/17123. Auto-sklearn will support new categories in categorical data with the release of scikit-learn 0.25 or scikit-learn 1.0 (however they name it). In the meantime you have to pass the data as numpy arrays.

**Comment by zachmayer** [comment]
what is it in sklearn .25/1.0 that will allow for handling new categories?

**Comment by mfeurer** [comment]
Thanks @zachmayer for checking back. To be honest, I can't find out right now.

We have refactored our code to also work with the current version of scikit-learn.
