### ISSUE TITLE
Problems starting with automl: cannot import name random_choice_csc

### ISSUE THREAD

**Issue by lesshaste** [automl/auto-sklearn#108]
I managed to install automl on ubuntu 14.04 using.

easy_install -U pip
sudo pip install Cython
sudo pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt
sudo pip install auto-sklearn

If I didn't do these steps it complained about missing Cython.build.

Now when I try to run the Example from http://automl.github.io/auto-sklearn/stable/ I get:

Traceback (most recent call last):
  File "automl-test.py", line 1, in <module>
    import autosklearn.classification
  File "/usr/local/lib/python2.7/dist-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/usr/local/lib/python2.7/dist-packages/autosklearn/estimators.py", line 8, in <module>
    import autosklearn.automl
  File "/usr/local/lib/python2.7/dist-packages/autosklearn/automl.py", line 22, in <module>
    from autosklearn.evaluation import resampling, eval_with_limits
  File "/usr/local/lib/python2.7/dist-packages/autosklearn/evaluation/__init__.py", line 10, in <module>
    from .abstract_evaluator import *
  File "/usr/local/lib/python2.7/dist-packages/autosklearn/evaluation/abstract_evaluator.py", line 7, in <module>
    from sklearn.dummy import DummyClassifier, DummyRegressor
  File "/usr/local/lib/python2.7/dist-packages/sklearn/dummy.py", line 15, in <module>
    from .utils.random import random_choice_csc
ImportError: cannot import name random_choice_csc

**Comment by lesshaste** [comment]
As an experiment I tried

pip install pip --upgrade
pip install -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt

from a clean virtualenv. 

This time I get

[...]
Collecting ConfigSpace (from -r https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt (line 22))
  Downloading ConfigSpace-0.1.1.tar.gz (80kB)
    100% |████████████████████████████████| 81kB 780kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-FFv_W5/ConfigSpace/setup.py", line 3, in <module>
        import ConfigSpace
      File "ConfigSpace/__init__.py", line 6, in <module>
        from ConfigSpace.configuration_space import Configuration, \
      File "ConfigSpace/configuration_space.py", line 27, in <module>
        import numpy as np
    ImportError: No module named numpy

I did  pip install numpy and tried again.

This time I get   ImportError: No module named six (fixed with: pip install six), then  ImportError: No module named Cython.Build (fixed with: pip install Cython).  Once those are manually fixed it installs  and I can do pip install auto-sklearn .

The Example from http://automl.github.io/auto-sklearn/stable/ then runs.

**Comment by mfeurer** [comment]
Thanks for reporting this. We need to add a mechanism which sorts the dependencies for installation.

**Comment by mfeurer** [comment]
The [latest installation manual](http://automl.github.io/auto-sklearn/stable/) and the latest version that I just pushed to pypi a few minutes ago should install all dependencies in the correct order. Please reopen if this issue persists.

**Comment by lesshaste** [comment]
I just pip install auto-sklearn --user -U  and then ran the new version of the example from http://automl.github.io/auto-sklearn/stable/ . I get

```
Traceback (most recent call last):
  File "automl-test.py", line 1, in <module>
    import autosklearn.classification
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/estimators.py", line 7, in <module>
    import autosklearn.automl
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/automl.py", line 27, in <module>
    from autosklearn.smbo import AutoMLSMBO
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/smbo.py", line 13, in <module>
    from smac.smbo.smbo import SMBO, get_types
  File "/home/user/.local/lib/python2.7/site-packages/smac/smbo/smbo.py", line 15, in <module>
    from smac.epm.rf_with_instances import RandomForestWithInstances
  File "/home/user/.local/lib/python2.7/site-packages/smac/epm/rf_with_instances.py", line 4, in <module>
    import pyrfr.regression
ImportError: /home/user/.local/lib/python2.7/site-packages/pyrfr/regression.so: undefined symbol: PyFPE_jbuf
```

**Comment by lesshaste** [comment]
Thank you. The new code seems to give no output at all while it is running. Is there a verbose option?

**Comment by mfeurer** [comment]
Could you please open a new issue for that? I hope that better output is only a matter of correctly setting up the logger.
