### ISSUE TITLE
Sparse Data via lil_matrix not supported

### ISSUE THREAD

**Issue by fmohr** [automl/auto-sklearn#1087]
## Describe the bug ##
Running `fit` on auto-sklearn fails when the input data `X` is a `lil_matrix`. It *does* work with `csr_matrix`, but that is not recommended. I am not aware how to efficiently create a csr_matrix without using `df.values`, which we of course want to avoid.

## To Reproduce ##
```python
df = # somehow get the data frame, for example for openml id 1486
dfSparse = pd.get_dummies(df[lc for c in df.columns if c != labelColumn]], sparse=True)

print("dummies created, now creating sparse matrix")
X = lil_matrix(dfSparse.shape, dtype=np.float32)
for i, col in enumerate(dfSparse.columns):
    ix = dfSparse[col] != 0
    X[np.where(ix), i] = 1
```

## Expected behavior ##
auto-sklearn should finish successfully and produce a model.

## Actual behavior, stacktrace or logfile ##
```
 --> Traceback (most recent call last):
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/estimators.py", line 597, in fit
 -->     dataset_name=dataset_name,
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/estimators.py", line 356, in fit
 -->     self.automl_.fit(load_models=self._load_models, **kwargs)
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/automl.py", line 1322, in fit
 -->     load_models=load_models,
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/automl.py", line 440, in fit
 -->     X, y = self.InputValidator.validate(X, y)
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/data/validation.py", line 110, in validate
 -->     X = self.validate_features(X)
 -->   File "/usr/local/lib/python3.6/dist-packages/autosklearn/data/validation.py", line 161, in validate_features
 -->     X.sort_indices()
 -->   File "/usr/local/lib/python3.6/dist-packages/scipy/sparse/base.py", line 687, in __getattr__
 -->     raise AttributeError(attr + " not found")
 --> AttributeError: sort_indices not found
```

## Environment and installation: ##

Please give details about your installation:

* Arch Linux
* Is your installation in a virtual environment or conda environment? Yes, it is installed within a singularity container.
* Python version: 3.7.7
* Auto-sklearn version: 0.12.0

**Comment by franchuterivera** [comment]
Hello, thanks for using Auto-Sklearn. This problem was fixed on a newer version of autosklearn, particularly on #1041.

I tried reproducing the behavior with the latest version and the following code:

```
import sklearn.datasets
import sklearn.metrics
import autosklearn.classification
import pandas as pd
from scipy.sparse import lil_matrix
import numpy as np

X, y = sklearn.datasets.fetch_openml(data_id=1486, return_X_y=True, as_frame=True)
dfSparse = pd.get_dummies(X, sparse=True)
X = lil_matrix(dfSparse.shape, dtype=np.float32)
for i, col in enumerate(dfSparse.columns):
    ix = dfSparse[col] != 0
    X[np.where(ix), i] = 1

automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=120, #  Please try with more runtime as this is just for reproducing purposes
    per_run_time_limit=30,
)
```
And this does not seem to be a problem anymore. Kindly re-open if you still see an issue using the latest version.
