### ISSUE TITLE
Which version of scikit learn should be used in Python 3.6.10

### ISSUE THREAD

**Issue by hyzhang-hub** [automl/auto-sklearn#1093]
I found an error running the code：
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    main()
  File "main.py", line 25, in main
    model = create_model(FLAGS.model, data.input_dim(), data, dist_calculator)
  File "/home/zhy/workspace/graph_similarity/SimGNN/model/Siamese/data_siamese.py", line 43, in input_dim
    return self.node_feat_encoder.input_dim()
  File "/home/zhy/workspace/graph_similarity/SimGNN/model/Siamese/data_siamese.py", line 242, in input_dim
    return self.oe.transform([[0]]).shape[1]
  File "/home/zhy/anaconda3/envs/tf/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py", line 394, in transform
    if self.drop is not None:
AttributeError: 'OneHotEncoder' object has no attribute 'drop'
My Python environment is 3.6.10. I tried some versions of scikit learn, but they all failed. I don't know why.
Please give me some suggestions, thank you.

**Comment by mfeurer** [comment]
The stacktrace looks like you're not using Auto-sklearn and I'm therefore closing this issue as it does not appear to be an Auto-sklearn issue. If you're using Auto-sklearn please reopen and explain how this error is related to Auto-sklearn.
