### ISSUE TITLE
Auto-sklearn consumes a lot of memory compared to dataset size

### ISSUE THREAD

**Issue by rabsr** [automl/auto-sklearn#1130]
## Describe the bug ##
By default memory_limit is set to 3GB for machine learning models. I do get following error even when I use data of size ~3.5MB. 
`ValueError: Dummy prediction failed with run state StatusType.MEMOUT and additional output: {'error': 'Memout (used more than 1024 MB).', 'configuration_origin': 'DUMMY'}`
As per [subsample_if_too_large](https://github.com/automl/auto-sklearn/blob/25d680d4e9520a661aae48ea4c7295c663b64df3/autosklearn/automl.py#L816), 10x memory should be sufficient to successfully train best model. But I have to increase memory_limit to 4-5GB to successfully run experiments.
We have performed few experiments to find root cause. It looks like it is related to pynisher and some memory is used by python interpreter. 
I do wonder why is such large memory is required for such small dataset.

## To Reproduce ##
I am using following script. I am getting same error even with n=1,2,3 and 4 i.e. (memory_limit=1-4GB).

```
import sklearn.datasets
import pandas as pd
import autosklearn.classification

X, y = sklearn.datasets.fetch_openml(data_id=1461, return_X_y=True, as_frame=False)
for col in X.columns:
    if X[col].dtype.name == 'object':
        X[col] = X[col].astype('category')
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)
print('data shape:', X_train.shape)

n=1
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=300,
    per_run_time_limit=60,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
    memory_limit=n*1024,
)
automl.fit(X_train, y_train, dataset_name='breast_cancer')
```

## Actual behavior, stacktrace or logfile ##
```
data shape: (33908, 16)
Traceback (most recent call last):
  File "test_memory_askl.py", line 31, in <module>
[ERROR] [2021-04-18 00:19:13,203:Client-AutoML(1):breast_cancer] Dummy prediction failed with run state StatusType.MEMOUT and additional output: {'error': 'Memout (used more than 1024 MB).', 'configuration_origin': 'DUMMY'}.
    automl.fit(X_train, y_train, dataset_name='breast_cancer')
  File "automl_env/lib/python3.7/site-packages/autosklearn/estimators.py", line 598, in fit
    dataset_name=dataset_name,
  File "automl_env/lib/python3.7/site-packages/autosklearn/estimators.py", line 357, in fit
    self.automl_.fit(load_models=self.load_models, **kwargs)
  File "automl_env/lib/python3.7/site-packages/autosklearn/automl.py", line 1422, in fit
    is_classification=True,
  File "automl_env/lib/python3.7/site-packages/autosklearn/automl.py", line 623, in fit
    self._do_dummy_prediction(datamanager, num_run)
  File "automl_env/lib/python3.7/site-packages/autosklearn/automl.py", line 438, in _do_dummy_prediction
    % (str(status), str(additional_info))
ValueError: Dummy prediction failed with run state StatusType.MEMOUT and additional output: {'error': 'Memout (used more than 1024 MB).', 'configuration_origin': 'DUMMY'}.
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/python/python37/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
Process ForkProcess-1:
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <function AutoML.__del__ at 0x7ff16baa0840>
Traceback (most recent call last):
  File "automl_env/lib/python3.7/site-packages/autosklearn/automl.py", line 1373, in __del__
  File "automl_env/lib/python3.7/site-packages/autosklearn/automl.py", line 352, in _clean_logger
  File "/opt/python/python37/lib/python3.7/multiprocessing/process.py", line 140, in join
  File "/opt/python/python37/lib/python3.7/multiprocessing/popen_fork.py", line 44, in wait
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/opt/python/python37/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/python/python37/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "automl_env/lib/python3.7/site-packages/autosklearn/util/logging_.py", line 295, in start_log_server
    receiver.serve_until_stopped()
  File "automl_env/lib/python3.7/site-packages/autosklearn/util/logging_.py", line 327, in serve_until_stopped
    self.timeout)
KeyboardInterrupt
```

## Environment and installation: ##

* Is your installation in a virtual environment or conda environment? Virtual Environment
* Python Version: 3.7.3
* Auto-skearn: 0.12.3

**Comment by franchuterivera** [comment]
Hello, thanks a lot for reporting this problem.

If I try your provided code (by setting as_frame=True so that your column indication works) and use the default 3GB with the latest auto-sklearn, I do not observe a problem and I do so multiple models being fitted.
```
data shape: (33908, 16)
[(0.320000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'extra_trees', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'no_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'minority_coalescer', 'data_preprocessing:numerical_transformer:imputation:strategy': 'median', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'minmax', 'feature_preprocessor:__choice__': 'polynomial', 'classifier:extra_trees:bootstrap': 'True', 'classifier:extra_trees:criterion': 'gini', 'classifier:extra_trees:max_depth': 'None', 'classifier:extra_trees:max_features': 0.8957681555296357, 'classifier:extra_trees:max_leaf_nodes': 'None', 'classifier:extra_trees:min_impurity_decrease': 0.0, 'classifier:extra_trees:min_samples_leaf': 2, 'classifier:extra_trees:min_samples_split': 9, 'classifier:extra_trees:min_weight_fraction_leaf': 0.0, 'data_preprocessing:categorical_transformer:category_coalescence:minority_coalescer:minimum_fraction': 0.00011293033925606851, 'feature_preprocessor:polynomial:degree': 2, 'feature_preprocessor:polynomial:include_bias': 'True', 'feature_preprocessor:polynomial:interaction_only': 'True'},
dataset_properties={
  'task': 1,
  'sparse': False,
  'multilabel': False,
  'multiclass': False,
  'target_type': 'classification',
  'signed': False})),
(0.240000, SimpleClassificationPipeline({'balancing:strategy': 'none', 'classifier:__choice__': 'gradient_boosting', 'data_preprocessing:categorical_transformer:categorical_encoding:__choice__': 'one_hot_encoding', 'data_preprocessing:categorical_transformer:category_coalescence:__choice__': 'no_coalescense', 'data_preprocessing:numerical_transformer:imputation:strategy': 'mean', 'data_preprocessing:numerical_transformer:rescaling:__choice__': 'none', 'feature_preprocessor:__choice__': 'feature_agglomeration', 'classifier:gradient_boosting:early_stop': 'valid', 'classifier:gradient_boosting:l2_regularization': 1.7108930238344161e-10, 'classifier:gradient_boosting:learning_rate': 0.010827728124541558, 'classifier:gradient_boosting:loss': 'auto', 'classifier:gradient_boosting:max_bins': 255, 'classifier:gradient_boosting:max_depth': 'None', 'classifier:gradient_boosting:max_leaf_nodes': 25, 'classifier:gradient_boosting:min_samples_leaf': 4, 'classifier:gradient_boosting:scoring': 'loss', 'classifier:gradient_boosting:tol': 1e-07, 'feature_preprocessor:feature_agglomeration:affinity': 'euclidean', 'feature_preprocessor:feature_agglomeration:linkage': 'ward', 'feature_preprocessor:feature_agglomeration:n_clusters': 164, 'feature_preprocessor:feature_agglomeration:pooling_func': 'mean', 'classifier:gradient_boosting:n_iter_no_change': 19, 'classifier:gradient_boosting:validation_fraction': 0.1759114608225653},
dataset_properties={
----> This is the output of automl.show_models() that I added at the end
```

Do you observe this problem on the latest auto-sklearn? On recommendation also is to use 3.8 python to consume some memory enhancements done there, but I also did not see a problem in my laptop with 3.7.

First, let us see if you can still reproduce with the latest version.

**Comment by mfeurer** [comment]
Thanks @franchuterivera for checking the example. @rabsr can you reproduce the error with Auto-sklearn 0.12.6?

**Comment by rabsr** [comment]
@franchuterivera @mfeurer I am able to reproduce the issue. I get the same Memout error for dummy prediction with memory_limit set to 1-4GB. I am able to run with 5GB. 
The only difference is I have downloaded the bank dataset (openml 1461 dataset) and using it.  My input to Autosklearn is pandas dataframe.

OS: "Red Hat Enterprise Linux Server 7.9 (Maipo)"

Following is the updated script

```
import sklearn.datasets
import pandas as pd
import autosklearn.classification
import sklearn.model_selection
import os

target = "target"

X = pd.read_csv("data/bank.csv"))

y = X[target]

X.drop([target], inplace=True, axis=1)

for col in X.columns:
    if X[col].dtype.name == 'object':
        X[col] = X[col].astype('category')
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, random_state=1)
print('data shape:', X_train.shape)


n=5
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=300,
    per_run_time_limit=60,
    tmp_folder='/tmp/autosklearn_classification_example_tmp',
    output_folder='/tmp/autosklearn_classification_example_out',
    memory_limit=n*1024,
)
automl.fit(X_train, y_train, dataset_name='bank_dataset')
```

Following are the packages version
```
Package            Version
------------------ --------
auto-sklearn       0.12.6
click              8.0.1
cloudpickle        1.6.0
ConfigSpace        0.4.19
Cython             0.29.23
dask               2021.6.2
distributed        2021.6.2
fsspec             2021.6.1
HeapDict           1.0.1
importlib-metadata 4.5.0
joblib             1.0.1
lazy-import        0.2.2
liac-arff          2.5.0
locket             0.2.1
msgpack            1.0.2
numpy              1.21.0
pandas             1.2.5
partd              1.2.0
pip                20.2.3
psutil             5.8.0
pynisher           0.6.4
pyparsing          2.4.7
pyrfr              0.8.2
python-dateutil    2.8.1
pytz               2021.1
PyYAML             5.4.1
scikit-learn       0.24.2
scipy              1.6.3
setuptools         40.8.0
six                1.16.0
smac               0.13.1
sortedcontainers   2.4.0
tblib              1.7.0
threadpoolctl      2.1.0
toolz              0.11.1
tornado            6.1
typing-extensions  3.10.0.0
wheel              0.36.2
zict               2.0.0
zipp               3.4.1
```

There is one more issue. scipy has released new version which is not compatible with SMAC 0.13.1 version. I had to use scipy version 1.6.3.

**Comment by mfeurer** [comment]
Thanks a lot for your update. Unfortunately, we cannot reproduce this issue, so it must be something subtle about the environment.

Would you be able to provide us a dockerfile that triggers the error? Or could you please try our docker container and see if this also triggers the issue?

**Comment by rabsr** [comment]
Sure. I will try with autosklearn docker container and keep you posted once I have results.

**Comment by AbhayGoyal** [comment]
I am still getting the following issue
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'traceback': 'Traceback (most recent call last):\n  File "/usr/local/home/aghnw/anaconda3/envs/bias/lib/python3.8/site-packages/autosklearn/evaluation/__init__.py", line 349, in run\n    obj = pynisher.enforce_limits(**arguments)(self.ta)\nAttributeError: module \'pynisher\' has no attribute \'enforce_limits\'\n', 'error': 'AttributeError("module \'pynisher\' has no attribute \'enforce_limits\'")'}.
