### ISSUE TITLE
auto-sklearn error when gcp dask_client is used

### ISSUE THREAD

**Issue by psraghuveer** [automl/auto-sklearn#1174]
Code:
```py
import autosklearn.classification
from dask_cloudprovider.gcp import GCPCluster
from dask.distributed import Client

with GCPCluster() as dask_gcp_cluster:
   with Client(dask_gcp_cluster) as dask_client:
     automl = autosklearn.classification.AutoSklearnClassifier(dask_client=dask_client)
     automl.fit() # calling automl.fit here on X_train and y_train (pandas DataFrames) results in the error below.
```

Error:
```sh
[ERROR] [2021-07-11 16:38:50,709:Client-AutoML(1):5924e4fd-e238-11eb-bbe9-438dc20b6eec] [Errno 2] No such file or directory: '/tmp/autosklearn_tmp_5924a168-e238-11eb-bbe9-438dc20b6eec/.auto-sklearn/datamanager.pkl'
Traceback (most recent call last):
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/autosklearn/automl.py", line 789, in fit
    _proc_smac.run_smbo()
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/autosklearn/smbo.py", line 502, in run_smbo
    smac.optimize()
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/smac/facade/smac_ac_facade.py", line 597, in optimize
    incumbent = self.solver.run()
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/smac/optimizer/smbo.py", line 288, in run
    self._incorporate_run_results(run_info, result, time_left)
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/smac/optimizer/smbo.py", line 493, in _incorporate_run_results
    callback(smbo=self, run_info=run_info, result=result, time_left=time_left)
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/autosklearn/ensemble_builder.py", line 158, in __call__
    self.build_ensemble(smbo.tae_runner.client)
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/autosklearn/ensemble_builder.py", line 193, in build_ensemble
    result = self.futures.pop().result()
  File "/home/raghuveer/fastml/fastml-backend/venv/lib/python3.8/site-packages/distributed/client.py", line 226, in result
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/autosklearn/ensemble_builder.py", line 347, in fit_and_return_ensemble
  File "/opt/conda/lib/python3.8/site-packages/autosklearn/ensemble_builder.py", line 567, in __init__
  File "/opt/conda/lib/python3.8/site-packages/autosklearn/util/backend.py", line 313, in load_datamanager
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/autosklearn_tmp_5924a168-e238-11eb-bbe9-438dc20b6eec/.auto-sklearn/datamanager.pkl'
```
Versions:
auto-sklearn: 0.12.6
dask: 2021.7.0
dask-cloudprovider[gcp]==2021.6.0

**Comment by rabsr** [comment]
auto-sklearn uses a tmp_folder to save intermediate results (model generated, predictions, configs etc). And it expects tmp_folder path to be shared across dask workers. You need to set tmp_folder path in autosklearn.classification.AutoSklearnClassifier as follows:

```
automl = autosklearn.classification.AutoSklearnClassifier(dask_client=dask_client, tmp_folder=<shared_path>)
```

**Comment by eddiebergman** [comment]
@psraghuveer I'm not familiar with dask in the cloud but:
* Parallel processes are distributed using dask
* If using multiple cloud compute nodes with the GCPCluster, their filesystems might differ
* Hence `/tmp` for node 1 differs from `/tmp` for node 2
* Leading to no such found directory

This is not an immediate concern to support cloud distributed computing.

However in the meantime, most cloud providers support a shared filesystem between nodes, i.e. `/shared` or something like that. I would investigate GCP's options and see if your can have all your nodes have access to it and then pass
```python
shared_path = 'some/shared/network/drive/'
automl = autosklearn.classification.AutoSklearnClassifier(
    dask_client=dask_client,
    output_folder=shared_path> + '/asklearn_output'
    tmp_folder=shared_path + '/asklearn_tmp'
)
```

To help us address this in the future, if you could give a small description of your GCP setup, and whether these folders were actually created in `/tmp` from the main host you ran the script on, that would provide more info both for you and when we can get around to it.

All the best
