### ISSUE TITLE
smac/scenario/scenario.py  ValueError: Could not parse the following arguments: ['algo_runs_timelimit', 'cutoff']

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#129]
while running the example from your frontpage:

```
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 766, in run_smbo
    self.shared_mode)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 201, in __init__
    super(AutoMLScenario, self).__init__(scenario_dict)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/smac/scenario/scenario.py", line 65, in __init__
    str(list(scenario.keys())))
ValueError: Could not parse the following arguments: ['algo_runs_timelimit', 'cutoff']
```

**Comment by tbsflk** [comment]
I do get exactly the same error when I try to use AutoSklearnClassifier in my project.

**Comment by jtyberg** [comment]
It looks like a mismatch between auto-sklearn and smac.  The former sends `cutoff` and `algo_runs_timelimit`, while the [latter](https://github.com/automl/SMAC3/blob/2d5091c7a6312dcf7c2895795532f7754fe04936/smac/scenario/scenario.py#L124) checks for argument _names_ `cutoff_time` and `tuner-timeout`, and fails if they to not match.

**Comment by mfeurer** [comment]
There were updates to the SMAC tool which aren't yet reflected in the master branch. Please try to re-install, it should be fixed.

**Comment by Motorrat** [comment]
Thanks. It works now. I saw SMAC 0.1.1 removed and 0.0.1 installed. One thing though - the resulting score is at 0.97211766346, i.e. below 0.98.
