### ISSUE TITLE
AssertionError: daemonic processes are not allowed to have children

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#130]
I am trying to keep running multiple AutoSklearnClassifier seeds in parallel as already worked before. Now I get the following error messages. 
Has the logic of parallel execution changes? If so what is the recommended pattern?

```
[INFO] [2016-09-18 13:52:38,346:AutoML(1):59485c0bb92ca0c6c03c60b7e52d88d7] Starting to create dummy predictions.
[ERROR] [2016-09-18 13:52:38,350:AutoML(1):59485c0bb92ca0c6c03c60b7e52d88d7] Error creating dummy prediction 1/2:daemonic processes are not allowed to have children
[ERROR] [2016-09-18 13:52:38,353:AutoML(1):59485c0bb92ca0c6c03c60b7e52d88d7] Error creating dummy prediction 2/2 daemonic processes are not allowed to have children
[INFO] [2016-09-18 13:52:38,386:AutoML(1):59485c0bb92ca0c6c03c60b7e52d88d7] Start Ensemble with 2995.52sec time left
 #  Exception in seed=1.    #  13:52 #
Traceback (most recent call last):
  File "nfs_share/Redly-SQL-Example2.py", line 88, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/automl.py", line 175, in fit
    return self._fit(loaded_data_manager)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/automl.py", line 340, in _fit
    self._proc_ensemble.start()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children
multiprocessing.pool.RemoteTraceback:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "nfs_share/Redly-SQL-Example2.py", line 88, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/automl.py", line 175, in fit
    return self._fit(loaded_data_manager)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/automl.py", line 340, in _fit
    self._proc_ensemble.start()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 103, in start
    'daemonic processes are not allowed to have children'
AssertionError: daemonic processes are not allowed to have children


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "nfs_share/Redly-SQL-Example2.py", line 168, in <module>
    pool.map(spawn_classifier, [fit_delay+90*i for i in range(pool_size)])
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
AssertionError: daemonic processes are not allowed to have children

```

this is the relevant part of the code that was working with the older version of autosklearn
```
def spawn_classifier(seed):
    time.sleep(seed) # to avoid race for lock
    c = AutoSklearnClassifier(time_left_for_this_task=overall_run, per_run_time_limit=per_task, ml_memory_limit=memory_limit,
                shared_mode=True, tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir,
                delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
                ensemble_size=0, initial_configurations_via_metalearning=0,
                include_preprocessors=('no_preprocessing',),
                include_estimators=('sgd',),
                seed=seed)
    c._task = BINARY_CLASSIFICATION
    c._metric = F1_METRIC
    c._precision = '32'
    c._dataset_name = 'Autosklearn'
    try:
        p("Starting seed="+str(seed))
        c.fit(X_train, y_train, metric='f1_metric')
        p("####### Finished seed="+str(seed))
    except Exception:
        p("Exception in seed="+str(seed)+".  ")
        traceback.print_exc()
        raise

p("Process pool size="+str(pool_size))
if __name__ == '__main__':
    pool = Pool(pool_size)
    time.sleep(10)
    # 90 is experimental value so no race condition occure
    pool.map(spawn_classifier, [fit_delay+90*i for i in range(pool_size)])
    pool.close()
    pool.join()
    pool.terminate()
    p("Multicore fit completed")

```

**Comment by Motorrat** [comment]
After a downgrade of SMAC #129  I am still facing this issue.

**Comment by Motorrat** [comment]
this could be used as a testing example

```
import time, shutil, traceback
from multiprocessing import Pool
from autosklearn.classification import AutoSklearnClassifier
from autosklearn.constants import *
import sklearn.datasets

digits = sklearn.datasets.load_digits()
X = digits.data
y = digits.target
import numpy as np
indices = np.arange(X.shape[0])
np.random.shuffle(indices)
X = X[indices]
y = y[indices]
X_train = X[:1000]
y_train = y[:1000]
X_test = X[1000:]
y_test = y[1000:]

atsklrn_tempdir='atsklrn_tmp'

def spawn_classifier(seed):
    time.sleep(seed) # to avoid race for lock
    c = AutoSklearnClassifier(shared_mode=True
         , tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir
         , delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
         seed=seed)
    c._precision = '32'
    c._dataset_name = 'digits'
    try:
        print("Starting seed="+str(seed))
        c.fit(X_train, y_train, metric='f1_metric')
        print("Finished seed="+str(seed))
    except Exception:
        print("Exception in seed="+str(seed)+".  ")
        traceback.print_exc()
        raise

if __name__ == '__main__':

    shutil.rmtree(atsklrn_tempdir,ignore_errors=True) # remove temp directory

    spawn_classifier(1)
#    this commented part doesn't work now but it does in the older version of auto-sklearn
#    pool_size=2
#    pool = Pool(processes=pool_size)
#    time.sleep(10)
#    pool.map(spawn_classifier, [90*i for i in range(pool_size)])
#    pool.close()
#    pool.join()
#    pool.terminate()

    seed = 1
    c = AutoSklearnClassifier(
        shared_mode=True, tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir,
        delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
        seed=seed)
    c._precision = '32'
    c._dataset_name = 'digits'

    print(c.score(X_test,y_test))
```

**Comment by mfeurer** [comment]
This is not an issue with auto-sklearn but an issue due to the upgrade to python3.5. The workers in a Pool are no daemons themselves, and can't have child processes at all. I'll update the example.

**Comment by mfeurer** [comment]
Ah, this is actually already in the examples. Could you please try replacing the pool code by the manual starting of processes as in [example_parallel.py](https://github.com/automl/auto-sklearn/blob/master/example/example_parallel.py)

**Comment by Motorrat** [comment]
Thanks, the example_parallel.py goes through successfully, however with the score of just 0.85.
I see a lot of errors of this kind in the terminal window:
`[ERROR] [2016-09-21 03:01:22,638:EnsembleBuilder(4):digits] Caught ValueError: Ensemble size cannot be less than one!`

```
[WARNING] [2016-09-21 03:17:44,483:EnsembleBuilder(5):digits] Error loading predictions_ensemble_6_00077.npy: Solution and prediction have different number of samples: 330 and 329
[ERROR] [2016-09-21 03:17:44,483:EnsembleBuilder(7):digits] Model only predicts at random: predictions_ensemble_6_00067.npy has score: -1
```

**Comment by Motorrat** [comment]
I have rewritten the code following the example_parallel.py pattern and it works now. 

One question to the https://github.com/automl/auto-sklearn/blob/master/example/example_parallel.py#L39 remains, 
Why do you start with 2 for the seeds `for i in range(2, 6):`
 Shouldn't the loop look like this `for i in range(number_of_seeds):` so it goes from 0 to number_of_seeds-1 ?
This is how this works for me in my code now, anyway.

**Comment by mfeurer** [comment]
Okay, are the ensemble builder errors still there?

Otherwise, there is no specific reason for the seeds that I remember. The final classifier has the seed 1.

**Comment by Motorrat** [comment]
The first type "Caught ValueError: Ensemble size cannot be less than one!" appear with your example_parallel.py and 'digits' dataset. They are still there. I run example_parallel.py as is, without changing a line.

Further on I see a lot of `[ERROR] [2016-09-21 07:20:33,999:EnsembleBuilder(0):Autosklearn] Model only predicts at random: predictions_ensemble_3_00009.npy has score: -0.270531400966` in example_parallel.py as well.
 
This type of error also appear with my real-world dataset and my own code, but just to make it clear the model works at the end.

**Comment by mfeurer** [comment]
Okay, the output will be gone in the next release. I'm closing this now.
