### ISSUE TITLE
packages/pyrfr/regression.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by suny16907** [automl/auto-sklearn#141]
when i pip install auto sklearn the was a error **packages/pyrfr/regression.so: undefined symbol: PyFPE_jbuf,** i was install it on python 2.7 in anaconda environments

>>> import autosklearn.classification
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/autosklearn/estimators.py", line 8, in <module>
    import autosklearn.automl
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 27, in <module>
    from autosklearn.smbo import AutoMLSMBO
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/autosklearn/smbo.py", line 14, in <module>
    from smac.smbo.smbo import SMBO, get_types
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/smac/smbo/smbo.py", line 15, in <module>
    from smac.epm.rf_with_instances import RandomForestWithInstances
  File "/home/sunye/anaconda2/lib/python2.7/site-packages/smac/epm/rf_with_instances.py", line 4, in <module>
    import pyrfr.regression
ImportError: /home/sunye/anaconda2/lib/python2.7/site-packages/pyrfr/regression.so: undefined symbol: PyFPE_jbuf

**Comment by mfeurer** [comment]
There is a longer discussion on how to solve this issue in #101.
