### ISSUE TITLE
Uncaught CpuTimeoutException?

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#143]
```
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 119, in subprocess_func
    for child in p.children(recursive=True):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 866, in children
    table[p.ppid()].append(p)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 550, in ppid
    return self._proc.ppid()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1459, in ppid
    return int(self._parse_stat_file()[2])
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 27, in handler
    raise(CpuTimeoutException)
pynisher.limit_function_call.CpuTimeoutException
```

**Comment by mfeurer** [comment]
CPU time limits should not be used in auto-sklearn. I just submitted a patch to the development branch which should fix this issue. Does auto-sklearn actually choke on this or does it continue running?

**Comment by Motorrat** [comment]
Yes, it continues to run. Thanks for the fix (I won't be testing it though, unless this becomes a blocker in the future)

**Comment by mfeurer** [comment]
Okay, I close it for now.

**Comment by Motorrat** [comment]
ups, seems to be still there

```

Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 119, in subprocess_func
    for child in p.children(recursive=True):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 866, in children
    table[p.ppid()].append(p)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 550, in ppid
    return self._proc.ppid()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1459, in ppid
    return int(self._parse_stat_file()[2])
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 994, in _parse_stat_file
    data = f.read()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 27, in handler
    raise(CpuTimeoutException)
pynisher.limit_function_call.CpuTimeoutException
[WARNING] [2016-09-30 16:31:20,397:EnsembleBuilder(1):foobar] Error loading file (not .npy): tmpqpfhl6rq

```

**Comment by Motorrat** [comment]
and a slightly different one 

```
n_components is too large: it will be set to 30
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 119, in subprocess_func
    for child in p.children(recursive=True):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 866, in children
    table[p.ppid()].append(p)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 550, in ppid
    return self._proc.ppid()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 962, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1459, in ppid
    return int(self._parse_stat_file()[2])
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/_pslinux.py", line 1001, in _parse_stat_file
    return [name] + fields_after_name
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 27, in handler
    raise(CpuTimeoutException)
pynisher.limit_function_call.CpuTimeoutException
```

**Comment by Motorrat** [comment]
And another one

```
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 95, in subprocess_func
    return_value = (None, CpuTimeoutException)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 27, in handler
    raise(CpuTimeoutException)
pynisher.limit_function_call.CpuTimeoutException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 119, in subprocess_func
    for child in p.children(recursive=True):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 326, in wrapper
    return fun(self, *args, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 864, in children
    for p in process_iter():
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/psutil/__init__.py", line 1344, in process_iter
    new_pids = a - b
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 27, in handler
    raise(CpuTimeoutException)
pynisher.limit_function_call.CpuTimeoutException
```

**Comment by mfeurer** [comment]
This fix is only in the development branch, are you using the development branch?

**Comment by Motorrat** [comment]
No, I don't run the development branch. How would I install it? Sorry, I'm not that versed in github commands - only as much to get me up and running so far.

Regardless, I am posting these errors here as they seem to have different root causes. Doesn't it help to see why the CpuTimeoutException occured (something was too slow?)

**Comment by mfeurer** [comment]
You can install it by `pip install git+https://github.com/automl/auto-sklearn@development`. Nevertheless, you should probably wait for the next release as the output changed quite a lot.

Thanks for posting these errors. The CpuTimeoutException is something that shouldn't have been used by auto-sklearn in the first place and I simply removed it's usage. It is thrown when auto-sklearn runs over a CPU time limit. This doesn't really work well when another subprocess is created, so auto-sklearn only uses a wallclock time limit. Seeing why this happens is indeed a great idea.

**Comment by Motorrat** [comment]
On the other hand, I have just realized, that these Tracebacks are probably just showing the failed multiprocessing code, that fails **after** the CpuTimeoutException is raised and the process is killed. So these Traceback might not really be that helpful. I guess this issue may remain closed :-)

**Comment by mfeurer** [comment]
Yes, that's correct. You can see the 'more' interesting error messages in the other related issues that you've opened.
