### ISSUE TITLE
arpack.py in eigs % (k, n - 1)) ValueError: k=0 must be between 1 and ndim(A)-1=1

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#144]
I get a lot of these

```

Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/gem.py", line 16, in fit
    self.preprocessor.fit(X, Y)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/implementations/gem.py", line 34, in fit
    S,U = eigs(C2, self.N)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py", line 1238, in eigs
    % (k, n - 1))
ValueError: k=0 must be between 1 and ndim(A)-1=1

```

**Comment by mfeurer** [comment]
Thanks for reporting this. We already have experienced problems with the GEM preprocessor in #107 and it is scheduled for removal. In the meantime, you can just remove it from the list of preprocessors by including all other preprocessors by their name.

**Comment by Motorrat** [comment]
I saw GEM to be the only one that worked for a large-ish dataset https://www.kaggle.com/c/loan-default-prediction/data with 183mb zipped. Below I add some log snippets to illustrate.
I know, this is just an anecdotal evidence. But for me having something that fails from time to time, but may deliver the solve where nothing else works is better than not having it at all. This is why we try out all the combinations, isn't it? On the other hand, if GEM has other problems that compromise other parts of the pipeline most of the time, may be it is not worth it. 

```
[INFO] [2016-10-03 00:24:05,604:AutoMLSMBO(11)::foobar] Using 199 training points for SMAC.
[INFO] [2016-10-03 00:24:12,453:AutoMLSMBO(11)::foobar] Used 6.84918 seconds to find next configurations
[INFO] [2016-10-03 00:24:12,457:AutoMLSMBO(11)::foobar] Starting to evaluate 30. configuration (from SMAC) with time limit 858s.
[INFO] [2016-10-03 00:24:12,457:AutoMLSMBO(11)::foobar] Configuration:
  balancing:strategy, Value: 'weighting'
  classifier:__choice__, Value: 'random_forest'
  classifier:random_forest:bootstrap, Value: 'False'
  classifier:random_forest:criterion, Value: 'entropy'
  classifier:random_forest:max_depth, Constant: 'None'
  classifier:random_forest:max_features, Value: 2.092036159294316
  classifier:random_forest:max_leaf_nodes, Constant: 'None'
  classifier:random_forest:min_samples_leaf, Value: 4
  classifier:random_forest:min_samples_split, Value: 19
  classifier:random_forest:min_weight_fraction_leaf, Constant: 0.0
  classifier:random_forest:n_estimators, Constant: 100
  imputation:strategy, Value: 'mean'
  one_hot_encoding:minimum_fraction, Value: 0.05188399318167551
  one_hot_encoding:use_minimum_fraction, Value: 'True'
  preprocessor:__choice__, Value: 'gem'
  preprocessor:gem:N, Value: 17
  preprocessor:gem:precond, Value: 0.466684310030886
  rescaling:__choice__, Value: 'none'

[INFO] [2016-10-03 00:26:14,224:AutoMLSMBO(11)::foobar] Finished evaluating 30. configuration. **Duration: 120.681572; loss: 0.467259**; status 1; addition
al run info: ;duration: 120.68157243728638;num_run:00030
```

```
[INFO] [2016-10-03 00:08:44,072:AutoMLSMBO(5)::foobar] Starting to evaluate 24. configuration (from SMAC) with time limit 858s.
[INFO] [2016-10-03 00:08:44,076:AutoMLSMBO(5)::foobar] Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'xgradient_boosting'
  classifier:xgradient_boosting:base_score, Constant: 0.5
  classifier:xgradient_boosting:colsample_bylevel, Constant: 1
  classifier:xgradient_boosting:colsample_bytree, Constant: 1
  classifier:xgradient_boosting:gamma, Constant: 0
  classifier:xgradient_boosting:learning_rate, Value: 0.20506995243283785
  classifier:xgradient_boosting:max_delta_step, Constant: 0
  classifier:xgradient_boosting:max_depth, Value: 1
  classifier:xgradient_boosting:min_child_weight, Value: 10
  classifier:xgradient_boosting:n_estimators, Value: 458
  classifier:xgradient_boosting:reg_alpha, Constant: 0
  classifier:xgradient_boosting:reg_lambda, Constant: 1
  classifier:xgradient_boosting:scale_pos_weight, Constant: 1
  classifier:xgradient_boosting:subsample, Value: 0.5176375681985671
  imputation:strategy, Value: 'most_frequent'
  one_hot_encoding:use_minimum_fraction, Value: 'False'
  preprocessor:__choice__, Value: 'liblinear_svc_preprocessor'
  preprocessor:liblinear_svc_preprocessor:C, Value: 2.3329487475667747
  preprocessor:liblinear_svc_preprocessor:dual, Constant: 'False'
  preprocessor:liblinear_svc_preprocessor:fit_intercept, Constant: 'True'
  preprocessor:liblinear_svc_preprocessor:intercept_scaling, Constant: 1
  preprocessor:liblinear_svc_preprocessor:loss, Value: 'squared_hinge'
  preprocessor:liblinear_svc_preprocessor:multi_class, Constant: 'ovr'
  preprocessor:liblinear_svc_preprocessor:penalty, Constant: 'l1'
  preprocessor:liblinear_svc_preprocessor:tol, Value: 0.0309806749873134
  rescaling:__choice__, Value: 'standardize'
[INFO] [2016-10-03 00:23:04,520:AutoMLSMBO(5)::foobar] Finished evaluating 24. configuration. **Duration: 859.181305; loss: 2.000000**; status 2; additional run info:
```

**Comment by mfeurer** [comment]
The actual issue with GEM is not it's performance, but the lack of a maintainer and the fact that auto-sklearn is the wrong package for this piece of code (should be a ML package). If the code was in scikit-learn I would immediately keep it because I've seen that it can work very well for some datasets.

Currently, I'm mostly trying to find time to fix all the issues with auto-sklearn and cannot really test it. I hope that I find some time to work more on auto-sklearn in the near future.

**Comment by mfeurer** [comment]
I just merged a PR to the development branch which removes GEM. Therefore, it'll be gone in the next bugfix release.
