### ISSUE TITLE
When dataset is mostly zeros I get an error 

### ISSUE THREAD

**Issue by asmgx** [automl/auto-sklearn#1441]
When dataset is mostly zeros I get an error when call leaderboard()

>>> print(automl.leaderboard())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/my/anaconda3/lib/python3.8/site-packages/autosklearn/estimators.py", line 841, in leaderboard
    model_runs[model_id]['ensemble_weight'] = weight
KeyError: 1

during fitting I got many of dummy model

[WARNING] [2022-04-17 18:07:09,063:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-04-17 18:07:21,429:smac.runhistory.runhistory2epm.RunHistory2EPM4LogCost] Got cost of smaller/equal to 0. Replace by 0.000010 since we use log cost.
[WARNING] [2022-04-17 18:07:21,489:Client-EnsembleBuilder] No models better than random - using Dummy loss!Number of models besides current dummy model: 17. Number of dummy models: 1

My dataset is mainly zeros 

and I got F1 score of 100%

Autosklearn version is 0.14.6

**Comment by eddiebergman** [comment]
Hey @asmgx,

So it seems autosklearn never found a model that was better than Sklearn's [dummy classifier](https://scikit-learn.org/stable/modules/generated/sklearn.dummy.DummyClassifier.html). What's more, it seems the default strategy for the dummy classifier can achieve an F1 score of 100% which seems odd.

This seems like an interesting dataset to debug with, would you be able to share it?

Best,
Eddie

**Comment by asmgx** [comment]
Here is dataset that i used attached (X_train and y_train)
[data.zip](https://github.com/automl/auto-sklearn/files/8509692/data.zip)

**Comment by eddiebergman** [comment]
Sorry I havn't got around to trying this yet, I will give it a go next week or perhaps @mfeurer  who has tried it can give some feedback if there is any?
