### ISSUE TITLE
XGboostError

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#148]
```

Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 63, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 138, in fit_estimator
    self.pipeline_.steps[-1][-1].fit(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/xgradient_boosting.py", line 129, in fit
    self.estimator.fit(X, y)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/xgboost/sklearn.py", line 337, in fit
    missing=self.missing)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/xgboost/core.py", line 232, in __init__
    self._init_from_npy2d(data, missing)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/xgboost/core.py", line 284, in _init_from_npy2d
    ctypes.byref(self.handle)))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
xgboost.core.XGBoostError: b'std::bad_alloc'
```

**Comment by mfeurer** [comment]
Thanks for reporting this. @sfalkner can this error happen inside the pynisher or would the pynisher stop the process before it can produce such error due to requesting too much memory?

**Comment by sfalkner** [comment]
Is this just some debugging out, or does autosklearn actually fail because of it?
std::bad_alloc is inside C++ code. It indicates that the program tried to allocate beyond the limit which then fails like with that exception. I am not sure why this error is not caught by the pynisher or why this exception would make it to the surface.
@mfeurer did you ever add the traceback information into the pynisher for your debuggin? Because this is what it looks like to me.

**Comment by mfeurer** [comment]
This is debugging output of auto-sklearn. When talking to @sfalkner he assumed that xgboost raises the wrong exception. I opened an issue [at the xgboost issue tracker](https://github.com/dmlc/xgboost/issues/1629).
