### ISSUE TITLE
Uncaught exception? ValueError: SelectRates removed all features.

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#150]
I have re-installed auto-sklearn 0.0.2 from the github and just want to share what I see in the log, It does not break the overall process.

```
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/feature_selection/base.py:80: UserWarning: No features were selected: either the data is too noisy or the selection test too strict.
  UserWarning)
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 148, in _pre_transform
    .transform(Xt)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/select_rates.py", line 72, in transform
    "%s removed all features." % self.__class__.__name__)
ValueError: SelectRates removed all features.
```

**Comment by Motorrat** [comment]
`Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 116, in _ica_par
    warnings.warn('FastICA did not converge. Consider increasing '
UserWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
`

**Comment by Motorrat** [comment]
`n_components is too large: it will be set to 25
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 108, in _ica_par
    - g_wtx[:, np.newaxis] * W)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 55, in _sym_decorrelation
    s, u = linalg.eigh(np.dot(W, W.T))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/linalg/decomp.py", line 288, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/_lib/_util.py", line 228, in _asarray_validated
    a = toarray(a)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1033, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 36, in fit
    raise ValueError("Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738")
ValueError: Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738
`

**Comment by mfeurer** [comment]
Similar to #151, this output will no longer be there with this afternoons release.

**Comment by Motorrat** [comment]
I have re-installed the autosklearn 1.1 but still see the above error:

n_components is too large: it will be set to 23
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 108, in _ica_par
    - g_wtx[:, np.newaxis] * W)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 55, in _sym_decorrelation
    s, u = linalg.eigh(np.dot(W, W.T))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/linalg/decomp.py", line 288, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/_lib/_util.py", line 228, in _asarray_validated
    a = toarray(a)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1033, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self._fit_and_suppress_warnings(self.model, X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 335, in _fit_and_suppress_warnings
    model = model.fit(X, y)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 36, in fit
    raise ValueError("Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738")
ValueError: Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 108, in _ica_par
    - g_wtx[:, np.newaxis] * W)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 55, in _sym_decorrelation
    s, u = linalg.eigh(np.dot(W, W.T))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/linalg/decomp.py", line 288, in eigh
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/scipy/_lib/_util.py", line 228, in _asarray_validated
    a = toarray(a)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/numpy/lib/function_base.py", line 1033, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self._fit_and_suppress_warnings(self.model, X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 335, in _fit_and_suppress_warnings
    model = model.fit(X, y)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 36, in fit
    raise ValueError("Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738")
ValueError: Bug in scikit-learn: https://github.com/scikit-learn/scikit-learn/pull/2738
n_components is too large: it will be set to 23

**Comment by Motorrat** [comment]
and some time later in the log this has appeared:
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/base.py:284: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:688: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:688: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py:116: UserWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.
  warnings.warn('FastICA did not converge. Consider increasing '
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:688: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:688: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/linear_model/base.py:284: RuntimeWarning: overflow encountered in exp
  np.exp(prob, prob)

**Comment by mfeurer** [comment]
Is this only in the log file or also in the command line output? I moved all warnings into the log files, but the output is still there. 

Maybe there should be two log files, one with debug output and one with info output that is shows the progress of auto-sklearn.

**Comment by lsorber** [comment]
Still seeing `ValueError: SelectRates removed all features.` during training on 0.1.2.

**Comment by mfeurer** [comment]
Thanks for pointing that out.

**Comment by lsorber** [comment]
Also seeing `ValueError: Numerical problems in QDA. QDA.scalings_ contains values <= 0.0`, but it's less common (on an `np.float64` feature matrix where all features are in [0, 1]).

**Comment by mfeurer** [comment]
This failures should no longer be visible on stdout/stderr in the latest release (0.2.0).
