### ISSUE TITLE
ValueError: Numerical problems in QDA. QDA.scalings_ contains values <= 0.0

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#151]
```
/x/Redly/anaconda3/lib/python3.5/site-packages/sklearn/discriminant_analysis.py:688: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 63, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 138, in fit_estimator
    self.pipeline_.steps[-1][-1].fit(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/qda.py", line 41, in fit
    raise ValueError('Numerical problems in QDA. QDA.scalings_ '
ValueError: Numerical problems in QDA. QDA.scalings_ contains values <= 0.0

```

**Comment by mfeurer** [comment]
This output will no longer be visible to the user with this afternoons upcoming release, so I'm closing this now.
