### ISSUE TITLE
Timeout waiting to acquire lock

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#153]
[INFO] [2016-10-02 17:39:08,197:AutoMLSMBO(6)::foobar] Finished evaluating 6. configuration on SUBSET. Duration 1.845422; loss 1.587501; status 1; additional run info: ;duration: 1.8454220294952393;num_run:00006
[INFO] [2016-10-02 17:39:08,198:AutoMLSMBO(6)::foobar] Finished SUBSET training sucessfully with ratio 0.137986
[INFO] [2016-10-02 17:39:08,198:AutoMLSMBO(6)::foobar] Metadata directory: /x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/metalearning/files/f1_metric_binary.classification_dense
[INFO] [2016-10-02 17:39:08,828:AutoMLSMBO(6)::foobar] Start calculating metafeatures for foobar
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
FileExistsError: [Errno 17] File exists: '/x/Redly/truffles/nfs_share/atsklrn_tmp/.auto-sklearn/mgm-19-6811-61ee4700.195152254171169479775240' -> '/x/Redly/truffles/nfs_share/atsklrn_tmp/.auto-sklearn/datamanager.pkl.lock
.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(_args, *_kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 532, in run_smbo
    self.reset_data_manager()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 274, in reset_data_manager
    max_mem = max_mem)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 79, in load_data
    D = backend.load_datamanager()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/util/backend.py", line 143, in load_datamanager
    with lockfile.LockFile(lock_path, timeout=60):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/__init__.py", line 197, in **enter**
    self.acquire()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/linklockfile.py", line 46, in acquire
    self.path)
lockfile.LockTimeout: Timeout waiting to acquire lock for ./nfs_share/atsklrn_tmp/.auto-sklearn/datamanager.pkl.lock
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
FileExistsError: [Errno 17] File exists: '/x/Redly/truffles/nfs_share/atsklrn_tmp/.auto-sklearn/mgm-19-6811-61ee4700.195272254171169479775240' -> '/x/Redly/truffles/nfs_share/atsklrn_tmp/.auto-sklearn/datamanager.pkl.lock
.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(_self._args, *_self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(_args, *_kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 532, in run_smbo
    self.reset_data_manager()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 274, in reset_data_manager
    max_mem = max_mem)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/smbo.py", line 79, in load_data
    D = backend.load_datamanager()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/util/backend.py", line 143, in load_datamanager
    with lockfile.LockFile(lock_path, timeout=60):
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/__init__.py", line 197, in **enter**
    self.acquire()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/lockfile/linklockfile.py", line 46, in acquire
    self.path)
lockfile.LockTimeout: Timeout waiting to acquire lock for ./nfs_share/atsklrn_tmp/.auto-sklearn/datamanager.pkl.lock

**Comment by mfeurer** [comment]
@Motorrat could you please check whether this issue is still present in the latest version of auto-sklearn. I think I found the culprit and removed it.

**Comment by mfeurer** [comment]
I'm closing this now because of inactivity and because I think the issue is solved. Please re-open if the issue still exists with `auto-sklearn>=0.2.1`.

**Comment by rabsr** [comment]
@mfeurer I am experiencing this issue with 0.7.0 version of Autosklearn. I am facing this issue only when I use NFS directory for temp and out directory. It works fine when used with local directory.

**Comment by mfeurer** [comment]
Do you observe the same error message?

**Comment by rabsr** [comment]
@mfeurer  Execution hangs for long time. On interrupting the execution I get the following logs:

```Traceback (most recent call last):
  File "nfs_mount/automl/lib/python3.5/site-packages/lockfile/linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
OSError: [Errno 5] Input/output error: ’nfs_mount/temp/.auto-sklearn/hostname-a8b56740.649-289117862387046132' -> ‘nfs_mount/temp/.auto-sklearn/datamanager.pkl.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "automl/examples/example_custom_scaler.py", line 43, in <module>
    main()
  File "automl/examples/example_custom_scaler.py", line 28, in main
    clf.fit(X_train, y_train, dataset_name='breast_cancer')
  File “nfs_mount/automl/lib/python3.5/site-packages/autosklearn/estimators.py", line 681, in fit
    dataset_name=dataset_name,
  File "nfs_mount/automl/lib/python3.5/site-packages/autosklearn/estimators.py", line 351, in fit
    self._automl[0].fit(**kwargs)
  File "nfs_mount/automl/lib/python3.5/site-packages/autosklearn/automl.py", line 1026, in fit
    load_models=load_models,
  File "nfs_mount/automl/lib/python3.5/site-packages/autosklearn/automl.py", line 213, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "nfs_mount/automl/lib/python3.5/site-packages/autosklearn/automl.py", line 383, in _fit
    self._backend.save_datamanager(datamanager)
  File "nfs_mount4/automl/lib/python3.5/site-packages/autosklearn/util/backend.py", line 300, in save_datamanager
    with lockfile.LockFile(filepath):
  File "nfs_mount/automl/lib/python3.5/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "nfs_mount/automl/lib/python3.5/site-packages/lockfile/linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
KeyboardInterrupt```

**Comment by mfeurer** [comment]
From your error message it looks like there is an issue with your nfs in that it's not possible to create a link. Can you execute commands such as `ls`, `mv` and `cp` on your nfs from the command line?

**Comment by rabsr** [comment]
@mfeurer Yes, I am able to perform all commands `ls`, `mv`, `cp`, `rm` etc on nfs.

**Comment by mfeurer** [comment]
@rabsr I just see that I never followed up on this. If this is still an issue with the latest version of Auto-sklearn, could you please create a new issue? It's hard to keep track of closed issues.
