### ISSUE TITLE
ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output

### ISSUE THREAD

**Issue by belzheng** [automl/auto-sklearn#1534]
# Short Question Description
When I regressed the data using autosklearn, the first time it was successful, but the following errors were reported when I re-fitted the data:
![2](https://user-images.githubusercontent.com/91657801/175953985-ba420a28-12e7-476f-9c8d-bf0e2c6a21ff.PNG)
![1](https://user-images.githubusercontent.com/91657801/175952705-19efc62f-a885-4d1f-b0aa-ac64eab29120.PNG)

# System Details (if relevant)
* Which version of `auto-sklearn` are you using? 0.14.7

**Comment by belzheng** [comment]
I want to emphasize that two weeks ago I had no problem running the same code, but when I tried to run the code again, the problem I was talking about came up, and I wanted to know if there was a solution?
Thanks!

**Comment by eddiebergman** [comment]
Hi @belzheng,

Could you copy and paste the two outputs here so I can look at them properly?

Best,
Eddie

**Comment by belzheng** [comment]
OpenBLAS blas_thread_init: pthread_create failed for thread 31 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 32 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 33 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 34 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 35 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 36 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 37 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 38 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 39 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 40 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 41 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 45 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 48 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 49 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 50 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 51 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 52 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 53 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 54 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 55 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 56 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 57 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 58 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 59 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 60 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 61 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 62 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 514040 current, 514040 max
[ERROR] [2022-06-28 13:14:46,754:Client-AutoML(1):394036e3-f6a1-11ec-b3a9-e14937a945cb] Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': 'Process pynisher function call:\nTraceback (most recent call last):\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap\n    self.run()\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/multiprocessing/process.py", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/pynisher/limit_function_call.py", line 133, in subprocess_func\n    return_value = ((func(*args, **kwargs), 0))\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/__init__.py", line 42, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py", line 1175, in eval_holdout\n    evaluator = TrainEvaluator(\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py", line 183, in __init__\n    super().__init__(\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 202, in __init__\n    threadpool_limits(limits=1)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 373, in __init__\n    super().__init__(ThreadpoolController(), limits=limits, user_api=user_api)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 166, in __init__\n    self._set_threadpool_limits()\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 299, in _set_threadpool_limits\n    lib_controller.set_num_threads(num_threads)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 865, in set_num_threads\n    return set_func(num_threads)\nKeyboardInterrupt\n', 'exitcode': 1, 'configuration_origin': 'DUMMY'}.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 reg(X2_train, X2_test, y2_train, y2_test)

Input In [10], in reg(X_train, X_test, y_train, y_test)
     23 # with autosklearn
     24 ## using abess with autosklearn and specify the feature preprocessor
     25 regap = autosklearn.regression.AutoSklearnRegressor(
     26     time_left_for_this_task=60,
     27     per_run_time_limit=10,
   (...)
     32     memory_limit=6144,
     33 )
---> 34 regap.fit(X_train.values, y_train)
     35 yap_pred = regap.predict(X_test.values)
     36 r2_scoreap = sklearn.metrics.r2_score(yap_pred, y_test)

File ~/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/estimators.py:1191, in AutoSklearnRegressor.fit(self, X, y, X_test, y_test, feat_type, dataset_name)
   1178     raise ValueError("Regression with data of type {} is "
   1179                      "not supported. Supported types are {}. "
   1180                      "You can find more information about scikit-learn "
   (...)
   1186                         )
   1187                      )
   1189 # Fit is supposed to be idempotent!
   1190 # But not if we use share_mode.
-> 1191 super().fit(
   1192     X=X,
   1193     y=y,
   1194     X_test=X_test,
   1195     y_test=y_test,
   1196     feat_type=feat_type,
   1197     dataset_name=dataset_name,
   1198 )
   1200 return self

File ~/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/estimators.py:375, in AutoSklearnEstimator.fit(self, **kwargs)
    373 if self.automl_ is None:
    374     self.automl_ = self.build_automl()
--> 375 self.automl_.fit(load_models=self.load_models, **kwargs)
    377 return self

File ~/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/automl.py:2133, in AutoMLRegressor.fit(self, X, y, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models)
   2122 def fit(
   2123     self,
   2124     X: SUPPORTED_FEAT_TYPES,
   (...)
   2131     load_models: bool = True,
   2132 ):
-> 2133     return super().fit(
   2134         X, y,
   2135         X_test=X_test,
   2136         y_test=y_test,
   2137         feat_type=feat_type,
   2138         dataset_name=dataset_name,
   2139         only_return_configuration_space=only_return_configuration_space,
   2140         load_models=load_models,
   2141         is_classification=False,
   2142     )

File ~/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/automl.py:808, in AutoML.fit(self, X, y, task, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models, is_classification)
    804     return self.configuration_space
    806 # == Perform dummy predictions
    807 # Dummy prediction always have num_run set to 1
--> 808 self.num_run += self._do_dummy_prediction(datamanager, num_run=1)
    810 # == RUN ensemble builder
    811 # Do this before calculating the meta-features to make sure that the
    812 # dummy predictions are actually included in the ensemble even if
    813 # calculating the meta-features takes very long
    814 ensemble_task_name = 'runEnsemble'

File ~/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/automl.py:476, in AutoML._do_dummy_prediction(self, datamanager, num_run)
    471         self._logger.error(
    472             "Dummy prediction failed with run state %s and additional output: %s.",
    473             str(status), str(additional_info),
    474         )
    475         # Fail if dummy prediction fails.
--> 476         raise ValueError(
    477             "Dummy prediction failed with run state %s and additional output: %s."
    478             % (str(status), str(additional_info))
    479         )
    480 return num_run

ValueError: Dummy prediction failed with run state StatusType.CRASHED and additional output: {'error': 'Result queue is empty', 'exit_status': "<class 'pynisher.limit_function_call.AnythingException'>", 'subprocess_stdout': '', 'subprocess_stderr': 'Process pynisher function call:\nTraceback (most recent call last):\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap\n    self.run()\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/multiprocessing/process.py", line 108, in run\n    self._target(*self._args, **self._kwargs)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/pynisher/limit_function_call.py", line 133, in subprocess_func\n    return_value = ((func(*args, **kwargs), 0))\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/__init__.py", line 42, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py", line 1175, in eval_holdout\n    evaluator = TrainEvaluator(\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/train_evaluator.py", line 183, in __init__\n    super().__init__(\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 202, in __init__\n    threadpool_limits(limits=1)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 373, in __init__\n    super().__init__(ThreadpoolController(), limits=limits, user_api=user_api)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 166, in __init__\n    self._set_threadpool_limits()\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 299, in _set_threadpool_limits\n    lib_controller.set_num_threads(num_threads)\n  File "/data/home/zy/.conda/envs/zy/lib/python3.9/site-packages/threadpoolctl.py", line 865, in set_num_threads\n    return set_func(num_threads)\nKeyboardInterrupt\n', 'exitcode': 1, 'configuration_origin': 'DUMMY'}.

**Comment by eddiebergman** [comment]
I would guess from reading this it's something to do with some scikit-learn based parallelism and your system constraints. Please refer to this [sklearn documentation](https://scikit-learn.org/stable/computing/parallelism.html?highlight=joblib#oversubscription-spawning-too-many-threads).

For more details, `RLIMIT_NPROC` is a system limit on how many threads can be spawned as your user on your system, i.e. `RLIMIT_NPROC 514040 current, 514040 max`. If you have some other application running on your system, it may also be spawning a lot of threads and at some point, that limit is reached. This is not really an auto-sklearn issue but does show up in auto-sklearn issues from time to time. The fix is usually the ones given in the scikit learn documentation above.

You can learn more about `RLIMIT_<X>` if curious [here](https://man7.org/linux/man-pages/man2/getrlimit.2.html)
