### ISSUE TITLE
numpy.linalg.linalg.LinAlgError: Matrix is not positive definite

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#154]
```
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 63, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 138, in fit_estimator
    self.pipeline_.steps[-1][-1].fit(X, y, **fit_params)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/classification/proj_logit.py", line 21, in fit
    self.estimator.fit(X, Y)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/implementations/ProjLogit.py", line 41, in fit
    C = np.linalg.cholesky(0.5 * np.dot(trainx.T,trainx) + precond)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 612, in cholesky
    r = gufunc(a, signature=signature, extobj=extobj)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/numpy/linalg/linalg.py", line 93, in _raise_linalgerror_nonposdef
    raise LinAlgError("Matrix is not positive definite")
numpy.linalg.linalg.LinAlgError: Matrix is not positive definite
```

**Comment by mfeurer** [comment]
Thanks for reporting this. Similar to #144, we already scheduled ProjLogit for removal.

**Comment by mfeurer** [comment]
I just merged the removal of ProjLogit into the development branch. It'll be removed from auto-sklearn in the next bugfix release.
