### ISSUE TITLE
Import pyrfr.regression error

### ISSUE THREAD

**Issue by hello2all** [automl/auto-sklearn#159]
I can not get it work under python 2.7, however 3.5 version works just fine. The error occurred while importing  autosklearn.classification:
```python
from autosklearn.classification import AutoSklearnClassifier
```

```
Traceback (most recent call last):                                                                                                                           
  File "<stdin>", line 1, in <module>                                                                                                                        
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>                                            
    from autosklearn.estimators import AutoSklearnClassifier                                                                                                 
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/autosklearn/estimators.py", line 8, in <module>                                                
    import autosklearn.automl                                                                                                                                
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 27, in <module>                                                   
    from autosklearn.smbo import AutoMLSMBO                                                                                                                  
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/autosklearn/smbo.py", line 14, in <module>                                                     
    from smac.smbo.smbo import SMBO, get_types                                                                                                               
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/smac/smbo/smbo.py", line 15, in <module>                                                       
    from smac.epm.rf_with_instances import RandomForestWithInstances                                                                                         
  File "/home/liangyuan/anaconda2/lib/python2.7/site-packages/smac/epm/rf_with_instances.py", line 4, in <module>                                            
    import pyrfr.regression                                                                                                                                  
ImportError: /home/liangyuan/anaconda2/lib/python2.7/site-packages/pyrfr/regression.so: undefined symbol: _ZTVNSt7__cxx1118basic_stringstreamIcSt11char_trait
sIcESaIcEEE 
```
System Info:
```
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40)                                                                                    
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2  
```
I've tried reinstall auto-sklearn and all its dependencies under a new env, but the issue persists.

**Comment by mfeurer** [comment]
Thanks for reporting this. Often, `ImportErrors` regarding the random forest are a problem with anaconda, see issue #101. Do you need to use auto-sklearn in python2.7? If no, I advise you to use it under python3.5. The next release will be python3 only.

**Comment by hello2all** [comment]
@mfeurer Thanks for the reply, I'll stick to python 3 then.
