### ISSUE TITLE
OSError: [Errno 22] Invalid argument error during AutoSklearnClassifier fitting

### ISSUE THREAD

**Issue by manuelinfosec** [automl/auto-sklearn#1623]
While trying to fit X_train and y_train using AutoSklearnClassifier, it produces this error: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.8/multiprocessing/forkserver.py", line 207, in main
    with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument
```
The surprising thing is, it works perfectly with same parameters on Google Colab.

The parameters used for initializing AutoSklearnClassifier are:
- "time_left_for_this_task": 30,
- "run_time_limit":14.0,
- "n_jobs": 5,

## Environment and installation: ##

Please give details about your installation:

* OS: Windows Subsystem For Linux
* I don't use a virtual environment
* Python version:  3.8.10
* Auto-sklearn version: 0.15.0
* ConfigSpace version: 0.4.21

All packages and version:
```
Package                       Version
----------------------------- --------------------
-onfigSpace                   0.4.21
absl-py                       1.3.0
apyori                        1.1.2
asgiref                       3.5.2
astunparse                    1.6.3
attrs                         19.3.0
auto-sklearn                  0.15.0
Automat                       0.8.0
blinker                       1.4
boto3                         1.24.51
botocore                      1.27.51
cachetools                    5.2.0
certifi                       2019.11.28
cffi                          1.15.1
chardet                       3.0.4
charset-normalizer            2.1.0
Click                         7.0
cloud-init                    22.2
cloudpickle                   2.2.0
colorama                      0.4.3
command-not-found             0.3
configobj                     5.0.6
ConfigSpace                   0.4.21
constantly                    15.1.0
cryptography                  37.0.4
Cython                        0.29.32
dask                          2022.11.1
dbus-python                   1.2.16
defusedxml                    0.7.1
distributed                   2022.11.1
distro                        1.4.0
distro-info                   0.23ubuntu1
Django                        3.2.15
django-allauth                0.51.0
django-cors-headers           3.13.0
django-rest-auth              0.9.5
django-rest-passwordreset     1.2.1
djangorestframework           3.13.1
djangorestframework-api-key   2.2.0
djangorestframework-simplejwt 5.2.0
emcee                         3.1.3
entrypoints                   0.3
flatbuffers                   22.10.26
fsspec                        2022.11.0
gast                          0.4.0
google-auth                   2.14.1
google-auth-oauthlib          0.4.6
google-pasta                  0.2.0
grpcio                        1.51.0
h5py                          3.7.0
HeapDict                      1.0.1
httplib2                      0.14.0
hyperlink                     19.0.0
idna                          3.3
importlib-metadata            5.0.0
incremental                   16.10.1
Jinja2                        2.10.1
jmespath                      1.0.1
joblib                        1.2.0
jsonpatch                     1.22
jsonpointer                   2.0
jsonschema                    3.2.0
keras                         2.10.0
Keras-Preprocessing           1.1.2
keyring                       18.0.1
language-selector             0.1
launchpadlib                  1.10.13
lazr.restfulclient            0.14.2
lazr.uri                      1.0.3
liac-arff                     2.5.0
libclang                      14.0.6
locket                        1.0.0
Markdown                      3.4.1
MarkupSafe                    2.1.1
MiniSom                       2.3.0
more-itertools                4.2.0
msgpack                       1.0.4
mysql-connector               2.2.9
mysql-connector-python        8.0.30
netifaces                     0.10.4
nltk                          3.7
numpy                         1.23.5
oauthlib                      3.2.0
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.3.5
partd                         1.3.0
pexpect                       4.6.0
Pillow                        9.3.0
pip                           20.0.2
protobuf                      3.9.2
psutil                        5.9.4
pyasn1                        0.4.2
pyasn1-modules                0.2.1
pycparser                     2.21
PyGObject                     3.36.0
PyHamcrest                    1.9.0
PyJWT                         2.4.0
pymacaroons                   0.13.0
PyMySQL                       1.0.2
PyNaCl                        1.3.0
pynisher                      0.6.4
pyodbc                        4.0.34
pyOpenSSL                     22.1.0
pyparsing                     3.0.9
pyrfr                         0.8.3
pyrsistent                    0.15.5
pyserial                      3.4
python-apt                    2.0.0+ubuntu0.20.4.8
python-dateutil               2.8.2
python-debian                 0.1.36ubuntu1
python3-openid                3.2.0
pytz                          2022.1
PyYAML                        5.3.1
regex                         2022.10.31
requests                      2.28.1
requests-oauthlib             1.3.1
requests-unixsocket           0.2.0
rsa                           4.9
s3transfer                    0.6.0
scikit-learn                  0.24.2
scipy                         1.9.3
SecretStorage                 2.3.1
service-identity              18.1.0
setuptools                    45.2.0
simplejson                    3.16.0
six                           1.14.0
smac                          1.2
sortedcontainers              2.4.0
sos                           4.3
sqlparse                      0.4.2
ssh-import-id                 5.10
systemd-python                234
tblib                         1.7.0
tensorboard                   2.10.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.10.0
tensorflow-estimator          2.10.0
tensorflow-io-gcs-filesystem  0.27.0
termcolor                     2.1.1
threadpoolctl                 3.1.0
toolz                         0.12.0
tornado                       6.1
tqdm                          4.64.1
Twisted                       18.9.0
typing                        3.7.4.3
typing-extensions             4.3.0
ubuntu-advantage-tools        27.10
ufw                           0.36
unattended-upgrades           0.1
urllib3                       1.26.10
wadllib                       1.3.3
Werkzeug                      2.2.2
wget                          3.2
wheel                         0.34.2
whitenoise                    6.2.0
wrapt                         1.14.1
xgboost                       0.90
zict                          2.2.0
zipp                          1.0.0
zope.interface                4.7.1
```

**Comment by manuelinfosec** [comment]
Surprisingly, I removed the n_jobs parameter, and it worked.
