### ISSUE TITLE
AttributeError: 'Pipeline' object has no attribute '_pre_transform'

### ISSUE THREAD

**Issue by colingoldberg** [automl/auto-sklearn#165]
Hi,

Running the 'digits' example provided, I get (many) multiple reports of the same error (AttributeError: 'Pipeline' object has no attribute '_pre_transform'), although this does not seem to stop it from continuing, seemingly forever. Eventually I interrupted it.

A typical output was:
[INFO] [2016-10-13 18:58:18,967:AutoMLSMBO(1)::fe2c91440a6f3a3a6119220eba306822] Finished evaluating 581. configuration. Duration: 1.025522; loss: 2.000000; status 3; additional run info:  
[ERROR] [2016-10-13 18:58:19,076:AutoMLSMBO(1)::fe2c91440a6f3a3a6119220eba306822] zero-size array to reduction operation minimum which has no identity
[ERROR] [2016-10-13 18:58:19,077:AutoMLSMBO(1)::fe2c91440a6f3a3a6119220eba306822] Error in getting next configurations with SMAC. Using random configuration!
[INFO] [2016-10-13 18:58:19,098:AutoMLSMBO(1)::fe2c91440a6f3a3a6119220eba306822] Starting to evaluate 582. configuration (from SMAC) with time limit 360s.
[INFO] [2016-10-13 18:58:19,098:AutoMLSMBO(1)::fe2c91440a6f3a3a6119220eba306822] Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'proj_logit'
  classifier:proj_logit:max_epochs, Value: 10
  imputation:strategy, Value: 'mean'
  one_hot_encoding:use_minimum_fraction, Value: 'False'
  preprocessor:__choice__, Value: 'feature_agglomeration'
  preprocessor:feature_agglomeration:affinity, Value: 'manhattan'
  preprocessor:feature_agglomeration:linkage, Value: 'average'
  preprocessor:feature_agglomeration:n_clusters, Value: 194
  preprocessor:feature_agglomeration:pooling_func, Value: 'median'
  rescaling:__choice__, Value: 'none'

Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/pipeline/base.py", line 62, in fit
    init_params=init_params)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/pipeline/classification.py", line 87, in pre_transform
    X, y, fit_params=fit_params, init_params=init_params)
  File "/usr/local/lib64/python2.7/site-packages/autosklearn/pipeline/base.py", line 131, in pre_transform
    X, fit_params = self.pipeline_._pre_transform(X, y, **fit_params)
AttributeError: 'Pipeline' object has no attribute '_pre_transform'

Regards

Colin Goldberg

**Comment by mfeurer** [comment]
Hi,

it seems you are using scikit-learn 0.18. auto-sklearn currently only supports 0.17. Please downgrade your scikit-learn version to use auto-sklearn.

I opened #170 to add a warning in such cases.
