### ISSUE TITLE
Is there any way to tune hyperparameters that are 2D arrays

### ISSUE THREAD

**Issue by belzheng** [automl/auto-sklearn#1678]
# Short Question Description
I want to adjust the knots position of Bspline, but it is a two-dimensional array, I don't know how to use auto-sklearn to adjust it, I will be grateful if you can give a solution.

**Comment by eddiebergman** [comment]
Hi,

You'll have to [create your own custom Estimator](https://automl.github.io/auto-sklearn/master/examples/80_extending/example_extending_preprocessor.html#create-lda-component-for-auto-sklearn) and in the space, specify a hyperparameter for each entry of the array.

Take a look at [`MLP::get_hyperparameter_search_space()`](https://github.com/automl/auto-sklearn/blob/673211252ca508b6f5bb92cf5fa87c6455bbad99/autosklearn/pipeline/components/classification/mlp.py#L213-L218) where we define two hyperprameters which get joined together as a [single hyperparameter in the estimator](https://github.com/automl/auto-sklearn/blob/673211252ca508b6f5bb92cf5fa87c6455bbad99/autosklearn/pipeline/components/classification/mlp.py#L93-L95)

**Comment by belzheng** [comment]
Thank you for your answer. My problem now is that the defined hyperparameters put into auto-sklearn will report a type error, the specific code is as follows:
```python
dataset = fetch_openml(data_id = int(189))
X=dataset.data
y=dataset.target
#drop rows with nan or inf
X.replace([np.inf,-np.inf],np.NaN,inplace=True)
inx=X[X.isna().values==True].index.unique().tolist()
X.drop(inx,inplace=True)
y.drop(inx,inplace=True)
y = np.array(y)
#use dummy variables to replace catogory variables:
X = pd.get_dummies(X)
## Keep only numeric columns
X = X.select_dtypes(np.number)
## Remove columns with NaN or Inf values
nan = np.isnan(X).any()[np.isnan(X).any() == True]
inf = np.isinf(X).any()[np.isinf(X).any() == True]
X.drop(columns = list(nan.index), inplace = True)
X.drop(columns = list(inf.index), inplace = True)
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
y_scaled = scaler.fit_transform(y.reshape(-1, 1))
p = X.shape[1]
print("the number of features:", p)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_scaled, random_state=42)

def generate_knots_param(p):
    param_names = []
    for i in range(p):
        param_range = np.percentile(np.random.uniform(0, 1, size=1000), np.linspace(0, 100, num=10))
        for j, value in enumerate(param_range):
            param_name = f"knots_{i}_{j}"
            param_names.append((param_name, value))
    return param_names
x_knots = generate_knots_param(p)

class Bspline(AutoSklearnPreprocessingAlgorithm):
    def __init__(self, n_knots, degree, extrapolation, x_knots, random_state=None):
        self.n_knots = n_knots
        self.degree = degree
        self.extrapolation = extrapolation   
        self.x_knots = x_knots
        knots_values = np.array([value for _, value in x_knots]).reshape(10,p)
        self.knots = np.sort(np.unique(knots_values, axis=0), axis=0)

        self.random_state = random_state
        self.preprocessor = None

    def fit(self, X, y=None):
        self.degree = int(self.degree)
        self.n_knots = int(self.n_knots)

        self.knots = self.knots[:self.n_knots]

        self.preprocessor = SplineTransformer(
            n_knots=self.n_knots, 
            degree=self.degree,
            knots=self.knots,
            extrapolation=self.extrapolation,
            include_bias=False
        )
        self.preprocessor.fit(X, y)
        return self

    def transform(self, X):
        if self.preprocessor is None:
            raise NotImplementedError()
        return self.preprocessor.transform(X)

    @staticmethod
    def get_properties(dataset_properties=None):
        return {
            "shortname": "Bspline",
            "name": "Bspline transformer",
            "handles_regression": True,
            "handles_classification": True,
            "handles_multiclass": True,
            "handles_multilabel": True,
            "handles_multioutput": True,
            "is_deterministic": True,
            "input": (DENSE, UNSIGNED_DATA, SIGNED_DATA),
            "output": (DENSE, UNSIGNED_DATA, SIGNED_DATA),
        }

    

    @staticmethod
    def get_hyperparameter_search_space(feat_type: Optional[FEAT_TYPE_TYPE] = None, dataset_properties=None):
        cs = ConfigurationSpace()

        n_knots = UniformIntegerHyperparameter("n_knots", 2, 10, default_value=5)
        degree = UniformIntegerHyperparameter("degree", 1, 2, default_value=2)
        extrapolation = CategoricalHyperparameter("extrapolation", ["constant", "linear"], default_value="constant")

        cs.add_hyperparameters([n_knots, degree, extrapolation])

     
        for param_name, value in x_knots:
            param = UniformFloatHyperparameter(param_name, 0, 1, default_value=value)
            cs.add_hyperparameter(param)

        return cs

# Add Bspline component to auto-sklearn.
autosklearn.pipeline.components.feature_preprocessing.add_preprocessor(Bspline)

class AbessRegression(AutoSklearnRegressionAlgorithm):

    def __init__(self, random_state=None):
        #self.exchange_num = exchange_num
        self.random_state = random_state
        self.estimator = None

    def fit(self, X, y):
        from abess import LinearRegression
        self.estimator = LinearRegression()
        self.estimator.fit(X, y)
        return self

    def predict(self, X):
        if self.estimator is None:
            raise NotImplementedError
        return self.estimator.predict(X)

    @staticmethod
    def get_properties(dataset_properties=None):
        return {
            'shortname': 'abess',
            'name': 'abess linear regression',
            'handles_regression': True,
            'handles_classification': False,
            'handles_multiclass': False,
            'handles_multilabel': False,
            'handles_multioutput': True,
            'is_deterministic': True,
            'input': (SPARSE, DENSE, UNSIGNED_DATA, SIGNED_DATA),
            'output': (PREDICTIONS,)
        }
    
    @staticmethod
    def get_hyperparameter_search_space(
        feat_type: Optional[FEAT_TYPE_TYPE] = None, dataset_properties=None
    ):
        cs = ConfigurationSpace() 
        #exchange_num=UniformIntegerHyperparameter(
         #   name='exchange_num', lower=4, upper=5, default_value=5
        #)
        #cs.add_hyperparameters([exchange_num])
        return cs
    
# Add abesscomponent to auto-sklearn.
autosklearn.pipeline.components.regression.add_regressor(AbessRegression)


regaallp = autosklearn.regression.AutoSklearnRegressor(
    time_left_for_this_task=300,
    per_run_time_limit=10,
    include={
        'feature_preprocessor':[
            'Bspline',
        ],
        'regressor': ['AbessRegression'],
    },
    memory_limit=6144*2,
    ensemble_size = 1,
)
regaallp.fit(X_train, y_train)
```
The error is as follows:
[ERROR] [2023-08-01 14:47:01,786:Client-AutoML(1):280a8eec-3037-11ee-88de-a0369f2673ee] __init__() got an unexpected keyword argument 'knots_0_0'
Traceback (most recent call last):
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py", line 751, in fit
    self.configuration_space, configspace_path = self._create_search_space(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py", line 2252, in _create_search_space
    configuration_space = pipeline.get_configuration_space(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/util/pipeline.py", line 49, in get_configuration_space
    return _get_regression_configuration_space(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/util/pipeline.py", line 96, in _get_regression_configuration_space
    configuration_space = SimpleRegressionPipeline(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/regression.py", line 85, in __init__
    super().__init__(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/base.py", line 90, in __init__
    self.set_hyperparameters(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/base.py", line 250, in set_hyperparameters
    node.set_hyperparameters(
  File "/data/home/zy/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/components/base.py", line 454, in set_hyperparameters
    self.choice = self.get_components()[choice](**new_params)
TypeError: __init__() got an unexpected keyword argument 'knots_0_0'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[28], line 13
      1 regaallp = autosklearn.regression.AutoSklearnRegressor(
      2     time_left_for_this_task=300,
      3     per_run_time_limit=10,
   (...)
     11     ensemble_size = 1,
     12 )
---> 13 regaallp.fit(X_train, y_train)
     14 yaallp_pred = regaallp.predict(X_test)
     15 r2_scoreaallp = sklearn.metrics.r2_score(yaallp_pred, y_test)

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/estimators.py:1587, in AutoSklearnRegressor.fit(self, X, y, X_test, y_test, feat_type, dataset_name)
   1576     raise ValueError(
   1577         "Regression with data of type {} is "
   1578         "not supported. Supported types are {}. "
   (...)
   1582         "".format(target_type, supported_types)
   1583     )
   1585 # Fit is supposed to be idempotent!
   1586 # But not if we use share_mode.
-> 1587 super().fit(
   1588     X=X,
   1589     y=y,
   1590     X_test=X_test,
   1591     y_test=y_test,
   1592     feat_type=feat_type,
   1593     dataset_name=dataset_name,
   1594 )
   1596 return self

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/estimators.py:540, in AutoSklearnEstimator.fit(self, **kwargs)
    538 if self.automl_ is None:
    539     self.automl_ = self.build_automl()
--> 540 self.automl_.fit(load_models=self.load_models, **kwargs)
    542 return self

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py:2394, in AutoMLRegressor.fit(self, X, y, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models)
   2383 def fit(
   2384     self,
   2385     X: SUPPORTED_FEAT_TYPES,
   (...)
   2392     load_models: bool = True,
   2393 ) -> AutoMLRegressor:
-> 2394     return super().fit(
   2395         X,
   2396         y,
   2397         X_test=X_test,
   2398         y_test=y_test,
   2399         feat_type=feat_type,
   2400         dataset_name=dataset_name,
   2401         only_return_configuration_space=only_return_configuration_space,
   2402         load_models=load_models,
   2403         is_classification=False,
   2404     )

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py:962, in AutoML.fit(self, X, y, task, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models, is_classification)
    959 except Exception as e:
    960     # This will be called before the _fit_cleanup
    961     self._logger.exception(e)
--> 962     raise e
    963 finally:
    964     self._fit_cleanup()

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py:751, in AutoML.fit(self, X, y, task, X_test, y_test, feat_type, dataset_name, only_return_configuration_space, load_models, is_classification)
    743 # = Create a searchspace
    744 # Do this before One Hot Encoding to make sure that it creates a
    745 # search space for a dense classifier even if one hot encoding would
   (...)
    748 # like this we can't use some of the preprocessing methods in case
    749 # the data became sparse)
    750 with self._stopwatch.time("Create Search space"):
--> 751     self.configuration_space, configspace_path = self._create_search_space(
    752         self._backend.temporary_directory,
    753         self._backend,
    754         datamanager,
    755         include=self._include,
    756         exclude=self._exclude,
    757     )
    759 if only_return_configuration_space:
    760     return self.configuration_space

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/automl.py:2252, in AutoML._create_search_space(self, tmp_dir, backend, datamanager, include, exclude)
   2243 def _create_search_space(
   2244     self,
   2245     tmp_dir: str,
   (...)
   2249     exclude: Optional[Mapping[str, list[str]]] = None,
   2250 ) -> Tuple[ConfigurationSpace, str]:
   2251     configspace_path = os.path.join(tmp_dir, "space.json")
-> 2252     configuration_space = pipeline.get_configuration_space(
   2253         datamanager,
   2254         include=include,
   2255         exclude=exclude,
   2256     )
   2257     backend.write_txt_file(
   2258         configspace_path,
   2259         cs_json.write(configuration_space),
   2260         "Configuration space",
   2261     )
   2263     return configuration_space, configspace_path

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/util/pipeline.py:49, in get_configuration_space(datamanager, include, exclude, random_state)
     27 """Get the configuration of a pipeline given some dataset info
     28 
     29 Parameters
   (...)
     46     The configuration space for the pipeline
     47 """
     48 if datamanager.info["task"] in REGRESSION_TASKS:
---> 49     return _get_regression_configuration_space(
     50         datamanager, include, exclude, random_state
     51     )
     52 else:
     53     return _get_classification_configuration_space(
     54         datamanager, include, exclude, random_state
     55     )

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/util/pipeline.py:96, in _get_regression_configuration_space(datamanager, include, exclude, random_state)
     92     sparse = True
     94 dataset_properties = {"multioutput": multioutput, "sparse": sparse}
---> 96 configuration_space = SimpleRegressionPipeline(
     97     feat_type=datamanager.feat_type,
     98     dataset_properties=dataset_properties,
     99     include=include,
    100     exclude=exclude,
    101     random_state=random_state,
    102 ).get_hyperparameter_search_space(feat_type=datamanager.feat_type)
    103 return configuration_space

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/regression.py:85, in SimpleRegressionPipeline.__init__(self, config, feat_type, steps, dataset_properties, include, exclude, random_state, init_params)
     83 if "target_type" not in dataset_properties:
     84     dataset_properties["target_type"] = "regression"
---> 85 super().__init__(
     86     feat_type=feat_type,
     87     config=config,
     88     steps=steps,
     89     dataset_properties=dataset_properties,
     90     include=include,
     91     exclude=exclude,
     92     random_state=random_state,
     93     init_params=init_params,
     94 )

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/base.py:90, in BasePipeline.__init__(self, config, feat_type, steps, dataset_properties, include, exclude, random_state, init_params)
     83         raise ValueError(
     84             "Configuration passed does not come from the "
     85             "same configuration space. Differences are: "
     86             "%s" % diff
     87         )
     88     self.config = config
---> 90 self.set_hyperparameters(
     91     self.config, feat_type=feat_type, init_params=init_params
     92 )
     94 super().__init__(steps=self.steps)
     96 self._additional_run_info = {}

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/base.py:250, in BasePipeline.set_hyperparameters(self, configuration, feat_type, init_params)
    245     sub_init_params_dict = None
    247 if isinstance(
    248     node, (AutoSklearnChoice, AutoSklearnComponent, BasePipeline)
    249 ):
--> 250     node.set_hyperparameters(
    251         feat_type=feat_type,
    252         configuration=sub_configuration,
    253         init_params=sub_init_params_dict,
    254     )
    255 else:
    256     raise NotImplementedError("Not supported yet!")

File ~/.conda/envs/zy1/lib/python3.9/site-packages/autosklearn/pipeline/components/base.py:454, in AutoSklearnChoice.set_hyperparameters(self, configuration, feat_type, init_params)
    451 new_params["random_state"] = self.random_state
    453 self.new_params = new_params
--> 454 self.choice = self.get_components()[choice](**new_params)
    456 return self

TypeError: __init__() got an unexpected keyword argument 'knots_0_0'

I've been confused for a few days and haven't found a solution, so I hope to get a solution from you, thank you very much!

**Comment by eddiebergman** [comment]
Hi @belzheng, your `__init__` doesn't take in the parameters that you mention, you'll have to accept them in the `__init__`. Since it's a variable amount, you might want to use `kwargs` in your init, i.e. `__init__(self, <other named params>, **kwargs)` and process them in the body using `kwargs["knot_0_0"]`.
