### ISSUE TITLE
Simple example has numerous errors and warnings

### ISSUE THREAD

**Issue by lesshaste** [automl/auto-sklearn#169]
I have tried the simple example at https://automl.github.io/auto-sklearn/stable/ and I get numerous errors and warnings.

```
>>> import autosklearn.classification
>>> import sklearn.datasets
>>> digits = sklearn.datasets.load_digits()
>>> X = digits.data
>>> y = digits.target
>>> import numpy as np
>>> indices = np.arange(X.shape[0])
>>> np.random.shuffle(indices)
>>> X = X[indices]
>>> y = y[indices]
>>> X_train = X[:1000]
>>> y_train = y[:1000]
>>> X_test = X[1000:]
>>> y_test = y[1000:]
>>> automl = autosklearn.classification.AutoSklearnClassifier()
>>> automl.fit(X_train, y_train)
>>> print(automl.score(X_test,y_test))
```

I get errors saying there is a negative score. For example:

```
[...]
You are already timing task: index_run9
[ERROR] [2016-10-16 21:54:54,338:EnsembleBuilder(1):c9e830b41452c05ae9e71bc900116020] Model only predicts at random: /tmp/autosklearn_tmp_5461_8805/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_00001.npy has score: -0.00704934541793
[ERROR] [2016-10-16 21:54:54,405:EnsembleBuilder(1):c9e830b41452c05ae9e71bc900116020] Model only predicts at random: /tmp/autosklearn_tmp_5461_8805/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_00056.npy has score: -0.0137630077207
[ERROR] [2016-10-16 21:54:54,408:EnsembleBuilder(1):c9e830b41452c05ae9e71bc900116020] Model only predicts at random: /tmp/autosklearn_tmp_5461_8805/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_00060.npy has score: -0.00369251426653
[...]
```

There are also these warnings and errors:

```
/home/user/.local/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:113: UserWarning: Features [ 0 16 32 39 56] are constant.
  UserWarning)
/home/user/.local/lib/python2.7/site-packages/sklearn/feature_selection/univariate_selection.py:114: RuntimeWarning: invalid value encountered in divide
  f = msb / msw
Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 148, in eval_holdout
    loss, opt_pred, valid_pred, test_pred = evaluator.fit_predict_and_loss()
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/evaluation/holdout_evaluator.py", line 59, in fit_predict_and_loss
    self.model.fit(X_train, Y_train)
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/pipeline/base.py", line 63, in fit
    self.fit_estimator(X, y, **fit_params)
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/pipeline/base.py", line 138, in fit_estimator
    self.pipeline_.steps[-1][-1].fit(X, y, **fit_params)
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/pipeline/components/classification/passive_aggressive.py", line 25, in fit
    self.iterative_fit(X, y, n_iter=1)
  File "/home/user/.local/lib/python2.7/site-packages/autosklearn/pipeline/components/classification/passive_aggressive.py", line 57, in iterative_fit
    self.estimator.partial_fit(X, y, classes=np.unique(y))
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/linear_model/passive_aggressive.py", line 141, in partial_fit
    coef_init=None, intercept_init=None)
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py", line 373, in _partial_fit
    sample_weight=sample_weight, n_iter=n_iter)
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py", line 457, in _fit_multiclass
    for i in range(len(self.classes_)))
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 800, in __call__
    while self.dispatch_one_batch(iterator):
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 658, in dispatch_one_batch
    self._dispatch(tasks)
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 566, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 180, in __init__
    self.results = batch()
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/home/user/.local/lib/python2.7/site-packages/sklearn/linear_model/stochastic_gradient.py", line 278, in fit_binary
    est.power_t, est.t_, intercept_decay)
  File "sklearn/linear_model/sgd_fast.pyx", line 404, in sklearn.linear_model.sgd_fast.plain_sgd (sklearn/linear_model/sgd_fast.c:4919)
  File "sklearn/linear_model/sgd_fast.pyx", line 697, in sklearn.linear_model.sgd_fast._plain_sgd (sklearn/linear_model/sgd_fast.c:7569)
ValueError: Floating-point under-/overflow occurred at epoch #1. Scaling input data with StandardScaler or MinMaxScaler might help.
```

FastICA also appears to fail showing a "Traceback (most recent call last)" which finishes with:

`UserWarning: FastICA did not converge. Consider increasing tolerance or the maximum number of iterations.`

There is also:

`/home/user/.local/lib/python2.7/site-packages/sklearn/utils/__init__.py:93: DeprecationWarning: Function transform is deprecated; Support to use estimators as feature selectors will be removed in version 0.19. Use SelectFromModel instead.`

There are also a number of warnings relating to the change in parameter names in sklearn 0.17 and 0.18 that appear.

and so on.

Is this all caused by a new version of sklearn?

**Comment by mfeurer** [comment]
Hi,

This is not caused by a new version of sklearn, but by auto-sklearn displaying all warnings/error messages on the screen. I will push a new version of auto-sklearn to pypi this afternoon. Have a look at the updated examples, they will not produce this output any more. 

If you still think the output is not useful after upgrading, please open a new issue.

**Comment by lesshaste** [comment]
Thank you I will definitely try that out. It was the Tracebacks that looked particularly worrying to me.
