### ISSUE TITLE
ValueError: (' Dummy prediction failed with run state StatusType.CRASHED and additional output

### ISSUE THREAD

**Issue by stupidoge** [automl/auto-sklearn#1707]
Everytime when I train the model, it said a symbol lookup error or a ValueError: (' Dummy prediction failed with run state StatusType.CRASHED and additional output.

I don't know what's the reason? Should I uninstall the package and install again? Just now, no wrong happen.

`python: symbol lookup error: /home/kevin/.conda/envs/dl/lib/python3.8/site-packages/mkl/../../../libmkl_intel_thread.so.2: undefined symbol: omp_get_num_procs
[ERROR] [2023-11-23 00:36:01,230:Client-AutoML(1):181b848b-8955-11ee-8904-8fca44d9fc97] (' Dummy prediction failed with run state StatusType.CRASHED and additional output: {\'error\': \'Result queue is empty\', \'exit_status\': "<class \'pynisher.limit_function_call.AnythingException\'>", \'subprocess_stdout\': \'\', \'subprocess_stderr\': \'\', \'exitcode\': 127, \'configuration_origin\': \'DUMMY\'}.',)
[ERROR] [2023-11-23 00:36:01,230:Client-AutoML(1):181b848b-8955-11ee-8904-8fca44d9fc97] (' Dummy prediction failed with run state StatusType.CRASHED and additional output: {\'error\': \'Result queue is empty\', \'exit_status\': "<class \'pynisher.limit_function_call.AnythingException\'>", \'subprocess_stdout\': \'\', \'subprocess_stderr\': \'\', \'exitcode\': 127, \'configuration_origin\': \'DUMMY\'}.',)
Traceback (most recent call last):
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 765, in fit
    self._do_dummy_prediction()
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 489, in _do_dummy_prediction
    raise ValueError(msg)
ValueError: (' Dummy prediction failed with run state StatusType.CRASHED and additional output: {\'error\': \'Result queue is empty\', \'exit_status\': "<class \'pynisher.limit_function_call.AnythingException\'>", \'subprocess_stdout\': \'\', \'subprocess_stderr\': \'\', \'exitcode\': 127, \'configuration_origin\': \'DUMMY\'}.',)
Traceback (most recent call last):
  File "test.py", line 365, in <module>
    automl.fit(X_train, y_train)
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/estimators.py", line 1448, in fit
    super().fit(
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/estimators.py", line 540, in fit
    self.automl_.fit(load_models=self.load_models, **kwargs)
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 2304, in fit
    return super().fit(
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 962, in fit
    raise e
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 765, in fit
    self._do_dummy_prediction()
  File "/home/kevin/.conda/envs/dl/lib/python3.8/site-packages/autosklearn/automl.py", line 489, in _do_dummy_prediction
    raise ValueError(msg)
ValueError: (' Dummy prediction failed with run state StatusType.CRASHED and additional output: {\'error\': \'Result queue is empty\', \'exit_status\': "<class \'pynisher.limit_function_call.AnythingException\'>", \'subprocess_stdout\': \'\', \'subprocess_stderr\': \'\', \'exitcode\': 127, \'configuration_origin\': \'DUMMY\'}.',)`

**Comment by sayannath** [comment]
I also received the same error. You system needs more memory. I ran the same project in Google Colab(free-tier), it worked.
