### ISSUE TITLE
ImportError: No module named deprecation

### ISSUE THREAD

**Issue by bscully** [automl/auto-sklearn#185]
Using the basic clf example, I get the following error:

Traceback (most recent call last):
  File "basic.py", line 1, in <module>
    import autosklearn.classification
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/autosklearn/estimators.py", line 7, in <module>
    import autosklearn.automl
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/autosklearn/automl.py", line 14, in <module>
    from sklearn.base import BaseEstimator
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/lib/anaconda2/envs/housing/lib/python2.7/site-packages/sklearn/utils/validation.py", line 19, in <module>
    from .deprecation import deprecated
ImportError: No module named deprecation

I installed with the requirements file so all versions should be correct.
Specifically sklearn is:   scikit-learn (0.17.1)

**Comment by mfeurer** [comment]
Are you sure that you're using scikit-learn 0.17.1? In the github repository I can't find an import on line 19 in the file [sklearn.utils.validation](https://github.com/scikit-learn/scikit-learn/blob/0.17.X/sklearn/utils/validation.py).

**Comment by bscully** [comment]
You are correct, I must not have activated the correct env, my mistake...
Closing the issue.
