### ISSUE TITLE
setup.py is broken

### ISSUE THREAD

**Issue by podshumok** [automl/auto-sklearn#198]
`setup.py` tries to import `autosklearn` (`autosklearn/__init__.py`) to get current version (which is not a good practice IMO)
This leads to import of packages that may be not installed currently (and which are supposed to be installed during `setup.py install` run)

```
  Running setup.py (path:/tmp/pip-build-11cr8m0d/auto-sklearn/setup.py) egg_info for package auto-sklearn
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-11cr8m0d/auto-sklearn/setup.py", line 2, in <module>
        import autosklearn
      File "/tmp/pip-build-11cr8m0d/auto-sklearn/autosklearn/__init__.py", line 2, in <module>
        from autosklearn.util import dependencies
      File "/tmp/pip-build-11cr8m0d/auto-sklearn/autosklearn/util/__init__.py", line 5, in <module>
        from .logging_ import *
      File "/tmp/pip-build-11cr8m0d/auto-sklearn/autosklearn/util/logging_.py", line 7, in <module>
        import yaml
    ImportError: No module named 'yaml'
```

UPD:

```
  Running setup.py (path:/tmp/pip-build-tkc9_89e/auto-sklearn/setup.py) egg_info for package auto-sklearn
    Running command python setup.py egg_info
    Traceback (most recent call last):
      File "/tmp/pip-build-tkc9_89e/auto-sklearn/autosklearn/util/dependencies.py", line 32, in _verify_package
        module = pkg_resources.get_distribution(name)
      File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 556, in get_distribution
        dist = get_provider(dist)
      File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 430, in get_provider
        return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
      File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 966, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib64/python3.5/site-packages/pkg_resources/__init__.py", line 852, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'xgboost' distribution was not found and is required by the application

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tkc9_89e/auto-sklearn/setup.py", line 2, in <module>
        import autosklearn
      File "/tmp/pip-build-tkc9_89e/auto-sklearn/autosklearn/__init__.py", line 15, in <module>
        dependencies.verify_packages(__MANDATORY_PACKAGES__)
      File "/tmp/pip-build-tkc9_89e/auto-sklearn/autosklearn/util/dependencies.py", line 25, in verify_packages
        _verify_package(name, operation, version)
      File "/tmp/pip-build-tkc9_89e/auto-sklearn/autosklearn/util/dependencies.py", line 34, in _verify_package
        raise MissingPackageError(name)
    autosklearn.util.dependencies.MissingPackageError: mandatory package 'xgboost' not found
```

**Comment by mfeurer** [comment]
Thanks for reporting this. Do you mean it would be preferable to duplicate the version information in `setup.py` and `__init__.py`? Otherwise, I would just make sure that not all utils are imported in the init files.

**Comment by podshumok** [comment]
This might help:
https://stackoverflow.com/questions/17583443/what-is-the-correct-way-to-share-package-version-with-setup-py-and-the-package

**Comment by mfeurer** [comment]
Thank you very much. I just updated the code accordingly, and this issue will be fixed in the next bugfix release.

**Comment by podshumok** [comment]
Looks like this should be re-opened as setup.py still doesn't work for the same reasons

**Comment by mfeurer** [comment]
Thanks for reporting this, indeed, I forgot to remove the actual import. I just added commit 79053ce0a45cb17a4c1b6d13f80eb29273bde0c8, which should fix this issue. Will be in the next bugfix release.
