### ISSUE TITLE
Cross-validation Error: DummyClassifier not fitted.

### ISSUE THREAD

**Issue by RedLiN5** [automl/auto-sklearn#208]
I ran _autosklearn_ with 5-fold cv. 
Codes are like:
``` Python
automl = autosklearn.classification.AutoSklearnClassifier(
    time_left_for_this_task=600, per_run_time_limit=300,
    tmp_folder=None,
    output_folder=None,
    resampling_strategy='cv', resampling_strategy_arguments={'folds': 5},
)
automl.fit(X_train.copy(), y_train.copy())
automl.refit(X_train.copy(), y_train.copy())
```

But an error was raised:
```Python
Traceback (most recent call last):
  File "/home/leslie/Desktop/auto-sklearn-master/example/automl_classification.py", line 145, in <module>
    main_cv()
  File "/home/leslie/Desktop/auto-sklearn-master/example/automl_classification.py", line 138, in main_cv
    automl_prediction = automl.predict(X_test)
  File "/home/leslie/Desktop/auto-sklearn-master/autosklearn/estimators.py", line 347, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/leslie/Desktop/auto-sklearn-master/autosklearn/estimators.py", line 66, in predict
    return self._automl.predict(X)
  File "/home/leslie/Desktop/auto-sklearn-master/autosklearn/estimators.py", line 503, in predict
    predicted_probabilities = self._automl.predict(X)
  File "/home/leslie/Desktop/auto-sklearn-master/autosklearn/automl.py", line 458, in predict
    prediction = model.predict_proba(X_)
  File "/home/leslie/Desktop/auto-sklearn-master/autosklearn/evaluation/abstract_evaluator.py", line 48, in predict_proba
    probas = super(MyDummyClassifier, self).predict_proba(new_X)
  File "/home/leslie/anaconda3/lib/python3.5/site-packages/sklearn/dummy.py", line 253, in predict_proba
    raise ValueError("DummyClassifier not fitted.")
ValueError: DummyClassifier not fitted.
```
DummyClassifier should be fitted at the beginning, but here it cannot be found.
Has anyone ever met this problem? And how to solve it? Thanks!

**Comment by RedLiN5** [comment]
@mfeurer Hi Matthias! Would you mind to check this out? Thanks!

**Comment by mfeurer** [comment]
This is weird, I did not encounter this issue yet. Could you please paste the complete logfile or make it accessible via pastebin? In order to find the logfile, it's best if you specify a `tmp_folder` and set `delete_tmp_folder_after_terminate` to `False`.

**Comment by RedLiN5** [comment]
@mfeurer  Thanks for responding me! 
Here is the [Uploading AutoML(1)_digits.zip…](logfile). I have to compress it so I can upload it here. 
'holdout' and other strategies work well on my laptop, but only 'cv' is down. 
Look forward to your reply!

**Comment by RedLiN5** [comment]
It's my fault!!!!!
Probably it's because I edited some parts of source code, so this error happened.
I have uninstalled my old auto-sklearn and installed a new one.  The issue has been solved.

But still thank you a lot! @mfeurer
