### ISSUE TITLE
SMAC Syntax Error

### ISSUE THREAD

**Issue by hyperdo** [automl/auto-sklearn#210]
I installed autosklearn using the way on the website. Unfortunately, I am now getting this error upon importing autosklearn.
```
Building wheels for collected packages: auto-sklearn
  Running setup.py bdist_wheel for auto-sklearn ... done
  Stored in directory: /home/ethan/.cache/pip/wheels/31/fd/f5/992e4b2fb6dd309c4c65419876ef73d28d52ce07f80e25f9ee
Successfully built auto-sklearn
Installing collected packages: auto-sklearn
Successfully installed auto-sklearn-0.1.1
ethan@DESKTOP-371KK9J:~/machine-learning-work$ python
Python 2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:42:40)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import autosklearn.classification
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ethan/anaconda2/lib/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/home/ethan/anaconda2/lib/python2.7/site-packages/autosklearn/estimators.py", line 7, in <module>
    import autosklearn.automl
  File "/home/ethan/anaconda2/lib/python2.7/site-packages/autosklearn/automl.py", line 27, in <module>
    from autosklearn.smbo import AutoMLSMBO
  File "/home/ethan/anaconda2/lib/python2.7/site-packages/autosklearn/smbo.py", line 13, in <module>
    from smac.facade.smac_facade import SMAC
  File "/home/ethan/anaconda2/lib/python2.7/site-packages/smac/facade/smac_facade.py", line 43
    scenario: Scenario,
            ^
SyntaxError: invalid syntax
```

- Platform: Bash on Ubuntu on Windows
- Installation: Python 2.7 from Conda

Thank you!

**Comment by mfeurer** [comment]
We do only support python3.4 and python3.5. Please use Conda with one of these versions.
