### ISSUE TITLE
Error "flags not found" when input is sparse matrix

### ISSUE THREAD

**Issue by eromoe** [automl/auto-sklearn#213]
Hi!

I am doing a text-classification, the example code works with `sklearn.datasets.load_digits()`, but error on my dataset. 
My input `X` is transformed by TfidfVector, code as below, I would update the pickled dataset if you need.

`X` details:
```
<9516x28934 sparse matrix of type '<class 'numpy.float64'>'
	with 946932 stored elements in Compressed Sparse Row format>
```

Code:
```
import autosklearn.classification
import sklearn.cross_validation
import sklearn.datasets
import sklearn.metrics

from utils import load
from config import DATA_DIR

X = load('3np_train_X', DATA_DIR)
y = load('3np_train_y', DATA_DIR)


X_train, X_test, y_train, y_test = \
        sklearn.cross_validation.train_test_split(X, y, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))
```

Error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-205a95cff171> in <module>()
      7 X_train, X_test, y_train, y_test =         sklearn.cross_validation.train_test_split(X, y, random_state=1)
      8 automl = autosklearn.classification.AutoSklearnClassifier()
----> 9 automl.fit(X_train, y_train)
     10 y_hat = automl.predict(X_test)
     11 print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/estimators.py in fit(self, X, y, metric, feat_type, dataset_name)
    328 
    329         """
--> 330         return super(AutoSklearnClassifier, self).fit(X, y, metric, feat_type, dataset_name)
    331 
    332     def predict(self, X):

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/estimators.py in fit(self, *args, **kwargs)
    271     def fit(self, *args, **kwargs):
    272         self._automl = self.build_automl()
--> 273         super(AutoSklearnEstimator, self).fit(*args, **kwargs)
    274 
    275     def fit_ensemble(self, y, task=None, metric=None, precision='32',

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/estimators.py in fit(self, *args, **kwargs)
     19 
     20     def fit(self, *args, **kwargs):
---> 21         self._automl.fit(*args, **kwargs)
     22 
     23     def refit(self, X, y):

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/estimators.py in fit(self, X, y, metric, feat_type, dataset_name)
    455                 task = MULTICLASS_CLASSIFICATION
    456 
--> 457         return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
    458 
    459     def fit_ensemble(self, y, task=None, metric=None, precision='32',

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/automl.py in fit(self, X, y, task, metric, feat_type, dataset_name)
    150 
    151         if dataset_name is None:
--> 152             dataset_name = hash_numpy_array(X)
    153 
    154         self._backend.save_start_time(self._seed)

/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/util/hash.py in hash_numpy_array(X)
      5     m = hashlib.md5()
      6 
----> 7     if X.flags['C_CONTIGUOUS']:
      8         m.update(X.data)
      9     else:

/root/.virtualenvs/py35/lib/python3.5/site-packages/scipy/sparse/base.py in __getattr__(self, attr)
    557             return self.getnnz()
    558         else:
--> 559             raise AttributeError(attr + " not found")
    560 
    561     def transpose(self, axes=None, copy=False):

AttributeError: flags not found

```

**Comment by eromoe** [comment]
I tried use `X.A` (normal matrix)  for trainning, but get
```
[ERROR] [2016-12-20 14:28:53,821:AutoML(1):4fbd61d59ed179fecf739a7d56071ac6] Error creating dummy predictions:Memout 

Process pynisher function call:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/smbo.py", line 283, in _calculate_metafeatures
    logger=self.logger)
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/smbo.py", line 107, in _calculate_metafeatures
    dont_calculate=EXCLUDE_META_FEATURES, )
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 921, in calculate_all_metafeatures_with_labels
    dont_calculate=dont_calculate)
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 1020, in calculate_all_metafeatures
    value = metafeatures[name](X_, y_, categorical_)
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/metalearning/metafeatures/metafeature.py", line 33, in __call__
    value = self._calculate(X, y, categorical)
  File "/root/.virtualenvs/py35/lib/python3.5/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 233, in _calculate
    return float(helper_functions.get_value("MissingValues").sum())
AttributeError: 'NoneType' object has no attribute 'sum'
```

**Comment by mfeurer** [comment]
Thanks for reporting this. Did you try a np.Matrix in the second case? If yes, could you transform that into a np.ndarray? Regarding the first error, this is clearly a bug. You should be able to circumvent this bug by passing a dataset name to the `fit()` method.

**Comment by eromoe** [comment]
`X.A` 's type is `numpy.ndarray`,   `automl.fit(X.A, y, dataset_name='yq_np')` still get `AttributeError: 'NoneType' object has no attribute 'sum'`

**Comment by eromoe** [comment]
`X.A` 's type is `numpy.ndarray`,   `automl.fit(X.A, y, dataset_name='yq_np')` still get `AttributeError: 'NoneType' object has no attribute 'sum'`

**Comment by mfeurer** [comment]
My first guess is that there is something wrong with the input data. Could you please check the dtype and dimensions of `X.A` and `y` and post them here? If these are all `float64` and `> 0`, the it would be great if you could provide a minimal working example with synthetic data, or your data uploaded as you proposed.

**Comment by eromoe** [comment]
All feature are float64 and most of them are `0.` , as you know that 's why  tfidfvect transform input to sparse matrix .

X:
https://drive.google.com/open?id=0B589sSn5E1oqTmxDTE1NMzdEUzg
y:
https://drive.google.com/open?id=0B589sSn5E1oqQVlPQmpLVFlIZHc

PS: though automl show that error, it does complete training and give an usable model.

**Comment by mfeurer** [comment]
Thanks. I'll have a look at it (although I'm afraid it will only happen next year).

**Comment by mfeurer** [comment]
I just committed e87e812 to the development branch which fixes this issue. I hope it is still helpful for you.
