### ISSUE TITLE
Make BackendContext a ContextManager

### ISSUE THREAD

**Issue by mfeurer** [automl/auto-sklearn#221]
Currently, the implementation of the [BackendContext](https://github.com/automl/auto-sklearn/blob/master/autosklearn/util/backend.py#L31) is not a context manager. It relies on the delete function called properly on interpreter shutdown. Recent [travis-ci failures](https://travis-ci.org/automl/auto-sklearn/jobs/188557896) show that this isn't the case:

```
Exception ignored in: <bound method BackendContext.__del__ of <autosklearn.util.backend.BackendContext object at 0x7f7cd3e63fd0>>
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/auto_sklearn-0.1.2-py3.4-linux-x86_64.egg/autosklearn/util/backend.py", line 75, in __del__
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/auto_sklearn-0.1.2-py3.4-linux-x86_64.egg/autosklearn/util/backend.py", line 84, in delete_directories
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/site-packages/auto_sklearn-0.1.2-py3.4-linux-x86_64.egg/autosklearn/util/logging_.py", line 67, in warning
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1291, in warning
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1414, in _log
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1424, in handle
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1486, in callHandlers
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 853, in handle
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1045, in emit
  File "/home/travis/miniconda/envs/testenv/lib/python3.4/logging/__init__.py", line 1035, in _open
NameError: name 'open' is not defined
```

**Comment by eddiebergman** [comment]
Using a context managed backend means we can only have access to the backend within a small scope. Users wishing to extend this scope would need to then create the backends themselves.

Handled with automl_common whenever we can get that in anywho. I think the problem is more that auto-sklearn can just reuse a backend to achieve its previous state.
