### ISSUE TITLE
sklearn.utils.validation.NotFittedError: This FastICA instance is not fitted yet

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#248]
```
Process pynisher function call:
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/ubuntu/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 284, in eval_holdout
    evaluator.fit_predict_and_loss(iterative=iterative)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 77, in fit_predict_and_loss
    i, train_indices=train_split, test_indices=test_split)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/train_evaluator.py", line 211, in _partial_fit_and_predict
    self.Y_train[train_indices])
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 340, in _fit_and_suppress_warnings
    model.fit(X, y)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 88, in fit
    X, fit_params = self.pre_transform(X, y, fit_params=fit_params)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/classification.py", line 102, in pre_transform
    X, y, fit_params=fit_params)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/base.py", line 98, in pre_transform
    X, fit_params = self._pre_transform(X, y, **fit_params)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/sklearn/pipeline.py", line 148, in _pre_transform
    .transform(Xt)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 43, in transform
    return self.preprocessor.transform(X)
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/sklearn/decomposition/fastica_.py", line 542, in transform
    check_is_fitted(self, 'mixing_')
  File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py", line 678, in check_is_fitted
    raise NotFittedError(msg % {'name': type(estimator).__name__})
sklearn.utils.validation.NotFittedError: This FastICA instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.
```

**Comment by mfeurer** [comment]
Does this terminate the auto-sklearn optimization procedure?

**Comment by Motorrat** [comment]
No, it doesn't terminate the optimization procedure.

**Comment by mfeurer** [comment]
Closing this issue as this error message/warning should no longer appear with auto-sklearn 0.2.0.
