### ISSUE TITLE
many warnings executing website example on pypi version

### ISSUE THREAD

**Issue by amueller** [automl/auto-sklearn#249]
I installed auto-sklearn from pypi and ran the digits example from the website and I get the following error.
The code seems to run but the error message take over all output :-/

```python
Process pynisher function call:
Traceback (most recent call last):
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 284, in eval_holdout
    evaluator.fit_predict_and_loss(iterative=iterative)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 77, in fit_predict_and_loss
    i, train_indices=train_split, test_indices=test_split)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 211, in _partial_fit_and_predict
    self.Y_train[train_indices])
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/evaluation/abstract_evaluator.py", line 340, in _fit_and_suppress_warnings
    model.fit(X, y)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 88, in fit
    X, fit_params = self.pre_transform(X, y, fit_params=fit_params)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 102, in pre_transform
    X, y, fit_params=fit_params)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 98, in pre_transform
    X, fit_params = self._pre_transform(X, y, **fit_params)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/sklearn/pipeline.py", line 147, in _pre_transform
    Xt = transform.fit(Xt, y, **fit_params_steps[name]) \
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/pipeline/components/base.py", line 379, in fit
    return self.choice.fit(X, y, **kwargs)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/autosklearn/pipeline/components/feature_preprocessing/fast_ica.py", line 33, in fit
    self.preprocessor.fit(X)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/sklearn/decomposition/fastica_.py", line 523, in fit
    self._fit(X, compute_sources=False)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/sklearn/decomposition/fastica_.py", line 479, in _fit
    compute_sources=compute_sources, return_n_iter=True)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/sklearn/decomposition/fastica_.py", line 335, in fastica
    W, n_iter = _ica_par(X1, **kwargs)
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/site-packages/sklearn/decomposition/fastica_.py", line 116, in _ica_par
    warnings.warn('FastICA did not converge. Consider increasing '
  File "/home/andy/anaconda3/envs/autosklearn/lib/python3.6/warnings.py", line 99, in _showwarnmsg
    msg.file, msg.line)
TypeError: send_warnings_to_log() takes from 4 to 5 positional arguments but 6 were given
```

**Comment by amueller** [comment]
Should I try master or dev instead?

**Comment by mlindauer** [comment]
mfeurer is on vacation for the next 2 weeks. so, we won't be able to fix this problem at the moment.

> Should I try master or dev instead?

Given our workflow, I would expect that the version on pypi and the master branch are identical.

**Comment by amueller** [comment]
![image](https://cloud.githubusercontent.com/assets/449558/23614827/4db770d4-0252-11e7-8bb3-19b08037e06c.png)

Lucky him :)

**Comment by jgwerner** [comment]
@mlindauer I ran into this same error. Installed using virtualenv with Python 3.6 and followed [these installation instructions](http://automl.github.io/auto-sklearn/stable/#installation). Also used the example run provided [here](http://automl.github.io/auto-sklearn/stable/#example).

**Comment by mlindauer** [comment]
@jgwerner Thanks for reporting it. Our main developer will be back from his vacations on 28th of March. I will ask him to answer here as soon as possible.

**Comment by mfeurer** [comment]
The issue here is that the code isn't yet updated for python3.6. python3.5 and python3.4 should not show this behaviour.

**Comment by amueller** [comment]
There's breaking changes in 3.6?!

**Comment by mfeurer** [comment]
According to the doc there aren't. I think I used a wrong signature for the callback here, which makes it fail now.

**Comment by mfeurer** [comment]
Thank you very much for reporting this @amueller. Will be fixed in the next bugfix release.

**Comment by amueller** [comment]
sweet, thanks :)
