### ISSUE TITLE
Cannot import autosklearn.classification

### ISSUE THREAD

**Issue by parunach** [automl/auto-sklearn#252]
It fails with an error

`import autosklearn.classification`
Traceback (most recent call last):
File "/usr/lib64/python2.7/site-packages/autosklearn/classification.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnClassifier
  File "/usr/lib64/python2.7/site-packages/autosklearn/estimators.py", line 7, in <module>
    import autosklearn.automl
  File "/usr/lib64/python2.7/site-packages/autosklearn/automl.py", line 8, in <module>
    import unittest.mock
ImportError: No module named mock

This is in a CentOS 7.2 machine. The auto-sklearn was updated today.

**Comment by mlindauer** [comment]
please note that autosklearn is not compatible with Python 2.7

**Comment by parunach** [comment]
I did not know that. Thanks.
