### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'toarray'

### ISSUE THREAD

**Issue by sovaa** [automl/auto-sklearn#254]
auto-sklearn 0.1.3
python 3.4.5
pandas 0.19.2
centos 7

```
max_size = 10000

X = pd.read_csv('data_train_x.csv')
y = pd.read_csv('data_train_y.csv', header=None)
X = X[X.columns[1:]][:max_size]
y = y[y.columns[1:]][:max_size]

validation_split = int(len(X) / 2.0)

X_valid = X[:validation_split].copy()
X_train = X[validation_split+1:].copy()
y_train = y[validation_split+1:].copy()
y_valid = y[:validation_split].copy()

import autosklearn.classification

automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
y_hat = automl.predict(X_valid)
```

```
Traceback (most recent call last):
  File "search_automl.py", line 134, in <module>
    y_hat = automl.predict(X_valid)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/estimators.py", line 373, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/estimators.py", line 66, in predict
    return self._automl.predict(X)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/estimators.py", line 532, in predict
    predicted_probabilities = self._automl.predict(X)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/automl.py", line 505, in predict
    prediction = model.predict_proba(X_)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/pipeline/classification.py", line 125, in predict_proba
    Xt = transform.transform(Xt)
  File "/home/foo/test/env3/lib/python3.4/site-packages/autosklearn/pipeline/components/data_preprocessing/one_hot_encoding/one_hot_encoding.py", line 55, in transform
    return X.toarray()
  File "/home/foo/test/env3/lib/python3.4/site-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'toarray'
```

The method in `one_hot_encoding.py`:

```
def transform(self, X):
    import scipy.sparse

    is_sparse = scipy.sparse.issparse(X)
    if self.preprocessor is None:
        raise NotImplementedError()
    X = self.preprocessor.transform(X)
    if is_sparse:
        return X
    elif isinstance(X, np.ndarray):
        return X
    else:
        return X.toarray()
```

Maybe auto-sklearn doesn't work well with pandas?

**Comment by mlindauer** [comment]
yes, please provide X and y as numpy arrays. For example, I would expect that `DataFrame.as_matrix()` should work well.

**Comment by sovaa** [comment]
Yep, that works. Thanks for the quick reply.
