### ISSUE TITLE
automl.prediction fails after automl.refit call

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#263]
I guess this is worth opening a separate issue. 
I have the same problem with the failing prediction as https://github.com/automl/auto-sklearn/issues/260 after a recent fresh installation of the full stack (fresh Ubuntu 16.04, Anaconda, auto-sklearn) 

To isolate the issue I have even put a copy of the same data in both refit and predict methods:
```
automl.refit(X.copy().values, y)
y_pred = automl.predict(X.copy().values)
```
but it fails nevertheless.

The X dataset is the Titanic dataset, I believe I can not publish it here but I can share it off-line together with the code.

The problem seems to be in the refit() because prediction goes fine if the refit() is excluded.

```
Traceback (most recent call last):
  File "zeroconf.py", line 291, in <module>
    y_pred = c.predict(X.copy().values)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 373, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 66, in predict
    return self._automl.predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 532, in predict
    predicted_probabilities = self._automl.predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 505, in predict
    prediction = model.predict_proba(X_)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 127, in predict_proba
    return self.steps[-1][-1].predict_proba(Xt)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/__init__.py", line 126, in predict_proba
    return self.choice.predict_proba(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/random_forest.py", line 107, in predict_proba
    probas = self.estimator.predict_proba(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 537, in predict_proba
    X = self._validate_X_predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/ensemble/forest.py", line 319, in _validate_X_predict
    return self.estimators_[0]._validate_X_predict(X, check_input=True)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/tree/tree.py", line 376, in _validate_X_predict
    % (self.n_features_, n_features))
ValueError: Number of features of the model must  match the input. Model n_features is 15 and  input n_features is 14
```
it seems to be the first classificator that fails, because there are different error messages when re-running the same code
```

Traceback (most recent call last):
  File "zeroconf.py", line 291, in <module>
    y_pred = c.predict(X.copy().values)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 373, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 66, in predict
    return self._automl.predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 532, in predict
    predicted_probabilities = self._automl.predict(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 505, in predict
    prediction = model.predict_proba(X_)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 127, in predict_proba
    return self.steps[-1][-1].predict_proba(Xt)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/__init__.py", line 126, in predict_proba
    return self.choice.predict_proba(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/autosklearn/pipeline/components/classification/bernoulli_nb.py", line 86, in predict_proba
    return self.estimator.predict_proba(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py", line 103, in predict_proba
    return np.exp(self.predict_log_proba(X))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py", line 83, in predict_log_proba
    jll = self._joint_log_likelihood(X)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/sklearn/naive_bayes.py", line 783, in _joint_log_likelihood
    % (n_features, n_features_X))
ValueError: Expected input with 10 features, got 8 instead
```

**Comment by mfeurer** [comment]
Solution to this is posted in the original issue #260.
