### ISSUE TITLE
Using n_jobs for predict throws an exception

### ISSUE THREAD

**Issue by felixvelariusbos** [automl/auto-sklearn#307]
Was using the Auto-sklearn with no issues, so I decided to try using the n_jobs parameter for predictions to see if I could start speeding up the process a little. With this line of code:
```
automl = cl.AutoSklearnClassifier (
                                    per_run_time_limit      = 3,
                                    time_left_for_this_task = 360
                                    )
automl.fit(xTrain, yTrain)
y_hat = automl.predict(xTest, n_jobs=3)
```
I got:
```
Exception ignored in: <bound method BackendContext.__del__ of <autosklearn.util.backend.BackendContext object at 0x7fb9a5e12390>>
Traceback (most recent call last):
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/site-packages/autosklearn/util/backend.py", line 74, in __del__
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/site-packages/autosklearn/util/backend.py", line 83, in delete_directories
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/site-packages/autosklearn/util/logging_.py", line 67, in warning
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1318, in warning
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1442, in _log
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1452, in handle
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 863, in handle
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1069, in emit
  File "/home/jdoe/anaconda2/envs/python3/lib/python3.6/logging/__init__.py", line 1059, in _open
NameError: name 'open' is not defined
```
Interestingly, my program did get to completion; after that code snippet I print out the accuracy and the AUC. That prints out fine, and then right after that throws the ignored exception

I have a quad core processor, and I'm running this on a Red Hat.

As a side note, this is pretty neat software y'all have made. Thanks for working on it!

**Comment by mfeurer** [comment]
Thanks a lot for reporting this. This exception is not harmful as explained in #221. As it is a duplicate, I'm closing this.
