### ISSUE TITLE
Issues when extending with wrapper for LightGBM

### ISSUE THREAD

**Issue by carterkoehler** [automl/auto-sklearn#324]
I am attempting to write a classification and a regression component that serve as wrappers for the LightGBM library to serve as an alternate gradient boosting framework. So far, I have resolved several of the issues I have been having, but it still crashes consistently when I limit the search space to just this one component. For the purposes of this issue, I will focus entirely on the classification component, as the problem with the regression component is effectively indistinguishable.

As it sits currently, the component looks like this:
```
import numpy as np

from ConfigSpace.configuration_space import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter, \
    UniformIntegerHyperparameter, UnParametrizedHyperparameter, Constant, \
    CategoricalHyperparameter

from autosklearn.pipeline.components.base import \
    AutoSklearnClassificationAlgorithm

from autosklearn.pipeline.constants import *


class LGBMachineClassifier(AutoSklearnClassificationAlgorithm):
    def __init__(self, learning_rate, feature_fraction,
                 num_leaves, min_data_in_leaf, max_depth,
                 max_bin, min_gain_to_split,min_sum_hessian_in_leaf,
                 bagging_fraction, lambda_l1, lambda_l2,
                 min_data_in_bin, random_state=None, num_threads=1):

        
        self.learning_rate = learning_rate
        self.num_leaves = num_leaves
        self.max_bin = max_bin
        self.feature_fraction = feature_fraction
        self.min_data_in_leaf = min_data_in_leaf
        self.min_sum_hessian_in_leaf = min_sum_hessian_in_leaf
        self.max_depth = max_depth
        self.min_gain_to_split = min_gain_to_split
        if random_state is None:
            self.random_state = np.random.randint(1, 10000, size=1)[0]
        else:
            self.random_state = random_state.randint(1, 10000, size=1)[0]
        self.num_threads = num_threads
        self.bagging_fraction = bagging_fraction
        self.lambda_l1 = lambda_l1
        self.lambda_l2 = lambda_l2
        self.min_data_in_bin = min_data_in_bin
        
        
    def fit(self, X, y):
        import LightGBM as lgbm

        self.learning_rate = float(self.learning_rate)
        self.num_leaves = int(self.num_leaves)
        self.max_bin = int(self.max_bin)
        self.feature_fraction = float(self.feature_fraction)
        self.min_data_in_leaf = int(self.min_data_in_leaf)
        self.min_sum_hessian_in_leaf = float(self.min_sum_hessian_in_leaf)
        self.max_depth = int(self.max_depth)
        self.min_gain_to_split = float(self.min_gain_to_split)
        self.num_threads = int(self.num_threads)
        self.bagging_fraction = float(self.bagging_fraction)
        self.lambda_l1 = float(self.lambda_l1)
        self.lambda_l2 = float(self.lambda_l2)
        self.min_data_in_bin = int(self.min_data_in_bin)
        

        self.estimator = lgbm.LGBMClassifier(
            learning_rate = self.learning_rate,
            num_leaves = self.num_leaves,
            max_bin = self.max_bin,
            feature_fraction = self.feature_fraction,
            min_data_in_leaf = self.min_data_in_leaf,
            min_sum_hessian_in_leaf = self.min_sum_hessian_in_leaf,
            max_depth = self.max_depth,
            min_gain_to_split = self.min_gain_to_split,
            random_state = self.random_state,
            num_threads = self.num_threads,
            bagging_fraction = self.bagging_fraction,
            lambda_l1 = self.lambda_l1,
            lambda_l2 = self.lambda_l2,
            min_data_in_bin = self.min_data_in_bin
        )

        self.estimator.fit(X,y)
        return self
    
    def predict(self, X):
        if self.estimator is None:
            raise NotImplementedError
        return self.estimator.predict(self, X)

    def predict_proba(self, X):
        if self.estimator is None:
            raise NotImplementedError
        probas = self.estimator.predict_proba(X)
        return probas

    @staticmethod
    def get_properties(dataset_properties=None):
        return {'shortname': 'LGBM',
                'name': 'Light Gradient Boosting Machine Classifier',
                'handles_regression': False,
                'handles_classification': True,
                'handles_multiclass': True,
                'handles_multilabel': False,
                'is_deterministic': True,
                'input':(DENSE, SPARSE, UNSIGNED_DATA),
                'output': (PREDICTIONS,)}

    @staticmethod
    def get_hyperparameter_search_space(dataset_properties=None):
        cs = ConfigurationSpace()

        #Parametrized
        learning_rate = UniformFloatHyperparameter(
            name='learning_rate', lower=0.01, upper=1, default=0.1)
        feature_fraction = UniformFloatHyperparameter(
            name='feature_fraction', lower=0.5, upper=1.0, default=0.9)
        num_leaves = UniformIntegerHyperparameter(
            name='num_leaves', lower=5, upper=500, default=31)
        min_data_in_leaf = UniformIntegerHyperparameter(
            name='min_data_in_leaf', lower=1, upper=30, default=20)
        lambda_l1 = UniformFloatHyperparameter(
            name='lambda_l1', lower=0.0, upper=10.0, default=0.0)
        lambda_l2 = UniformFloatHyperparameter(
            name='lambda_l2', lower=0.0, upper=10.0, default=0.0)
        max_bin = UniformIntegerHyperparameter(
            name='max_bin', lower=50, upper=500, default=255)
        

        #UnParametrized
        bagging_fraction = UnParametrizedHyperparameter(
            name='bagging_fraction', value=1.0)
        bagging_freq = UnParametrizedHyperparameter(
            name='bagging_freq', value=5)
        max_depth = UnParametrizedHyperparameter(
            name='max_depth', value=-1)
        min_data_in_bin = UnParametrizedHyperparameter(
            name='min_data_in_bin', value=5)
        min_gain_to_split = UnParametrizedHyperparameter(
            name='min_gain_to_split', value=0)
        min_sum_hessian_in_leaf = UnParametrizedHyperparameter(
            name='min_sum_hessian_in_leaf', value=1e-3)
        

        cs.add_hyperparameters([learning_rate, feature_fraction, bagging_fraction,
                                num_leaves, min_data_in_leaf, lambda_l1,
                                lambda_l2, min_data_in_bin, max_depth, max_bin,
                                min_sum_hessian_in_leaf, min_gain_to_split]) 
        
        return cs
```

and the test case I have been using most often is as follows:

```
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics

import autosklearn.classification

def main():
    X, y = sklearn.datasets.load_digits(return_X_y=True)
    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)

    automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=120, per_run_time_limit=30,
        tmp_folder='/tmp/autosklearn_lgbm_class_test',
        output_folder='/tmp/autosklearn_lgbm_class_out',
        delete_tmp_folder_after_terminate=False,
        include_estimators=['lightgb_machine'],
    )

  
    automl.fit(X_train.copy(), y_train.copy(), dataset_name='digits')
  
    print(automl.show_models())
    predictions = automl.predict(X_test)
    print("Accuracy score", sklearn.metrics.accuracy_score(y_test, predictions))

if __name__=="__main__":
    main()
```
This results the following error:
```
Running TA selection

Configuration is Configuration:
  balancing:strategy, Value: 'none'
  classifier:__choice__, Value: 'lightgb_machine'
  classifier:lightgb_machine:bagging_fraction, Constant: 1.0
  classifier:lightgb_machine:feature_fraction, Value: 0.9
  classifier:lightgb_machine:lambda_l1, Value: 0.0
  classifier:lightgb_machine:lambda_l2, Value: 0.0
  classifier:lightgb_machine:learning_rate, Value: 0.1
  classifier:lightgb_machine:max_bin, Value: 255
  classifier:lightgb_machine:max_depth, Constant: -1
  classifier:lightgb_machine:min_data_in_bin, Constant: 5
  classifier:lightgb_machine:min_data_in_leaf, Value: 20
  classifier:lightgb_machine:min_gain_to_split, Constant: 0
  classifier:lightgb_machine:min_sum_hessian_in_leaf, Constant: 0.001
  classifier:lightgb_machine:num_leaves, Value: 31
  imputation:strategy, Value: 'mean'
  one_hot_encoding:minimum_fraction, Value: 0.01
  one_hot_encoding:use_minimum_fraction, Value: 'True'
  preprocessor:__choice__, Value: 'no_preprocessing'
  rescaling:__choice__, Value: 'standardize'


Ran with exit Status StatusType.CRASHED

Traceback (most recent call last):
  File "../test/test_lgbm_class.py", line 28, in <module>
    main()
  File "../test/test_lgbm_class.py", line 21, in main
    automl.fit(X_train.copy(), y_train.copy(), dataset_name='digits')
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 405, in fit
    dataset_name=dataset_name)
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 304, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/estimators.py", line 546, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/automl.py", line 449, in _fit
    _proc_smac.run_smbo()
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/smbo.py", line 661, in run_smbo
    smac.solver.incumbent = smac.solver.initial_design.run()
  File "/usr/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/initial_design/single_config_initial_design.py", line 80, in run
  File "/usr/lib64/python3.5/site-packages/auto_sklearn-0.2.0-py3.5-linux-x86_64.egg/autosklearn/evaluation/__init__.py", line 144, in start
    capped=capped)
  File "/usr/lib/python3.5/site-packages/smac-0.5.0-py3.5.egg/smac/tae/execute_ta_run.py", line 156, in start
smac.tae.execute_ta_run.FirstRunCrashedException: First run crashed, abort. (To prevent this, toggle the 'abort_on_first_run_crash'-option!)
```
where everything above the Traceback statement consists of print statements that I added manually to my installation of SMAC to help with debugging.

I have tried a wide variety of possible solutions, but I don't know what continues to cause this issue. Any help or advice is welcome.

As an addendum, I have a related, though entirely different question. What exactly does the ThirdPartyComponents add_component function do? The [documentation on extending auto-sklearn](https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/__init__.py) vaguely alludes to it "adding" the new component, but a fresh install of auto-sklearn with my component merely placed in the classification directory and one in which I have subsequently run the function are identical. Furthermore, if I am interpreting the contents of the find_components function and its call from the [init file in the classification directory](https://github.com/automl/auto-sklearn/blob/master/autosklearn/pipeline/components/classification/__init__.py) , the components should just be found by way of their files in the classification directory. Please let me know if there is something I am missing.

**Comment by carterkoehler** [comment]
As it turns out, the problem was a small issue with formatting and a couple of arguments that were incorrect. I'll go ahead and close this, though I would still be interested to see the answer to my second question.

**Comment by mfeurer** [comment]
If you put a component into the classification directory, it will be automatically be discovered and made available to Auto-sklearn. If you want to have your component reside in a different project you can add it via `add_component`. This allows for the separation of repositories of the base Auto-sklearn library and additional libraries. I hope this answer clarifies the current status. If you have further questions, please do not hesitate to ask.

**Comment by carterkoehler** [comment]
Thank you, I see. Then, is there some way to avoid the necessity of running ```add_component``` each time I want to include my component? Also, how does auto-sklearn's metalearning framework handles cases in which a component is not associated with any datasets, as described in _Efficient and Robust Automated Machine Learning_? I can update metafeatures locally, but for distribution that would not be feasible, and I would like to know how that is treated.

**Comment by mfeurer** [comment]
No, you either have to copy the file into the installation directory, or you need to call `add_component` at the beginning of your script.

In case there is no meta-data available for a component, auto-sklearn will ignore it during the meta-learning initialization procedure and only use it during the Bayesian optimization phase thereafter. Unfortunately, we do not have a procedure on how to integrate more meta-data. If you do have any idea here, please let us know.
