### ISSUE TITLE
regression forest error

### ISSUE THREAD

**Issue by arita37** [automl/auto-sklearn#344]
Hello,
Thanks for you work.

When training the example, I got this message :  
`
AttributeError: You cannot add attributes to <pyrfr.regression.forest_opts; proxy of <Swig Object of type           'rfr::forests::forest_options< num_t,response_t,index_t > *' at 0x7f9e02a87f60> >
`
```
import autosklearn.classification ; import sklearn.cross_validation
import sklearn.datasets           ; import sklearn.metrics
digits = sklearn.datasets.load_digits()
X = digits.data  ;     y = digits.target
X_train, X_test, y_train, y_test = sklearn.cross_validation.train_test_split(X,y,random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier()
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))


```
```
>>> automl.fit(X_train, y_train)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/estimators.py", line           405, in fit
    dataset_name=dataset_name)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/estimators.py", line           304, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/estimators.py", line           23, in fit
    self._automl.fit(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/estimators.py", line           546, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/automl.py", line 195,           in fit
    return self._fit(loaded_data_manager, metric)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/automl.py", line 449,           in _fit
    _proc_smac.run_smbo()
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/autosklearn/smbo.py", line 587, i          n run_smbo
    seed=1, num_trees=10)
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/smac/epm/rf_with_instances.py", l          ine 77, in __init__
    self.rf_opts.seed = seed
  File "/home/ubuntu/anaconda3/envs/sandbox/lib/python3.6/site-packages/pyrfr-0.5.2-py3.6-linux-x86_64.eg          g/pyrfr/regression.py", line 95, in set_attr
    raise AttributeError("You cannot add attributes to %s" % self)
AttributeError: You cannot add attributes to <pyrfr.regression.forest_opts; proxy of <Swig Object of type           'rfr::forests::forest_options< num_t,response_t,index_t > *' at 0x7f9e02a87f60> >
>>> y_hat = automl.predict(X_test)
>>> print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))
Accuracy score 0.117777777778
```

Any idea how it can be fixed ?

**Comment by mfeurer** [comment]
The solution is to use `pyrfr==0.4.0` instead of `pyrfr==0.5.2`. I will make a new bugfix release soon which will solve this issue.

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.
