### ISSUE TITLE
Leave one out cross-validation (LOOCV)

### ISSUE THREAD

**Issue by mattvan83** [automl/auto-sklearn#350]
Dear auto-sklearn experts,

Isn't it possible to use LOOCV when calling "autosklearn.classification.AutoSklearnClassifier" ?

I could see that k-fold cross-validation (stratified ?) was possible through resampling_strategy='cv' and resampling_strategy_arguments={'folds': k}. But when I set k=n, where n is the size of my training set, I got error.

Thank you in advance for your help !

Best regards,
Matthieu

**Comment by mfeurer** [comment]
Could you please post the exact error? Also, I cannot come up with a good use case where you would like to have leave one out cross-validation in Auto-sklearn, so it would be good if you could briefly describe what you're trying to achieve.

**Comment by mattvan83** [comment]
Please find below the exact error:
```
[ERROR] [2017-09-06 10:42:48,896:AutoML(1):COMAJ] Error creating dummy predictions: {'traceback': 'Traceback (most recent call last):\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 28, in fit_predict_try_except_decorator\n    return ta(queue=queue, **kwargs)\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 404, in eval_cv\n    evaluator.fit_predict_and_loss()\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/train_evaluator.py", line 90, in fit_predict_and_loss\n    self.X_train, y)):\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 322, in split\n    for train, test in super(_BaseKFold, self).split(X, y, groups):\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 91, in split\n    for test_index in self._iter_test_masks(X, y, groups):\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 610, in _iter_test_masks\n    test_folds = self._make_test_folds(X, y)\n  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/sklearn/model_selection/_split.py", line 575, in _make_test_folds\n    % (self.n_splits))\nValueError: All the n_groups for individual classes are less than n_splits=81.\n', 'error': "ValueError('All the n_groups for individual classes are less than n_splits=81.',)"} 
Traceback (most recent call last):
  File "AutoML.SignClustROIs.COMAJ.py", line 46, in <module>
    main()
  File "AutoML.SignClustROIs.COMAJ.py", line 32, in main
    automl.fit(X_train.copy(), y_train.copy(), dataset_name='COMAJ')
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 405, in fit
    dataset_name=dataset_name)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 304, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/estimators.py", line 546, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/automl.py", line 449, in _fit
    _proc_smac.run_smbo()
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/smbo.py", line 661, in run_smbo
    smac.solver.incumbent = smac.solver.initial_design.run()
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/smac/initial_design/single_config_initial_design.py", line 80, in run
    instance_specific=self.scenario.instance_specific.get(rand_inst, "0"))
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 144, in start
    capped=capped)
  File "/home/matthieu/programs/anaconda3/lib/python3.6/site-packages/smac/tae/execute_ta_run.py", line 150, in start
    raise FirstRunCrashedException("First run crashed, abort. (To "
smac.tae.execute_ta_run.FirstRunCrashedException: First run crashed, abort. (To prevent this, toggle the 'abort_on_first_run_crash'-option!)
```

I have very little sample size (=82 subjects) with four classes (class1 = 47 subjects; class2 = 9 subjects; class3 = 13 subjects; class4 = 13 subjects). So I could understand that in this case it is better to do LOO-CV than k-fold CV (I tried k=5; k=10 and k=30 with success but k=81 with error).

What do you think about this ?

**Comment by mfeurer** [comment]
Hm, I really don't know why this error comes up, but it will take some time until I can look into how to get rid of this error (end of September). Anyway, I never tried Auto-sklearn on datasets with less than 500 datapoints, and I'm really not sure if it will produce any meaningful results which are not totally overfitted. For now, would it work if you use k=30?

**Comment by mattvan83** [comment]
Yes it works when using k=30, but in my case of small samples is it better
to use high level of cross-validation or 10 or 30-fold CV sufficient ?

Moreover, is it possible to use stratified k-fold CV ?

Le 9 sept. 2017 7:58 AM, "Matthias Feurer" <notifications@github.com> a
écrit :

**Comment by mfeurer** [comment]
If you use k-fold CV, Auto-sklearn will automatically use stratified CV.

**Comment by mfeurer** [comment]
I just merged a PR which adds the possibility to provide custom split generators to the development branch. Please reopen if there are any further issue related to custom CV splitters.
