### ISSUE TITLE
Error installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by SexyApe** [automl/auto-sklearn#355]
https://github.com/automl/auto-sklearn/issues/308
My mistake is also :
python3 -c "from pyrfr import regression"

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyrfr._regression'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 17, in <module>
    _regression = swig_import_helper()
  File "/opt/anaconda3/lib/python3.6/site-packages/pyrfr/regression.py", line 16, in swig_import_helper
    return importlib.import_module('_regression')
  File "/opt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /opt/anaconda3/lib/python3.6/site-packages/_regression.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE

I have tried to reinstall the uninstall, but it does not work

**Comment by engelen** [comment]
This might be a problem with your version of `pyrfr`. I've been able to successfully install `auto-sklearn` after some trial and error on an Ubuntu machine, and the following installation procedure has worked for me. Could you try this procedure, and see whether it yields the same results?

1. Create a Conda environment with its own `pip` (important: if you install `pip` within the activated environment, you need to deactivate and activate it again for it to become active):
```
conda create -n test-auto-sklearn pip
```

2. Activate the environment
```
source activate test-auto-sklearn
```

3. Install `gcc` and `swig`
```
conda install gcc swig
```

4. Install `auto-sklearn`
```
pip install auto-sklearn
```

This should do it! Do note that, contrary to the instructions in the documentation, I did not need to install the requirements manually before running `pip install auto-sklearn`.

**Comment by Motorrat** [comment]
check what swig version do you have. swig >=3.0 is required

**Comment by mfeurer** [comment]
Please excuse the slow response. We have updated the auto-sklearn on pypi to work with the latest version of the pyrfr package which should solve the current installation issues. If you still encouter this issue with the latest version please post how you installed auto-sklearn, providing information on:

* whichever applies:
    * plain linux + name + version 
    * virtual environment 
    * AnaConda + version
* compiler and swig version
* python version

and the error log of the installation. Note however that we are currently experiencing some problems with the latest AnaConda version, while AnaConda 4.3.21 works.

**Comment by ajoeajoe** [comment]
I also have tried to reinstall the uninstall, but it does also not work, info are:

Mac OS
pyrfr 0.7.4
conda 4.6.14
Python 3.6.8
swig 4.0.0
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

I have installed autosklearn successfully,  

 run python -c "from pyrfr import regression" and errors found as following:

Traceback (most recent call last):
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/regression.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/_regression.cpython-36m-darwin.so, 2): Symbol not found: __ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev
  Referenced from: /Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/_regression.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/_regression.cpython-36m-darwin.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/regression.py", line 17, in <module>
    _regression = swig_import_helper()
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/site-packages/pyrfr/regression.py", line 16, in swig_import_helper
    return importlib.import_module('_regression')
  File "/Users/joe/anaconda3/envs/openml/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_regression'

**Comment by mfeurer** [comment]
@ajoeajoe are you trying to install Auto-sklearn on Ubuntu 16.04? It looks like you try to install it on a MAC.
