### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'default'

### ISSUE THREAD

**Issue by wanghia** [automl/auto-sklearn#384]
I got an error, how can I solve this problem?

Traceback (most recent call last):
  File "train_model_miaoche_kddr.py", line 75, in <module>
    module_tt(Test_data,Train_data,Train_label,feat_type,name)
  File "train_model_miaoche_kddr.py", line 24, in module_tt
    cls.fit(Train_data, Train_label,metric=autosklearn.metrics.roc_auc)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 417, in fit
    dataset_name=dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 316, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 558, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 367, in _fit
    exclude_preprocessors=self._exclude_preprocessors)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 799, in _create_search_space
    exclude_preprocessors=exclude_preprocessors)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/util/pipeline.py", line 51, in get_configuration_space
    return _get_classification_configuration_space(info, include, exclude)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/util/pipeline.py", line 91, in _get_classification_configuration_space
    include=include, exclude=exclude).\
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/classification.py", line 81, in __init__
    random_state, init_params)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 35, in __init__
    self.config_space = self.get_hyperparameter_search_space()
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 212, in get_hyperparameter_search_space
    dataset_properties=self.dataset_properties_)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/classification.py", line 178, in _get_hyperparameter_search_space
    exclude=exclude, include=include, pipeline=pipeline)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 311, in _get_base_search_space
    node.get_hyperparameter_search_space(dataset_properties))
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/components/data_preprocessing/one_hot_encoding/one_hot_encoding.py", line 82, in get_hyperparameter_search_space
    "use_minimum_fraction", ["True", "False"], default="True")
  File "ConfigSpace/hyperparameters.pyx", line 909, in ConfigSpace.hyperparameters.CategoricalHyperparameter.__init__

**Comment by mfeurer** [comment]
I assume you installed the package `ConfigSpace` in version 0.4.1. You need to downgrade that to a version 0.3.X.

**Comment by Aaaaaaare** [comment]
I have tried with version 0.3.3 and version 0.3.10 of ConfigSpace and I still have some errors... What version of ConfigSpace are you using? My errors are in ConfigSpace files

**Comment by mfeurer** [comment]
Could you please post your error message? The current version of auto-sklearn on pypi wants ConfigSpace==0.3.10, the development version want 0.4.2.

**Comment by cicero34** [comment]
I have the same problem.  I downgraded ConfigSpace to 0.3.10 but still get the following error messages:

/usr/lib/python3/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
/usr/lib/python3/dist-packages/scipy/sparse/coo.py:200: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.row) != 1 or np.rank(self.col) != 1:
/usr/lib/python3/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
/usr/lib/python3/dist-packages/scipy/sparse/compressed.py:130: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  if np.rank(self.data) != 1 or np.rank(self.indices) != 1 or np.rank(self.indptr) != 1:
Traceback (most recent call last):
  File "train_autosklearn.py", line 715, in <module>
    create_classifier() # nb create_classifer includes a save of classifier
  File "train_autosklearn.py", line 228, in create_classifier
    classifier.fit(Traintfidf_matrix, train_labels)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 417, in fit
    dataset_name=dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 316, in fit
    super(AutoSklearnEstimator, self).fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 23, in fit
    self._automl.fit(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/estimators.py", line 558, in fit
    return self._automl.fit(X, y, task, metric, feat_type, dataset_name)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 195, in fit
    return self._fit(loaded_data_manager, metric)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 367, in _fit
    exclude_preprocessors=self._exclude_preprocessors)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/automl.py", line 799, in _create_search_space
    exclude_preprocessors=exclude_preprocessors)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/util/pipeline.py", line 51, in get_configuration_space
    return _get_classification_configuration_space(info, include, exclude)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/util/pipeline.py", line 91, in _get_classification_configuration_space
    include=include, exclude=exclude).\
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/classification.py", line 81, in __init__
    random_state, init_params)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 35, in __init__
    self.config_space = self.get_hyperparameter_search_space()
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 212, in get_hyperparameter_search_space
    dataset_properties=self.dataset_properties_)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/classification.py", line 178, in _get_hyperparameter_search_space
    exclude=exclude, include=include, pipeline=pipeline)
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/base.py", line 311, in _get_base_search_space
    node.get_hyperparameter_search_space(dataset_properties))
  File "/usr/local/lib/python3.4/dist-packages/autosklearn/pipeline/components/data_preprocessing/one_hot_encoding/one_hot_encoding.py", line 82, in get_hyperparameter_search_space
    "use_minimum_fraction", ["True", "False"], default="True")
  File "ConfigSpace/hyperparameters.pyx", line 909, in ConfigSpace.hyperparameters.CategoricalHyperparameter.__init__
TypeError: __init__() got an unexpected keyword argument 'default'


Environment is Ubuntu 14.04.5.  I have followed the installation instructions at https://automl.github.io/auto-sklearn/stable/installation.html to get to this point.

Your assistance would be much appreciated!

**Comment by mfeurer** [comment]
From your error log I can see that there are some leftovers of ConfigSpace 0.4.X installed - there is no file `ConfigSpace/hyperparameters.pyx` in ConfigSpace 0.3.X. Please make sure to remove all files of the ConfigSpace package, then run `pip install ConfigSpace==0.3.10`.

**Comment by cicero34** [comment]
Matthias, I had already uninstalled ConfigSpace but it seems the uninstall
did leave some files behind.  For the sake of anyone else having the same
problem, I located the offending file
in /usr/local/lib/python3.4/dist-packages/ConfigSpace.  A rm -R on that
directory, followed by a fresh install of ConfigSpace 0.3.10, fixed that
problem.

Thanks for your help.

**Comment by mfeurer** [comment]
Thank you for letting me know about the issue @cicero34. I will investigate this.

**Comment by sslavian812** [comment]
Hi! Can anyone help me with this issue?
I'm stuck with it for a week already.

```
Traceback (most recent call last):
  . . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 33, in __init__
    algorithm = CategoricalHyperparameter("algorithm", ["auto", "full", "elkan"], default="auto")
  File "ConfigSpace/hyperparameters.pyx", line 909, in ConfigSpace.hyperparameters.CategoricalHyperparameter.__init__
TypeError: __init__() got an unexpected keyword argument 'default'
```
I'm using 
Ubuntu 14.04.5 LTS
Python: 3.4.3
GCC: 4.8.5
Swig: 3.0.2

It seems, that some of my libraries are incompatible with each other.
Previously I was fighting with this issue:
https://github.com/automl/auto-sklearn/issues/342

I tries to reinstall different versions of libraries, but it didn't help. 
For now, I've completely reinstalled my virtual environment.  `$pip list` gives following. Some of these packages I've installed manually (like smac, numpy, sklearn), some of them were installed as dependencies automatically.

```
alabaster (0.7.10)
argparse (1.4.0)
Babel (2.5.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigSpace (0.4.3)
cycler (0.10.0)
Cython (0.27.3)
docutils (0.14)
idna (2.6)
imagesize (0.7.1)
Jinja2 (2.10)
joblib (0.11)
MarkupSafe (1.0)
matplotlib (2.1.1)
numpy (1.13.3)
pandas (0.21.0)
pip (1.5.4)
psutil (5.4.2)
Pygments (2.2.0)
pynisher (0.4.2)
pyparsing (2.2.0)
pyrfr (0.7.0)
python-dateutil (2.6.1)
pytz (2017.3)
requests (2.18.4)
scikit-learn (0.19.1)
scipy (1.0.0)
setuptools (2.2)
six (1.11.0)
sklearn (0.0)
smac (0.8.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
typing (3.6.2)
urllib3 (1.22)
```

If I explicitly install ConfigSpace==0.3.10 as suggested here, I get 
```
Traceback (most recent call last):
  . . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 11, in <module>
    from smac.configspace import ConfigurationSpace
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/configspace/__init__.py", line 2, in <module>
    from ConfigSpace.read_and_write import pcs, pcs_new
ImportError: No module named 'ConfigSpace.read_and_write'
```

If I downgrade smac to 0.7.2,  (while using ConfigSpace 0.3.10) I get back the same error as above:
```
TypeError: __init__() got an unexpected keyword argument 'default'
```


If I use smac 0.7.2 with ConfigSpace 0.4.3, I get:
```
Traceback (most recent call last):
  ...
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 11, in <module>
    from smac.configspace import ConfigurationSpace
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/configspace/__init__.py", line 2, in <module>
    from ConfigSpace.io import pcs, pcs_new
ImportError: No module named 'ConfigSpace.io'
```

Can you please help me understand, what's going on here and how to fix it?
I'm totally stuck here.

**Comment by mfeurer** [comment]
You're using a too new version of SMAC with an older version of the ConfigSpace. Please use the versions given in the requirements file:
```
ConfigSpace>=0.3.3,<0.4
pynisher>=0.4
pyrfr>=0.6.1,<0.7
smac>=0.6.0,<0.7
```

**Comment by sslavian812** [comment]
I still have this issue. Consider the categorical hyperparameter:
`algorithm = CategoricalHyperparameter("algorithm", ["auto", "full", "elkan"], default="auto")`

If I have the `default` argument, it complains about having this default:
```
Traceback (most recent call last):
  File "ExhaustiveSearch.py", line 186, in <module>
    run(argfile)
  File "ExhaustiveSearch.py", line 100, in run
    th[0] = t.km_thread(metric, X, seed)
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 33, in __init__
    algorithm = CategoricalHyperparameter("algorithm", ["auto", "full", "elkan"], default="auto")
  File "ConfigSpace/hyperparameters.pyx", line 909, in ConfigSpace.hyperparameters.CategoricalHyperparameter.__init__
TypeError: __init__() got an unexpected keyword argument 'default'
```

If I remove the `default` argument from here, It complains about not having attribute default:
`algorithm = CategoricalHyperparameter("algorithm", ["auto", "full", "elkan"])`

```
Traceback (most recent call last):
  . . .
  File "/nfs/home/vshalamov/WORK/MultiClustering/ThreadsEx.py", line 48, in __init__
    "deterministic": "true"
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/scenario/scenario.py", line 116, in __init__
    self.out_writer.write_scenario_file(self)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/utils/io/output_writer.py", line 55, in write_scenario_file
    new_value = self._parse_argument(scenario, key, getattr(scenario, key))
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/utils/io/output_writer.py", line 94, in _parse_argument
    self.write_pcs_file(scenario.cs, new_path)
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/smac/utils/io/output_writer.py", line 161, in write_pcs_file
    fh.write(pcs.write(cs))
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/ConfigSpace/io/pcs_new.py", line 411, in write
    param_lines.write(build_categorical(hyperparameter))
  File "/nfs/home/vshalamov/WORK/environment/multi-clustering-environment/lib/python3.4/site-packages/ConfigSpace/io/pcs_new.py", line 77, in build_categorical
    str(param.default))
AttributeError: 'ConfigSpace.hyperparameters.CategoricalHyperparame' object has no attribute 'default'
```
Seems, that I have all packages as suggested:
```
ConfigSpace==0.3.3
pynisher==0.4
pyrfr==0.6.1
smac==0.6.0
```

pip list produces the following output:
```
alabaster (0.7.10)
argparse (1.4.0)
auto-sklearn (0.2.1)
Babel (2.5.1)
certifi (2017.11.5)
chardet (3.0.4)
ConfigSpace (0.3.3)
cycler (0.10.0)
Cython (0.27.3)
docutils (0.14)
idna (2.6)
imagesize (0.7.1)
Jinja2 (2.10)
joblib (0.11)
liac-arff (2.1.1)
lockfile (0.12.2)
MarkupSafe (1.0)
matplotlib (2.1.0)
nose (1.3.7)
numpy (1.13.3)
pandas (0.21.0)
pip (1.5.4)
psutil (5.4.3)
Pygments (2.2.0)
pynisher (0.4)
pyparsing (2.2.0)
pyrfr (0.6.1)
python-dateutil (2.6.1)
pytz (2017.3)
PyYAML (3.12)
requests (2.18.4)
scikit-learn (0.18.2)
scipy (1.0.0)
setuptools (2.2)
six (1.11.0)
sklearn (0.0)
smac (0.6.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-websupport (1.0.1)
typing (3.6.2)
urllib3 (1.22)
```

**Comment by mfeurer** [comment]
Version `0.3.3` of the ConfigSpace does not contain any `.pyx` files. Could you please remove all `.pyx`, all `.c` and all `.so` files from the ConfigSpace installation and try again?

**Comment by sslavian812** [comment]
@mfeurer 
Thank you for your help and patience! I've finally passed this issue.

**Comment by Cosmic-AJ** [comment]
I got an error. How can I solve it?

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-68c211ec8edb> in <module>
     11 ml_predictor = Predictor(type_of_estimator='regressor', column_descriptions=column_descriptions)
     12 
---> 13 ml_predictor.train(df_train)
     14 
     15 ml_predictor.score(df_test, df_test.MEDV)

~\Anaconda3\lib\site-packages\auto_ml\predictor.py in train(***failed resolving arguments***)
    641                         estimator_names = self._get_estimator_names()
    642 
--> 643                     X_df = self.fit_transformation_pipeline(X_df, y, estimator_names)
    644             else:
    645                 X_df = self.transformation_pipeline.transform(X_df)

~\Anaconda3\lib\site-packages\auto_ml\predictor.py in fit_transformation_pipeline(self, X_df, y, model_names)
    884 
    885         self.keep_cat_features = keep_cat_features
--> 886         ppl = self._construct_pipeline(model_name=model_names[0], keep_cat_features=self.keep_cat_features)
    887         ppl.steps.pop()
    888 

~\Anaconda3\lib\site-packages\auto_ml\predictor.py in _construct_pipeline(self, model_name, trained_pipeline, final_model, feature_learning, final_model_step_name, prediction_interval, keep_cat_features, is_hp_search)
    202                 params = self.training_params
    203 
--> 204             final_model = utils_models.get_model_from_name(model_name, training_params=params)
    205             pipeline_list.append(('final_model', utils_model_training.FinalModelATC(model=final_model, type_of_estimator=self.type_of_estimator, ml_for_analytics=self.ml_for_analytics, name=self.name, _scorer=self._scorer, feature_learning=feature_learning, uncertainty_model=self.need_to_train_uncertainty_model, training_prediction_intervals=training_prediction_intervals, column_descriptions=self.column_descriptions, training_features=training_features, keep_cat_features=keep_cat_features, is_hp_search=is_hp_search, X_test=self.X_test, y_test=self.y_test)))
    206 

~\Anaconda3\lib\site-packages\auto_ml\utils_models.py in get_model_from_name(model_name, training_params, is_hp_search)
    174 
    175     if catboost_installed:
--> 176         model_map['CatBoostRegressor'] = CatBoostRegressor(calc_feature_importance=True)
    177         model_map['CatBoostClassifier'] = CatBoostClassifier(calc_feature_importance=True)
    178 

TypeError: __init__() got an unexpected keyword argument 'calc_feature_importance'
```

**Comment by mfeurer** [comment]
@Cosmic-AJ you're in the wrong repository. This repository is about Auto-sklearn while you're using a package called auto_ml
