### ISSUE TITLE
Unable to install pyrfr on Ubuntu

### ISSUE THREAD

**Issue by tsekulski** [automl/auto-sklearn#394]
Hi,

While running:
`curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install`
I get the following error:
`Collecting pyrfr<0.7,>=0.6.1`
`Could not find a version that satisfies the requirement pyrfr<0.7,>=0.6.1 (from versions: 0.4.0) No matching distribution found for pyrfr<0.7,>=0.6.1`

Then I downloaded pyrfr 0.6.1 and tried installing manually:
`sudo python setup.py install`
And as an alternative:
`sudo pip install pyrfr`

In  both cases I get the following error:
```
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-Xb6TjN/pyrfr/setup.py", line 42, in <module>
        cmdclass={'install': CustomInstall}
      `File "/usr/lib/python2.7/distutils/core.py", line 151, in setup`
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands`
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-Xb6TjN/pyrfr/setup.py", line 9, in run
        build.run(self)
    TypeError: unbound method run() must be called with build instance as first argument (got CustomInstall instance instead)

```

Any hints how to pass this hurdle would be appreciated. Thanks in advance.

**Comment by tsekulski** [comment]
Here is the full log:
```
pyrfr-0.6.1 $ sudo python setup.py install
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
running install
running build_ext
building '_regression' extension
swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pyrfr
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./include -I/usr/include/python2.7 -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -O2 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
creating build/lib.linux-x86_64-2.7
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -o build/lib.linux-x86_64-2.7/_regression.so
building '_util' extension
swigging pyrfr/util.i to pyrfr/util_wrap.cpp
swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I./include -I/usr/include/python2.7 -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -O2 -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -o build/lib.linux-x86_64-2.7/_util.so
Traceback (most recent call last):
  File "setup.py", line 50, in <module>
    cmdclass={'install': CustomInstall}
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "setup.py", line 14, in run
    build.run(self)
TypeError: unbound method run() must be called with build instance as first argument (got CustomInstall instance instead)
```
And here the log from running pip install:
```
sudo pip install pyrfr
(...)
Collecting pyrfr
  Downloading pyrfr-0.4.0.tar.gz (265kB)
    100% |████████████████████████████████| 266kB 125kB/s 
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vg3vG6/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gEiJnS-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.linux-x86_64-2.7
    creating build/temp.linux-x86_64-2.7/pyrfr
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python2.7 -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-2.7
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pyrfr/regression_wrap.o -o build/lib.linux-x86_64-2.7/_regression.so
    building '_util' extension
    swigging pyrfr/util.i to pyrfr/util_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python2.7 -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/pyrfr/util_wrap.o -o build/lib.linux-x86_64-2.7/_util.so
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vg3vG6/pyrfr/setup.py", line 42, in <module>
        cmdclass={'install': CustomInstall}
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-vg3vG6/pyrfr/setup.py", line 9, in run
        build.run(self)
    TypeError: unbound method run() must be called with build instance as first argument (got CustomInstall instance instead)
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vg3vG6/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-gEiJnS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-vg3vG6/pyrfr/
```

**Comment by tsekulski** [comment]
OK, beginner's mistake - I was trying to install using Python 2.7 it seems.
