### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by janvanrijn** [automl/auto-sklearn#452]
Just installed auto-sklearn through pip, the resource library is not automatically installed.

**Comment by janvanrijn** [comment]
Scrape that. This is the stacktrace: 
```
Traceback (most recent call last):
  File "C:/projects/hyperband/curves/experiments/run_model.py", line 3, in <module>
    import curves
  File "C:\projects\hyperband\curves\__init__.py", line 1, in <module>
    import curves.utils
  File "C:\projects\hyperband\curves\utils\__init__.py", line 1, in <module>
    from .config_space import get_config_space
  File "C:\projects\hyperband\curves\utils\config_space.py", line 3, in <module>
    from autosklearn.util.pipeline import get_configuration_space
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\site-packages\autosklearn\util\pipeline.py", line 3, in <module>
    from autosklearn.pipeline.classification import SimpleClassificationPipeline
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\site-packages\autosklearn\pipeline\classification.py", line 11, in <module>
    from autosklearn.pipeline.components import classification as \
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\site-packages\autosklearn\pipeline\components\classification\__init__.py", line 16, in <module>
    AutoSklearnClassificationAlgorithm)
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\site-packages\autosklearn\pipeline\components\base.py", line 18, in find_components
    module = importlib.import_module(full_module_name)
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Jan\AppData\Local\conda\conda\envs\openml-general\lib\site-packages\autosklearn\pipeline\components\classification\libsvm_svc.py", line 1, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

And this is my pip freeze:
```
alabaster==0.7.10
auto-sklearn==0.3.0
Babel==2.5.3
bleach==2.1.3
certifi==2018.1.18
chardet==3.0.4
colorama==0.3.9
ConfigSpace==0.4.6
cycler==0.10.0
Cython==0.28.1
debtcollector==1.19.0
decorator==4.2.1
docutils==0.14
entrypoints==0.2.3
fasteners==0.14.1
html5lib==1.0.1
idna==2.6
imagesize==1.0.0
ipykernel==4.8.2
ipython==6.2.1
ipython-genutils==0.2.0
ipywidgets==7.1.2
iso8601==0.1.12
jedi==0.11.1
Jinja2==2.10
joblib==0.11
JsonForm==0.0.2
jsonschema==2.6.0
JsonSir==0.0.2
jupyter==1.0.0
jupyter-client==5.2.2
jupyter-console==5.2.0
jupyter-core==4.4.0
kiwisolver==1.0.1
liac-arff==2.2.0
lockfile==0.12.2
MarkupSafe==1.0
matplotlib==2.2.0
mistune==0.8.3
mock==2.0.0
monotonic==1.4
nbconvert==5.3.1
nbformat==4.4.0
netaddr==0.7.19
netifaces==0.10.6
nose==1.3.7
notebook==5.4.0
numpy==1.14.2
openml==0.6.0
oslo.concurrency==3.26.0
oslo.config==5.2.0
oslo.i18n==3.20.0
oslo.utils==3.36.0
packaging==17.1
pandas==0.22.0
pandocfilters==1.4.2
parso==0.1.1
pbr==3.1.1
pickleshare==0.7.4
prompt-toolkit==1.0.15
psutil==5.4.3
Pygments==2.2.0
pynisher==0.4.2
pyparsing==2.2.0
pyrfr==0.7.4
python-dateutil==2.7.0
Python-EasyConfig==0.1.7
pytz==2018.3
pywinpty==0.5.1
PyYAML==3.12
pyzmq==17.0.0
qtconsole==4.3.1
requests==2.18.4
Resource==0.2.1
rfc3986==1.1.0
scikit-learn==0.19.1
scipy==1.0.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.11.0
smac==0.8.0
snowballstemmer==1.2.1
Sphinx==1.7.2
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
stevedore==1.28.0
terminado==0.8.1
testpath==0.3.1
tornado==5.0
traitlets==4.3.2
typing==3.6.4
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.1.4
wincertstore==0.2
wrapt==1.10.11
xmltodict==0.11.0
```

**Comment by janvanrijn** [comment]
I am on windows indeed. Cool, thanks!

**Comment by mfeurer** [comment]
I just pushed a new release - it will raise an error if Auto-sklearn is executed on a Windows platform.
