### ISSUE TITLE
Errors with 

### ISSUE THREAD

**Issue by vivekaxl** [automl/auto-sklearn#456]
```
    automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=3600,
        per_run_time_limit=30,
        resampling_strategy='cv',
        resampling_strategy_arguments={'folds': 3},
        include_estimators=["libsvm_svc", ], exclude_estimators=None,
        include_preprocessors = ["no_preprocessing", ], exclude_preprocessors = None,
        ensemble_size=0,
        seed=seed,
        smac_scenario_args={'runcount_limit': run_count}
    )

    # fit() changes the data in place, but refit needs the original data. We
    # therefore copy the data. In practice, one should reload the data
    automl.fit(train_X.copy(), train_Y.copy(), metric=perf_measure) #autosklearn.metrics.f1)


    # print(automl.show_models())
    automl.fit_ensemble(train_Y, ensemble_size=50)

    # During fit(), models are fit on individual cross-validation folds. To use
    # all available data, we call refit() which trains all models in the
    # final ensemble on the whole dataset.
    automl.refit(train_X.copy(), train_Y.copy())
    predictions = automl.predict(test_X)
```

is throwing the error:
```
Traceback (most recent call last):
  File "run_svm.py", line 155, in <module>
    automl, model = run_experiment(group.train, group.test, run_count=eval, seed=rep, perf_measure=perf_measures[perf_measure])
  File "run_svm.py", line 93, in run_experiment
    automl.fit(train_X.copy(), train_Y.copy(), metric=perf_measure) #autosklearn.metrics.f1)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/estimators.py", line 400, in fit
    dataset_name=dataset_name)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/estimators.py", line 227, in fit
    self._automl.fit(*args, **kwargs)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/automl.py", line 887, in fit
    return super().fit(X, y, task, metric, feat_type, dataset_name)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/automl.py", line 189, in fit
    return self._fit(loaded_data_manager, metric)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/automl.py", line 439, in _fit
    _proc_smac.run_smbo()
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/autosklearn/smbo.py", line 501, in run_smbo
    smac.optimize()
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/smac/optimizer/smbo.py", line 180, in run
    challengers = self.choose_next(X, Y)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/smac/optimizer/smbo.py", line 247, in choose_next
    incumbent_value = self.runhistory.get_cost(self.incumbent)
  File "/Users/viveknair/virtualenv/autosklearn/lib/python3.5/site-packages/smac/runhistory/runhistory.py", line 271, in get_cost
    config_id = self.config_ids[config]
KeyError: None

```

I replace "libsvm_svc" with "decision_tree" and it runs.

**Comment by mfeurer** [comment]
Thank you very much for reporting this. I think this happens if the first configuration fails with the given budget constraints. You can circumvent this by increasing the budget or using a different classifier as you already tried.

**Comment by vivekaxl** [comment]
Thank you, @mfeurer. 
This error is only happening in MacOS and does not happen in Ubuntu14.04. I also increased the time budget (per_run_time_limit) from 30 to 90 seconds. Please note the program fails instantly.

**Comment by mfeurer** [comment]
We don't fully support MacOS and I am aware of at least one error with respect to budgets which was fixed in the development branch, but is not yet in the master branch. Could you please try the development branch?

**Comment by mfeurer** [comment]
Closing this as #608 is a report of the same issue with a later version of Auto-sklearn.
