### ISSUE TITLE
ImportError: cannot import name 'regression'

### ISSUE THREAD

**Issue by edwardljh** [automl/auto-sklearn#542]
meachine:ubuntu 16.04
python_version:python3.5

import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics
import autosklearn.regression

Traceback (most recent call last):
  File "/home/ubuntu/python_project/sklearn_examples/test_tmp.py", line 6, in <module>
    import autosklearn.regression
  File "/usr/local/lib/python3.5/dist-packages/autosklearn/regression.py", line 1, in <module>
    from autosklearn.estimators import AutoSklearnRegressor
  File "/usr/local/lib/python3.5/dist-packages/autosklearn/estimators.py", line 4, in <module>
    from autosklearn.automl import AutoMLClassifier, AutoMLRegressor
  File "/usr/local/lib/python3.5/dist-packages/autosklearn/automl.py", line 31, in <module>
    from autosklearn.smbo import AutoMLSMBO
  File "/usr/local/lib/python3.5/dist-packages/autosklearn/smbo.py", line 10, in <module>
    from smac.facade.smac_facade import SMAC
  File "/usr/local/lib/python3.5/dist-packages/smac-0.8.0-py3.5.egg/smac/facade/smac_facade.py", line 24, in <module>
  File "/usr/local/lib/python3.5/dist-packages/smac-0.8.0-py3.5.egg/smac/optimizer/smbo.py", line 11, in <module>
  File "/usr/local/lib/python3.5/dist-packages/smac-0.8.0-py3.5.egg/smac/epm/rf_with_instances.py", line 4, in <module>
ImportError: cannot import name 'regression'

please help me 
thanks

**Comment by edwardljh** [comment]
i found smac-0.8.0.dist-info is not a directory  so  I delete it and reinstall smac
I found it is error from 'from  pyrfr import regression ' so I reinstall pyrfr
Then it works
