### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by maracuja-juice** [automl/auto-sklearn#568]
Running: `pip install auto-sklearn`

I get this error: 
```
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-oniyqyr7/xgboost/
```

How can I overcome this error?

Platform: macOS
Python Environment: Anaconda

Log:

```
Collecting auto-sklearn
  Using cached https://files.pythonhosted.org/packages/0a/a6/cbbff9205cb7dc71d67a6c05ecdd5aa05856bc1638360238d25a4a01d670/auto-sklearn-0.4.0.tar.gz
Requirement already satisfied: setuptools in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (39.1.0)
Requirement already satisfied: nose in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.3.7)
Requirement already satisfied: six in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.11.0)
Requirement already satisfied: Cython in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.28.5)
Requirement already satisfied: numpy>=1.9.0 in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.15.1)
Requirement already satisfied: scipy>=0.14.1 in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (1.1.0)
Requirement already satisfied: scikit-learn<0.20,>=0.19 in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.19.2)
Collecting lockfile (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting joblib (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/69/91/d217cec1fe6eac525ca964cd67e4f79b1d4ce68b64cb82d0b9ae1af2311e/joblib-0.12.5-py2.py3-none-any.whl
Requirement already satisfied: psutil in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (5.4.7)
Requirement already satisfied: pyyaml in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (3.13)
Collecting liac-arff (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/c9/c3/6966861e2f4d302ac3a36821f7ac503b57d98cb9cc3b28e9cd8ef8b7df65/liac-arff-2.3.1.tar.gz
Requirement already satisfied: pandas in /anaconda3/lib/python3.6/site-packages (from auto-sklearn) (0.23.4)
Collecting ConfigSpace<0.5,>=0.4.0 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/40/53/e54835d444153ba461fe8aec28533a1ffc3c5531b89509c8029b6b57a7e7/ConfigSpace-0.4.7.tar.gz
Collecting pynisher<0.5,>=0.4 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/d2/cd/4e0469a55fd280df177af2d5e94d72541d3bb0115280e31a23c8922987e6/pynisher-0.4.2.tar.gz
Collecting pyrfr<0.8,>=0.6.1 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/c3/c6/c555cfa3c7d0078dded091d4901ed52344bbb925077aa70b871faf35fd58/pyrfr-0.7.4.tar.gz
Collecting smac<0.9,>=0.8 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/33/ab/2b0a6fb00bd76e2415a04dcca453ad0b0db9b4218b02401306ff2bc6135d/smac-0.8.0.tar.gz
Collecting xgboost==0.7.post3 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/cb/1c/a2ec1798d444e2b86b27fdbf18d9ab08c25c3d374de77429b55a76f42404/xgboost-0.7.post3.tar.gz
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost
    + cd ./xgboost/
    + [[ darwin16 == \d\a\r\w\i\n* ]]
    + LIB_XGBOOST=libxgboost.dylib
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    c++ -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -I/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clang: error: unsupported option '-fopenmp'
    clang: error: clang: error: unsupported option '-fopenmp'
    unsupported option '-fopenmp'
    clang: error: unsupported option '-fopenmp'
    make: *** [build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [build/learner.o] Error 1
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** [build/c_api/c_api.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    cd R-package/src; rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; cd /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost
    /bin/sh: line 0: cd: R-package/src: No such file or directory
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    Makefile:43: /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/make/dmlc.mk: No such file or directory
    make: *** No rule to make target `/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/dmlc-core/make/dmlc.mk'.  Stop.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/xgboost/./lib/libxgboost.dylib
    /anaconda3/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/dm/z5fc_93n545b5fr26nc16x8h0000gp/T/pip-install-e1kr474m/xgboost/
```

**Comment by maelfabien** [comment]
Same issue for me

**Comment by felipecorchs** [comment]
Any update on instaling auto-sklearn on a Mac? Similar problem here (Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/90/bfxjg4yx7412gcnjlcj_52k80000gn/T/pip-install-7bw0w3o5/xgboost/)

**Comment by mfeurer** [comment]
No, sorry, but we're also not working on making Auto-sklearn run on OSX. If Docker is not an option you need to wait a bit, we're currently working on replacing XGBoost by the latest scikit-learn GBM implementation.
