### ISSUE TITLE
Metafeatures progress

### ISSUE THREAD

**Issue by silviutofan92** [automl/auto-sklearn#571]
Hello, 

I'm trying to use the metafeatures part of the library in a piece of code, but getting an error. Is the piece of code just not finished and not intended to work yet, or is there any mis-use in my snippet? Thank you!

auto-sklearn/autosklearn/metalearning/metafeatures/metafeatures.py

`import numpy as np
import pandas as pd
import autosklearn.metalearning.metafeatures.metafeatures as automl

df = pd.read_csv('~/Documents/GitStuff/metaml/s3_kaggle_dataset_house-prices-advanced-regression-techniques.csv')
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
feat = automl.calculate_all_metafeatures(X, y, categorical='all', dataset_name='name')
`

Here's the traceback:
> Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1668, in <module>
    main()
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1662, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/pydevd.py", line 1072, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/stofan/Documents/GitStuff/metaml/metamain.py", line 16, in <module>
    x = automl.calculate_all_metafeatures(X, y, categorical='all', dataset_name='name')
  File "/Users/stofan/anaconda3/envs/test/lib/python3.7/site-packages/autosklearn/metalearning/metafeatures/metafeatures.py", line 952, in calculate_all_metafeatures
    X_transformed = ohe.fit_transform(X)
  File "/Users/stofan/anaconda3/envs/test/lib/python3.7/site-packages/autosklearn/pipeline/implementations/OneHotEncoder.py", line 255, in fit_transform
    self.categorical_features, copy=True)
  File "/Users/stofan/anaconda3/envs/test/lib/python3.7/site-packages/autosklearn/pipeline/implementations/OneHotEncoder.py", line 28, in _transform_selected
    X = check_array(X, accept_sparse='csc', force_all_finite=False, copy=copy)
  File "/Users/stofan/anaconda3/envs/test/lib/python3.7/site-packages/sklearn/utils/validation.py", line 448, in check_array
    array = array.astype(np.float64)
ValueError: could not convert string to float: 'RL'

**Comment by mfeurer** [comment]
Pandas Dataframes are not supported. Please convert your code into a numpy array of type float as required by scikit-learn models.
