### ISSUE TITLE
Memory Exception with cross validation

### ISSUE THREAD

**Issue by ice-blaze** [automl/auto-sklearn#582]
#558  fixed the issue with big dataset. But now there is a memory issue with cross validation. I don't know if it's related:
```
[WARNING] [2018-11-14 11:39:36,757:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] No models better than random - using Dummy Score!
[WARNING] [2018-11-14 11:39:36,773:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] Memory Exception -- restart with less ensemle_nbest: 3
[WARNING] [2018-11-14 11:39:36,815:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] Error loading /tmp/autosklearn_tmp_13747_8571/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/ensemble_builder.py", line 317, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/metrics/__init__.py", line 308, in calculate_score
    score = metric(solution, prediction)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/metrics/__init__.py", line 69, in __call__
    **self._kwargs)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 72, in _check_targets
    type_true = type_of_target(y_true)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/utils/multiclass.py", line 283, in type_of_target
    if y.dtype.kind == 'f' and np.any(y != y.astype(int)):
MemoryError

[WARNING] [2018-11-14 11:39:36,815:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] No models better than random - using Dummy Score!
[WARNING] [2018-11-14 11:39:36,829:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] Memory Exception -- restart with less ensemle_nbest: 1
[WARNING] [2018-11-14 11:39:36,871:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] Error loading /tmp/autosklearn_tmp_13747_8571/.auto-sklearn/predictions_ensemble/predictions_ensemble_1_1.npy: Traceback (most recent call last):
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/ensemble_builder.py", line 317, in read_ensemble_preds
    all_scoring_functions=False)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/metrics/__init__.py", line 308, in calculate_score
    score = metric(solution, prediction)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/autosklearn/metrics/__init__.py", line 69, in __call__
    **self._kwargs)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 176, in accuracy_score
    y_type, y_true, y_pred = _check_targets(y_true, y_pred)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 72, in _check_targets
    type_true = type_of_target(y_true)
  File "/home/someone/.local/share/virtualenvs/predict-YcUH-Xu6/lib/python3.6/site-packages/sklearn/utils/multiclass.py", line 283, in type_of_target
    if y.dtype.kind == 'f' and np.any(y != y.astype(int)):
MemoryError

[WARNING] [2018-11-14 11:39:36,871:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] No models better than random - using Dummy Score!
[CRITICAL] [2018-11-14 11:39:36,887:EnsembleBuilder(1):ce31a5bab4fd28ba7285abe424db315e] Memory Exception -- Unable to escape from memory exception
```

My dataset size is `(982840, 5)` and I have a memory limit of `ml_memory_limit=26024`

I used the `0.4.1` version downloaded on Pypi. This version differ from GitHub tag https://github.com/automl/auto-sklearn/tree/v.0.4.1/autosklearn. I have the modification of this commit https://github.com/automl/auto-sklearn/commit/ab45a25a162dec15491ad2a8a25b9c9ce386e046

**Comment by jvitorfranca** [comment]
How did you solve this problem?

**Comment by huangwei2013** [comment]
@jvitorfranca may same with this #558
