### ISSUE TITLE
install fail with missing numpy

### ISSUE THREAD

**Issue by Borda** [automl/auto-sklearn#610]
it seems that the installation fails while you install the package on a clean system and even with `numpy` installed earlier in the requirements...

```
$ pip install -r requirements.txt
Collecting scipy (from -r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/ab/19/c0ad5b9183ef97030edd6297d1726525ff2c369a09fbb6ea52a1e616ffd6/scipy-1.2.0-cp35-cp35m-manylinux1_x86_64.whl (26.5MB)
Collecting numpy (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/86/04/bd774106ae0ae1ada68c67efe89f1a16b2aa373cc2db15d974002a9f136d/numpy-1.15.4-cp35-cp35m-manylinux1_x86_64.whl (13.8MB)
Collecting matplotlib (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/ad/4c/0415f15f96864c3a2242b1c74041a806c100c1b21741206c5d87684437c6/matplotlib-3.0.2-cp35-cp35m-manylinux1_x86_64.whl (12.9MB)
Collecting scikit-learn (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/18/d9/bea927c86bf78d583d517f24cbc87606cb333bfb3a5c99cb85b547305f0f/scikit_learn-0.20.2-cp35-cp35m-manylinux1_x86_64.whl (5.3MB)
Collecting auto-sklearn (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/46/20/587724f41169bb787952eedaa70e021a684feb548a98a3f229ca3bf6f5e9/auto-sklearn-0.4.2.tar.gz (3.4MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3vjh1gxz/auto-sklearn/setup.py", line 4, in <module>
        import numpy as np
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-3vjh1gxz/auto-sklearn/
```
I was using the build-in gitlab.com CI
```
tests:
  image: python:3.5

  before_script:
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install --upgrade setuptools

  script:
  - pip install -r requirements.txt
```

**Comment by Borda** [comment]
looking to the .travis.yaml it seems that it was tested only for Conda, would you consider also a general Linux test environment?

**Comment by Borda** [comment]
it seems that the same issue is for https://github.com/automl/ConfigSpace
```
Collecting ConfigSpace<0.5,>=0.4.0 (from auto-sklearn==0.4.2->-r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/40/53/e54835d444153ba461fe8aec28533a1ffc3c5531b89509c8029b6b57a7e7/ConfigSpace-0.4.7.tar.gz (913kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-seoc0nwj/ConfigSpace/setup.py", line 4, in <module>
        import numpy as np
    ImportError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-seoc0nwj/ConfigSpace/
```

**Comment by Borda** [comment]
Fixed and added CI for clean Ubuntu distro.

**Comment by aravind-vasudevan** [comment]
> Fixed and added CI for clean Ubuntu distro.

@Borda I just tried to install it on a clean system (no numpy installed) and ConfigSpace fails still with the same error

**Comment by Borda** [comment]
`ConfigSpace` is another package which was not fixed by this patch :)

**Comment by aravind-vasudevan** [comment]
@Borda can you point to your fix? I will try and port it over to ConfigSpace as well

**Comment by Borda** [comment]
I believe that it was done in this PR https://github.com/automl/auto-sklearn/pull/611

**Comment by aravind-vasudevan** [comment]
> I believe that it was done in this PR #611

Super, thanks. I think the fix for `ConfigSpace` will be a one-liner that adds `numpy` to `install_requires`.

**Comment by braaannigan** [comment]
I also got this error building a docker image from python 3.7 and a workaround was to pip install numpy directly before running pip on requirements.txt
