### ISSUE TITLE
OSError: [Errno 28] No space left on device\n\

### ISSUE THREAD

**Issue by smilesun** [automl/auto-sklearn#643]
I met this problem, when I try to sepcify another folder name, in the second task, it said

```
Traceback (most recent call last):                                                                                                                                                     
  File "/home/hpc/pr74ze/di36tij/.conda/envs/w_env/lib/python3.6/site-packages/autosklearn/util/backend.py", line 104, in __del__                                                      
    self.delete_directories(force=False)                                                                                                                                               
  File "/home/hpc/pr74ze/di36tij/.conda/envs/w_env/lib/python3.6/site-packages/autosklearn/util/backend.py", line 113, in delete_directories                                           
    "auto-sklearn." % self.output_directory)                                                                                                                                           
ValueError: Failed to delete output dir: /home/hpc/pr74ze/di36tij/autosklearn_out because auto-sklearn did not create it. Please make sure that the specified output dir does not exist
 when instantiating auto-sklearn.
Error in { :
  task 2 failed - "FileExistsError: [Errno 17] File exists: '/home/hpc/pr74ze/di36tij/autosklearn_tmp'
```

**Comment by mfeurer** [comment]
Hm, the issue name and the posted error do not match. Regarding the posted error, you have to specify a different directory for each call, for example by adding the seed or a dataset ID to the output directory.

**Comment by Oli2** [comment]
Actually, I am experiencing the issue as per the subject and here is my output:

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
OSError: [Errno 28] No space left on device
Call stack:
  File "/automl/source_code/autosklearn_regressor_1h_yaml.py", line 176, in <module>
    main()
  File "/automl/source_code/autosklearn_regressor_1h_yaml.py", line 100, in main
    automl_reg.fit(X_train, y_train, metric= autosklearn.metrics.mean_squared_error)
  File "/usr/local/lib/python3.6/dist-packages/autosklearn/estimators.py", line 802, in fit
    dataset_name=dataset_name,
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/usr/local/lib/python3.6/dist-packages/smac/optimizer/smbo.py", line 196, in run
    output_directory=self.scenario.output_dir_for_this_run)
  File "/usr/local/lib/python3.6/dist-packages/smac/optimizer/pSMAC.py", line 83, in write
    run_history.save_json(temporary_filename, save_external=False)
  File "/usr/local/lib/python3.6/dist-packages/smac/runhistory/runhistory.py", line 333, in save_json
    "configs": configs}, fp, cls=EnumEncoder)
OSError: [Errno 28] No space left on device

I will apprecite your view on possible cause of the problem

**Comment by mfeurer** [comment]
Hey @Oli2, the issue is that your hard drive is full. Auto-sklearn can save quite a lot of files to disk. If that's the issue, we recently added a new argument, `max_models_on_disc`, with which you can limit the number of model Auto-sklearn will keep on the disk to build an ensemble in the end.
