### ISSUE TITLE
autosklearn can not load models by filename

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#69]
After the run seem to have completed successfully (some completed runs logged in SMAC logs) autosklearn fails with the following error message:

```
Traceback (most recent call last):
  File "truffles-autosklearn-multy.py", line 82, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 526, in _fit
    self._load_models()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 647, in _load_models
    self.models_ = self._backend.load_all_models(seed)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 171, in load_all_models
    models = self.load_models_by_file_names(model_files)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 185, in load_models_by_file_names
    seed = int(basename_parts[0])
ValueError: invalid literal for int() with base 10: 'tmpJmPf2D'

```

**Comment by mfeurer** [comment]
It seems that there is a temporary file left in the models directory. We should add a try/catch there to make sure this doesn't make auto-sklearn fail.

If you want to reuse the models, you can try to delete the file `tmpJmPf2D` and run the model loading part again.

**Comment by Ayaro** [comment]
I'll handle this issue. The code only try to load all models when no self._ensemble is present, maybe also related to the possible memory issue #71

**Comment by Motorrat** [comment]
another exception but seems to be caused by a different issue 
```
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 75, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 526, in _fit
    self._load_models()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 647, in _load_models
    self.models_ = self._backend.load_all_models(seed)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 171, in load_all_models
    models = self.load_models_by_file_names(model_files)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 185, in load_models_by_file_names
    seed = int(basename_parts[0])
ValueError: invalid literal for int() with base 10: 'None'
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 86, in <module>
    pool.map(spawn_classifier, [fit_delay+19*i for i in range(max_pool_size)])
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'None'
```

**Comment by Motorrat** [comment]
more logs for this issue
```
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-all.py", line 76, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 526, in _fit
    self._load_models()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 647, in _load_models
    self.models_ = self._backend.load_all_models(seed)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 171, in load_all_models
    models = self.load_models_by_file_names(model_files)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 185, in load_models_by_file_names
    seed = int(basename_parts[0])
ValueError: invalid literal for int() with base 10: 'tmp396086'
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-all.py", line 86, in <module>
    pool.map(spawn_classifier, [fit_delay+60*i for i in range(max_pool_size)])
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'tmp396086'
```
```
12:20:49.947 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Starting Iteration 3
12:20:49.952 [Event Manager Dispatch Thread] DEBUG c.u.c.b.a.e.h.LogRuntimeStatistics - *****Developer Statistics*****
 Count: 3
 Incumbent ID: 1 (internal ID:0x000E)
 Number of PISPs for Incumbent: 1
 Number of Instances for Incumbent: 1
 Number of Configurations Run: 5
 Performance of the Incumbent: 2.000
 Configuration Time Budget used: 775.26 s (0%)
 Configuration Time Budget remaining: 2.15E9 s
 Wall-clock Time Budget used: 1181.57 s (98%)
 Wall-clock Time Budget remaining: 18.43 s
 Algorithm Runs used: 5.00  (0%)
 Algorithm Runs remaining: 2.15E9
 Model/Iteration used: 2.00  (0%)
 Model/Iteration remaining: 2.15E9
 Sum of Target Algorithm Execution Times (treating minimum value as 0.1): 766.979 s
 CPU time of Configurator: 8.279 s
 User time of Configurator: 8.277 s
 Outstanding Runs on Target Algorithm Evaluator: 0
 Outstanding Requests on Target Algorithm Evaluator: 0
 Total Reported Algorithm Runtime: 766.779 s
 Sum of Measured Wallclock Runtime: 591554.336 s
 Max Memory: 910 MB
 Total Java Memory: 110 MB
 Free Java Memory: 82 MB
 * PISP count is roughly the number of runs, but doesn't included redundant runs on the same problem instance & seed
12:20:49.954 [main] DEBUG c.u.c.b.a.m.b.BasicModelBuilder - Building Random Forest took 0.001 seconds
12:20:49.954 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Random Forest Built
12:20:49.957 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Optimizing EI at valdata.iteration 3. fmin: 2.0
12:20:49.957 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Compute negEI for all conf. seen at valdata.iteration 3: took 0.0 s
12:20:49.969 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Selecting 1005 challengers based on EI took 0.014 seconds
12:20:49.971 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Calling intensify with 2010 challenger(s)
12:20:49.971 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Intensification timeBound: 1.0 (s); used: 0.0  (s)
12:20:49.972 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Performing up to 1 run(s) for challenger (0x1DD7) up to a total boun
d of Infinity
12:20:49.973 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Iteration 3: Scheduling run for config (0x1DD7) on instance 1 with s
eed -1 and captime 265.0
12:20:49.984 [CLI TAE (Master Thread - #0)] DEBUG c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - Process for <Instance:1, Seed:-1, Config:0x1DD7, Kappa:265.
0, Execution Config: 0x0001> started with pid: 32052 (Environment Variable: 74d568fd-50e3-447a-ba4f-203046e3ff3c)
12:25:45.118 [CLI TAE (Master Thread - #0)] ERROR c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - The following algorithm call failed: cd "/x/truffles/./nfs_share/atsklrn_tmp" ;  runsolver --watcher-data /dev/null -W 265 -d 30 -M 15000 python /home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/SMAC_interface.py holdout ./nfs_share/atsklrn_tmp/.auto-sklearn/datamanager.pkl 265.0 2147483647 -1 -balancing:strategy 'none' -classifier:__choice__ 'sgd' -classifier:sgd:alpha '1.0904965518476374E-5' -classifier:sgd:average 'False' -classifier:sgd:eta0 '0.0962821117795657' -classifier:sgd:fit_intercept 'True' -classifier:sgd:learning_rate 'constant' -classifier:sgd:loss 'perceptron' -classifier:sgd:n_iter '47' -classifier:sgd:penalty 'l2' -imputation:strategy 'mean' -one_hot_encoding:minimum_fraction '0.005224535112945596' -one_hot_encoding:use_minimum_fraction 'True' -preprocessor:__choice__ 'no_preprocessing' -rescaling:__choice__ 'normalize'
12:25:45.118 [CLI TAE (Master Thread - #0)] DEBUG c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - No output on standard out detected
12:25:45.129 [CLI TAE (Master Thread - #0)] DEBUG c.u.c.b.a.t.b.c.CommandLineAlgorithmRun - Run <Instance:1, Seed:-1, Config:0x1DD7, Kappa:265.0, Execution Config: 0x0001> ==> <CRASHED, 0.0, 0.0, 0.0, -1,ERROR: Wrapper did not output anything that matched the expected output ("Result of algorithm run:..."). Please try executing the wrapper directly> W:(295143.0) is completed
12:25:45.131 [CLI TAE Callback Threads (3-5)] WARN  c.u.c.b.a.t.d.s.TimingCheckerTargetAlgorithmEvaluator - Algorithm Run Result reported wallclock time of 295143.0 (secs) that exceeded it's cutoff time of 265.0 (secs) by 294878.0 (secs). Next warning at 294879.0 (secs)
12:25:45.133 [main] DEBUG c.u.c.b.s.c.SequentialModelBasedAlgorithmConfiguration - Iteration 3: Completed run for config (0x1DD7) on instance 1 with seed -1 and captime 265.0 => Result: CRASHED, response: 2.0, wallclock time: 295143.0 seconds
```

**Comment by Motorrat** [comment]
Just an additional info. Increasing the per_run_time_limit from 300 to 600 has removed the above ERROR and thus the script run through. This is not a solution though, because the models still can (and should) fail if they take more time than planned. But it helps to isolate the problem.

**Comment by Motorrat** [comment]
I still face the issue. Just checking in to see whether this might have been actually fixed?

**Comment by mfeurer** [comment]
I can't reproduce the issue. Thus, I couldn't fix it. Could you paste the code which makes auto-sklearn crash? Does the crash happen for your real-world dataset or an example dataset?

**Comment by Motorrat** [comment]
The problem I have is with the real-word dataset. After all the changes in the auto-sklearn multiprocessing call pattern I am trying to get to an example code that works for it so I can be sure the problem is not somewhere else (like Python3 related issue). As soon as I have a working example I will try to put something together as a test case.
Here is what I get with the current code:
```
[ERROR] [2016-09-21 04:36:11,288:EnsembleBuilder(1):Autosklearn] Model only predicts at random: predictions_ensemble_1_00001.npy has score: -0.682690490971
[ERROR] [2016-09-21 04:36:11,289:EnsembleBuilder(1):Autosklearn] Model only predicts at random: predictions_ensemble_1_00002.npy has score: -1.0
[ERROR] [2016-09-21 04:36:11,290:EnsembleBuilder(1):Autosklearn] Model only predicts at random: predictions_ensemble_1_00003.npy has score: -0.294008360427
[ERROR] [2016-09-21 04:36:11,292:EnsembleBuilder(1):Autosklearn] Model only predicts at random: predictions_ensemble_1_00004.npy has score: -0.324792297539
[ERROR] [2016-09-21 04:36:11,293:EnsembleBuilder(1):Autosklearn] Model only predicts at random: predictions_ensemble_1_00011.npy has score: -0.692527708259
[WARNING] [2016-09-21 04:36:11,294:EnsembleBuilder(1):Autosklearn] Error loading tmpk53ptomw: [Errno 2] No such file or directory: './nfs_share/atsklrn_tmp/.auto-sklearn/predictions_ensemble/tmpk53ptomw'
Process pynisher function call:
Traceback (most recent call last):
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/x/Redly/anaconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/pynisher/limit_function_call.py", line 83, in subprocess_func
    return_value = ((func(*args, **kwargs), 0))
  File "/x/Redly/anaconda3/lib/python3.5/site-packages/autosklearn/ensemble_builder.py", line 193, in main
    automl_seed = int(match.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Ayaro** [comment]
Added hotfix to ignore random files in model folders #137

**Comment by mfeurer** [comment]
@Ayaro thanks for the fix. I have also find yet another potential issue and fixed it.
@Motorrat could you please try whether the problem is still present? If no, I can put version 0.0.3 on pypi.

**Comment by Motorrat** [comment]
@mfeurer how should I test for this? Should I install a new branch or re-install the default one?

**Comment by mfeurer** [comment]
This is on the master branch. You can try `pip uninstall auto-sklearn; pip install git+https://github.com/automl/auto-sklearn --no-deps`

**Comment by mfeurer** [comment]
This will be available on pypi this afternoon. Could you please check whether the issue is solved?

**Comment by mfeurer** [comment]
I just pushed a new auto-sklearn version (0.3.0). Please reopen if the issue still exists.
