### ISSUE TITLE
autosklearn hangs after completing multicore run

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#71]
There is no error in SMAC logs. 
top shows the autosklearn processes inactive occupying a lot of memory:

```
%Cpu(s):  0.0 us,  0.0 sy,  0.0 ni,100.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  12378092+total, 11410110+used,  9679820 free,    54200 buffers
KiB Swap:        0 total,        0 used,        0 free. 13223792 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
14599 ekobylk+  20   0 42.463g 0.037t   2848 S   0.0 32.0  28:48.66 python
14628 ekobylk+  20   0 31.582g 0.030t      8 S   0.0 26.3   1:53.21 python
14627 ekobylk+  20   0 33.422g 0.029t      0 S   0.0 25.2   5:29.03 python
18521 ekobylk+  20   0 25.770g 0.024t   1016 S   0.0 21.2   0:00.02 python
18514 ekobylk+  20   0 2897984 2.069g      0 S   0.0  1.8   0:00.04 python
18515 ekobylk+  20   0 2897984 2.069g      0 S   0.0  1.8   0:00.02 python
```

Once I have issued (CTRL+C) in the python command line for the script it has completed and shown better results as the last time with less execution time. It also shows ensemble building completion at 22:32. So may be it is even not autosklearn itself?
So I wonder what is holding the completion off? 

This is what I find in 
ensemble_err_1.log

```
Start script: /home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/ensemble_selection_script.py
[DEBUG] [22:31:57:ensemble_selection_script.py] Time left: -5.000000
[DEBUG] [22:31:57:ensemble_selection_script.py] Time last iteration: 0.000000

[ERROR] [22:31:57:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_1_00000.npy has score: -0.81935483871
[ERROR] [22:31:57:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_1_00001.npy has score: -0.532039976484

SKIP similar lines

[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00067.npy has score: -0.446875
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00068.npy has score: -0.870646766169
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00069.npy has score: -0.474626865672
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00070.npy has score: -0.989130434783
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00071.npy has score: -0.483211678832
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00072.npy has score: -0.823788546256
[ERROR] [22:31:59:ensemble_selection_script.py] Model only predicts at random: predictions_ensemble_5_00073.npy has score: -0.488023952096
[INFO] [22:32:03:ensemble_selection_script.py] Ensemble Selection:
        Trajectory: 0: -0.430189 1: -0.421986 2: -0.397436 3: -0.392625 4: -0.392625 5: -0.392625 6: -0.392625 7: -0.392625 8: -0.392625 9: -0.392625 10: -0.392625 11: -0.389610 12: -0.388949 13: -0.388949 14: -0.388949 15: -0.388949 16: -0.388949 17: -0.388949 18: -0.388949 19: -0.388949 20: -0.388949 21: -0.388949 22: -0.388949 23: -0.388949 24: -0.388949 25: -0.388949 26: -0.388949 27: -0.388949 28: -0.388949 29: -0.388949 30: -0.388949 31: -0.388949 32: -0.388949 33: -0.388949 34: -0.388949 35: -0.388949 36: -0.388949 37: -0.388949 38: -0.388949 39: -0.388949 40: -0.388949 41: -0.388949 42: -0.388949 43: -0.388949 44: -0.388949 45: -0.388949 46: -0.388949 47: -0.388949 48: -0.388949 49: -0.388949
        Members: [128, 89, 57, 271, 8, 26, 26, 46, 46, 46, 293, 344, 241, 26, 26, 26, 341, 341, 341, 341, 341, 341, 341, 341, 341, 393, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 133, 46, 293, 26, 26, 26, 26, 26, 26, 26, 26]
        Weights: [ 0.    0.    0.    0.    0.    0.    0.    0.    0.02  0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.26  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.08  0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.02  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.02
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.02  0.    0.    0.    0.    0.28  0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.02  0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.02  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.04  0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.18  0.    0.    0.02  0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.02  0.    0.    0.    0.    0.    0.    0.  ]
        Identifiers: (1, 8) (1, 26) (1, 46) (1, 57) (2, 4) (2, 43) (2, 48) (4, 4) (4, 34) (4, 56) (5, 14) (5, 17) (5, 66)
[INFO] [22:32:03:ensemble_selection_script.py] Training performance: -0.388949
[INFO] [22:32:03:ensemble_selection_script.py] Could not find as many validation set predictions (0)as ensemble predictions (401)!.
[INFO] [22:32:03:ensemble_selection_script.py] Could not find as many test set predictions (0) as ensemble predictions (401)!
[DEBUG] [22:32:03:ensemble_selection_script.py] Time left: -10.804320
[DEBUG] [22:32:03:ensemble_selection_script.py] Time last iteration: 5.765388
[DEBUG] [22:32:03:ensemble_selection_script.py] Nothing has changed since the last time
```

log-run?.txt from SMAC all show "Returning with value: 0"
example:

```
22:17:08.016 [main] DEBUG c.u.c.b.smac.executors.SMACExecutor - Returning with value: 0
22:17:08.016 [Event Manager Dispatch Thread] DEBUG c.u.c.b.a.eventsystem.EventManager - Event Manager thread done, released 0 pending flushes
22:17:08.019 [FileSharingRunHistory Logger ( outputID:1)] INFO  c.u.c.b.a.r.FileSharingRunHistoryDecorator - At shutdown: /data/atskln_tmp/faebb891c2943e03251e86c73d212016/live-rundata-1.json had 85 runs added to it
22:17:08.019 [FileSharingRunHistory Logger ( outputID:1)] INFO  c.u.c.b.a.r.FileSharingRunHistoryDecorator - At shutdown: we retrieved atleast 316 runs and added them to our current data set [live-rundata-2.json=>67, live-rundata-3.json=>85, live-rundata-4.json=>90, live-rundata-5.json=>74]
```

**Comment by mfeurer** [comment]
How large is the temporary output directory which contains all the models? Maybe auto-sklearn is still trying to load all models into main memory. This would be the case if the model directory is larger than the amount of main memory used by auto-sklearn.

We have a fix for this in the development branch and I hope that we'll merge it soon.

**Comment by Motorrat** [comment]
the temp directory size is 36GB. I have also edited my post above - Once I have issued (CTRL+C) in the python command line for the script it has completed and shown better results as the last time with less execution time. So it worked. It also shows ensemble building completion at 22:32. So may be it is even not autosklearn itself?

**Comment by mfeurer** [comment]
When you hit CTRL+C, does it show you a stack trace?

**Comment by Motorrat** [comment]
```
  ^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
Process PoolWorker-9:
Process PoolWorker-7:
Process PoolWorker-8:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    func(*targs, **kargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 305, in _exit_function
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    _run_finalizers(0)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
    racquire()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 495, in _terminate_pool
KeyboardInterrupt
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 480, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 305, in _exit_function
    _run_finalizers(0)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 495, in _terminate_pool
    cls._help_stuff_finish(inqueue, task_handler, len(pool))
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 480, in _help_stuff_finish
    inqueue._rlock.acquire()
KeyboardInterrupt
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
KeyboardInterrupt
Process PoolWorker-4:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
KeyboardInterrupt
Process PoolWorker-5:
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/pool.py", line 102, in worker
    task = get()
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/queues.py", line 376, in get
    racquire()
KeyboardInterrupt
^C^C^C

```

**Comment by mfeurer** [comment]
This issue seems to be related to the use of SMAC2 (written in Java). @Motorrat did you also observe it with a version of auto-sklearn >= 0.1.0?

**Comment by Motorrat** [comment]
I don't think I do.

**Comment by mfeurer** [comment]
Thanks for letting me know. I'm closing this for now.
