### ISSUE TITLE
the run completes but exceptions are generated

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#72]
```
Process PoolWorker-13:
Traceback (most recent call last):
Process PoolWorker-12:
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
    self.run()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 42, in signal_handler
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 305, in _exit_function
    _run_finalizers(0)
  File "/home/ekobylkin/anaconda2/lib/python2.7/multiprocessing/util.py", line 250, in _run_finalizers
    def _run_finalizers(minpriority=None):
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 42, in signal_handler
    evaluator.finish_up()
AttributeError: 'NoneType' object has no attribute 'finish_up'
    evaluator.finish_up()
AttributeError: 'NoneType' object has no attribute 'finish_up'
```

**Comment by mfeurer** [comment]
This issue should be fixed by now. @Motorrat if you still observe it with auto-sklearn >= 0.1, please reopen this issue.
