### ISSUE TITLE
Test failure: RidgeComponentTest.test_default_boston 

### ISSUE THREAD

**Issue by mu-triv** [automl/auto-sklearn#723]
This test was run on Ubuntu 17.03, autosklearn v0.6.0

**Error Message**
0.7035465377559671 != 0.7035466002329827 within 7 places (6.247701556105767e-08 difference)
**Stacktrace**
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/usr/people/jenkinsphilatelist/node2/workspace/Autosklearn_RunTestsOnPullRequest/test/test_pipeline/components/regression/test_base.py", line 48, in test_default_boston
    places=self.res.get("default_boston_places", 7),
  File "/usr/lib/python3.7/unittest/case.py", line 893, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: 0.7035465377559671 != 0.7035466002329827 within 7 places (6.247701556105767e-08 difference)

**Comment by mfeurer** [comment]
Thanks for reporting this, we have fixed this and the unit tests on travis-ci are green now.
