### ISSUE TITLE
installation fails while building xgboost, but xgboost is already installed

### ISSUE THREAD

**Issue by clstaudt** [automl/auto-sklearn#742]
I get the following error even though the xgboost Python module has already been successfully installed:

```
 !  ~$…  pip install auto-sklearn                                                                             1737ms < Wed Nov 13 12:01:57 2019
Collecting auto-sklearn
  Using cached https://files.pythonhosted.org/packages/1d/99/27caac4f6804be48722158e31c630e0737110581774df0615a36b21239aa/auto-sklearn-0.5.2.tar.gz
Requirement already satisfied: setuptools in /Users/cls/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (40.8.0)
Requirement already satisfied: nose in /Users/cls/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.3.7)
Requirement already satisfied: Cython in /Users/cls/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (0.29.6)
Requirement already satisfied: numpy>=1.9.0 in /Users/cls/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.17.3)
Requirement already satisfied: scipy>=0.14.1 in /Users/cls/anaconda3/lib/python3.7/site-packages (from auto-sklearn) (1.2.1)
Collecting scikit-learn<0.20,>=0.19 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/77/4e/397996d781c98198863478c832f66e8312e6911d8c2de06959f767f26039/scikit_learn-0.19.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting xgboost>=0.80 (from auto-sklearn)
  Using cached https://files.pythonhosted.org/packages/96/84/4e2cae6247f397f83d8adc5c2a2a0c5d7d790a14a4c7400ff6574586f589/xgboost-0.90.tar.gz
    Complete output from command python setup.py egg_info:
    ++ pwd
    + oldpath=/private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost
    + cd ./xgboost/
    + echo darwin19
    + grep -q darwin
    + LIB_XGBOOST=libxgboost.dylib
    + which g++-5
    + which g++-7
    + which g++-8
    + which clang++
    /Users/cls/anaconda3/bin//clang++
    + export CC=clang
    + CC=clang
    + export CXX=clang++
    + CXX=clang++
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    		cd R-package/src; \
    		rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    		cd /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost; \
    	fi
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    In file included from src/c_api/c_api.cc:3:
    In file included from include/xgboost/data.h:10:
    dmlc-core/include/dmlc/base.h:190:10: fatal error: 'sys/types.h' file not found
    #include <sys/types.h>
             ^~~~~~~~~~~~~
    In file included from src/learner.cc:7:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/cls/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from src/c_api/c_api_error.cc:6:
    In file included from dmlc-core/include/dmlc/thread_local.h:9:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/mutex:189:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/__mutex_base:15:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/chrono:303:
    /Users/cls/anaconda3/bin/../include/c++/v1/ctime:48:10: fatal error: 'time.h' file not found
    #include <time.h>
             ^~~~~~~~
    In file included from src/logging.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/cls/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    1 error generated.
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    1 error generated.
    1 error generated.
    make: *** [build/logging.o] Error 1
    make: *** [build/c_api/c_api.o] Error 1
    1 error generated.
    make: *** [build/learner.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    		cd R-package/src; \
    		rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    		cd /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost; \
    	fi
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [/Library/Developer/CommandLineTools/usr/bin/make] - checked OK
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api_error.o src/c_api/c_api_error.cc >build/c_api/c_api_error.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/c_api/c_api.o src/c_api/c_api.cc >build/c_api/c_api.d
    In file included from src/c_api/c_api.cc:3:
    In file included from include/xgboost/data.h:10:
    dmlc-core/include/dmlc/base.h:190:10: fatal error: 'sys/types.h' file not found
    #include <sys/types.h>
             ^~~~~~~~~~~~~
    In file included from src/learner.cc:7:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/cls/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from src/c_api/c_api_error.cc:6:
    In file included from dmlc-core/include/dmlc/thread_local.h:9:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/mutex:189:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/__mutex_base:15:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/chrono:303:
    /Users/cls/anaconda3/bin/../include/c++/v1/ctime:48:10: fatal error: 'time.h' file not found
    #include <time.h>
             ^~~~~~~~
    In file included from src/logging.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/cls/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/cls/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    1 error generated.
    make: *** [build/c_api/c_api_error.o] Error 1
    make: *** Waiting for unfinished jobs....
    1 error generated.
    make: *** [build/c_api/c_api.o] Error 1
    1 error generated.
    1 error generated.
    make: *** [build/logging.o] Error 1
    make: *** [build/learner.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost/libpath.py", line 48, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/cls/anaconda3/xgboost/libxgboost.dylib
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/kp/ws_ljfcj7nlgg3ztmd10tyrw0000gn/T/pip-install-6252m79z/xgboost/
```

**Comment by mfeurer** [comment]
We removed xgboost from the latest 0.6.0 release and replaced it with scikit-learn's new, fast HistGradientBoost. Therefore, xgboost is no longer a dependency and error like this should no longer appear. I hope this helps.
