### ISSUE TITLE
is there anyone had 'zmq.error.ZMQError: Address already in use'?

### ISSUE THREAD

**Issue by zhyjiong** [automl/auto-sklearn#767]
I just followed the example code provided by the documentation like this:
`from autosklearn.classification import AutoSklearnClassifier`
`model = AutoSklearnClassifier(ml_memory_limit=10240)`
`model.fit(xtr, ytr)`

and I got the following error message in the terminal and my jupyter kernel shutdown automatically.

> [I 11:06:02.514 LabApp] KernelRestarter: restarting kernel (4/5), keep random ports
kernel de98339e-18a4-4117-8c78-fc8d6e7f42de restarted
Traceback (most recent call last):
  File "/pilot/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/pilot/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/pilot/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/pilot/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/pilot/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/pilot/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 456, in initialize
    self.init_sockets()
  File "/pilot/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 238, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/pilot/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 180, in _bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 547, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

**Comment by rluethy** [comment]
I am trying out auto-sklearn and am running into the same problem. I have tried it on two computers, both running linux and identical virtual environments and the example from the documentation. 

On my laptop the example works but on the other system, which has 40 cores,  I am getting the 'zmq.error.ZMQError: Address already in use' error.

**Comment by rluethy** [comment]
The workaround is to use docker with the Dockerfile given for auto-sklearn.

**Comment by mfeurer** [comment]
@rluethy did you find any indication that auto-sklearn or any package that auto-sklearn uses ZMQ or any other package that opens a port? I just checked [the latest output of continuous integration](https://travis-ci.org/github/automl/auto-sklearn/jobs/688259673) and could not find any trace of ZMQ or any other packages which looks like it would start a server/open a connection.

**Comment by mfeurer** [comment]
Closing this as it appears to be an issue with jupyter and not auto-sklearn.

**Comment by mfeurer** [comment]
> am I correct in thinking that the example notebook here is a dead-end?

No, the example works and can still be used. It is continuously unit tested and I've never seen it failing. I just tried the rendered jupyter notebook on my machine, and it works without any errors. Instead of downloading the jupyter example, you can also download the raw python example.

If this issue pops up again, it would be great to know if the code that causes an issue in jupyter causes the same issue when run with ipython.

**Comment by adamlenart** [comment]
I received the same error on jupyter. When run in an ipython shell, the shell terminates immediately silently without displaying any error messages upon calling the fit method.

**Comment by mfeurer** [comment]
Seeing this again, maybe this is an issue of the pyrfr (a C++ dependency) not being compiled correctly. We have just uploaded wheels for that package to pypi, maybe using those solves this issue (`pip install pyrfr>=0.8.1`).

**Comment by adamlenart** [comment]
Thank you, issue solved! I had pyrfr 0.8.0 installed, upgrading to 0.8.1 solved it.
