### ISSUE TITLE
backend.py competes for file lock in multiprocess scenario

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#78]
I am starting 16 processes with two seconds delay on a 32 core machine like this 

```
def spawn_classifier(seed):
    time.sleep(seed) # to avoid race for lock
    c = AutoSklearnClassifier(time_left_for_this_task=overall_run, per_run_time_limit=per_task, ml_memory_limit=memory_limit,
                shared_mode=True, tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir,
                delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
                ensemble_size=0, initial_configurations_via_metalearning=0,
                include_preprocessors=('no_preprocessing',),
                include_estimators=('sgd',),
                seed=seed)
    c._task = BINARY_CLASSIFICATION
    c._metric = F1_METRIC
    c._precision = '32'
    c._dataset_name = 'MyData'
    try:
        c.fit(X_train, y_train, metric='f1_metric')
    except Exception:
        traceback.print_exc()
        raise

if __name__ == '__main__':
    pool = Pool(max_pool_size) # 16 here
    time.sleep(10)
    pool.map(spawn_classifier, [fit_delay+2*i for i in range(max_pool_size)])
    pool.close()
    pool.join()
    pool.terminate()
```

In this case seven of the processes fail and here is the stack trace

```
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 348, in _fit
    data_manager_path = self._backend.save_datamanager(datamanager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 130, in save_datamanager
    with lockfile.LockFile(lock_path):
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/lockfile/__init__.py", line 197, in __enter__
    self.acquire()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/lockfile/linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 42, in signal_handler
    evaluator.finish_up()
Received signal 15. Aborting Training!
AttributeError: 'NoneType' object has no attribute 'finish_up'
```

The problem is reproducible on all four machines I have access to but ratio of the failed processes varies a little.

**Comment by mfeurer** [comment]
I have never seen this before, but suspect your dataset is quite large and it takes quite some time to write it to disk? Have you tried to increase the delay? Besides, you can just restart the jobs if they crashed because of such an issue. The parallel implementation is only communicating via files, and it does not matter when a process starts and ends. 

Nevertheless, we should use joblib to save the numpy/scipy array in the future in order to do this faster..

**Comment by Motorrat** [comment]
yes, the dataset is large. I have increased the delay to 9 seconds and it went fine on one machine. On another (started after the processes on the first one stabilized ) I had another set of exceptions. Not sure if this is related to the same issue:
```
# 05:49 # Exception in seed=162.
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 80, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 365, in _fit
    self._do_dummy_prediction(datamanager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 313, in _do_dummy_prediction
    output_dir=self._tmp_dir)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 206, in main
    make_mode_holdout(D, seed, configuration, num_run, output_dir)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 66, in make_mode_holdout
    **_get_base_dict())
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/evaluation/holdout_evaluator.py", line 35, in __init__
    classification=classification)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/evaluation/resampling.py", line 77, in split_data
    X_train, X_valid = X[train_index], X[valid_index]
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/csr.py", line 298, in __getitem__
    extracted = P * self
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.py", line 319, in __mul__
    return self._mul_sparse_matrix(other)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 508, in _mul_sparse_matrix
    indptr, indices, data)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 42, in signal_handler
    evaluator.finish_up()
AttributeError: 'NoneType' object has no attribute 'finish_up'
Received signal 15. Aborting Training!
# 05:49 # Exception in seed=180.
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-e.py", line 80, in spawn_classifier
    c.fit(X_train, y_train, metric='f1_metric')
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 271, in fit
    feat_type, dataset_name)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 262, in fit
    return self._fit(loaded_data_manager)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 352, in _fit
    datamanager.data['Y_train'])
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 679, in _save_ensemble_data
    _, _, _, y_ensemble = resampling.split_data(X, y)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/evaluation/resampling.py", line 77, in split_data
    X_train, X_valid = X[train_index], X[valid_index]
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/csr.py", line 298, in __getitem__
    extracted = P * self
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/base.py", line 319, in __mul__
    return self._mul_sparse_matrix(other)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/scipy/sparse/compressed.py", line 508, in _mul_sparse_matrix
    indptr, indices, data)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/cli/base_interface.py", line 42, in signal_handler
    evaluator.finish_up()
AttributeError: 'NoneType' object has no attribute 'finish_up'
Received signal 15. Aborting Training!
```

**Comment by Motorrat** [comment]
I am trying to set up an automated learning environment, so restarting would require some scripting to capture the crash event and calculate the number of instances that need to be re-started etc. I will try to increase the delay between the processes even more, to "brute force" this for now. But yes, would be great if this could be un-entangled. This kind of conflict when processes undercut one another goes against the hair of having a massively parallel implementation. Another option, of course - just add an option to auto_sklearn to run x processes in parallel to exhaust node capacity and manage the concurrency within itself.

**Comment by Motorrat** [comment]
Increasing the delay between the processes to 19 seconds helped. Thanks for the tip!

**Comment by mfeurer** [comment]
This should no longer be the case with auto-sklearn 0.1.3 as parts of the backend have been rewritten. If the error persists, please reopen the issue.
