### ISSUE TITLE
Conflicting model results 

### ISSUE THREAD

**Issue by moelliDo** [automl/auto-sklearn#783]
As described in #558 I'm currently using the BPI Challenge Dataset to compute machine learning models with Auto-Sklearn. I'm running two VMs with Ubuntu 16.04, 8 Cores and 30 GB of RAM. Around 25 GB of RAM are marked as available such that I set the ml_memory_limit to 24000. I iteratively split the dataset into i features and 1 outcome to calculate machine learning models. 
I defined the classifier as follows: 
`classifier = autosklearn.classification.AutoSklearnClassifier(time_left_for_this_task=14400, per_run_time_limit=1440, ensemble_memory_limit=8000, ml_memory_limit=24000, n_jobs=8)`
Auto-Sklearn ran for 1 hour which resulted in accuracies ranging from 0.0008 to 0.99. However, after I reran the computation (with the time limit set to one hour again) the results got worse for the same feature/output combination (from accuracy=0.97 to 0.001). I additionally ran the computation for 4 hours and the results again were worse for the exact same feature outcome combination than before. I noticed the following errors during computation: 
```
Process Process-65:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/estimators.py", line 15, in _fit_automl
    return automl.fit(load_models=load_models, **kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 996, in fit
    load_models=load_models,
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 208, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 489, in _fit
    _proc_smac.run_smbo()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/smbo.py", line 504, in run_smbo
    smac.optimize()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/optimizer/smbo.py", line 192, in run
    time_bound=max(self.intensifier._min_time, time_left))
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/intensification/intensification.py", line 169, in intensify
    log_traj=log_traj)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/intensification/intensification.py", line 360, in _race_challenger
    (cutoff < self.cutoff))
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 170, in start
    capped=capped)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/tae/execute_ta_run.py", line 168, in start
    instance_specific=instance_specific)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 211, in run
    obj(**obj_kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 195, in __call__
    subproc.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process Process-63:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/estimators.py", line 15, in _fit_automl
    return automl.fit(load_models=load_models, **kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 996, in fit
    load_models=load_models,
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 208, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/automl.py", line 489, in _fit
    _proc_smac.run_smbo()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/smbo.py", line 504, in run_smbo
    smac.optimize()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/facade/smac_facade.py", line 400, in optimize
    incumbent = self.solver.run()
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/optimizer/smbo.py", line 192, in run
    time_bound=max(self.intensifier._min_time, time_left))
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/intensification/intensification.py", line 169, in intensify
    log_traj=log_traj)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/intensification/intensification.py", line 360, in _race_challenger
    (cutoff < self.cutoff))
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 170, in start
    capped=capped)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/smac/tae/execute_ta_run.py", line 168, in start
    instance_specific=instance_specific)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/autosklearn/evaluation/__init__.py", line 211, in run
    obj(**obj_kwargs)
  File "/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/pynisher/limit_function_call.py", line 195, in __call__
    subproc.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[WARNING] [2020-02-15 00:13:56,569:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
[WARNING] [2020-02-15 00:13:56,569:smac.intensification.intensification.Intensifier] Challenger was the same as the current incumbent; Skipping challenger
/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/home/user/envs/ma-automl-ppm/lib/python3.6/site-packages/sklearn/metrics/classification.py:1439: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)
Accuracy: 0.06166777894301967
F1 (weighted): 0.058953502911216704
```

Could it be, that these errors result in the cancellation of model computations such that auto-sklearn starts from scratch? Is there any way I could prevent these errors? 

Thank you in advance and have a nice day.

**Comment by mfeurer** [comment]
Hey, they might be two issues here:
* if you run for 4 hours, Auto-sklearn might overfit a bit. If possible, you could go cross-validation.
* the `ml_memory_limit` is per job. If you run eight jobs in parallel, each of them can use 24 GB in your example, which can result in the machine being full. Could you try with a smaller number, maybe 6GB (which is only twice the total RAM if all jobs use all RAM instead of eight times the total RAM).

You can check how many configurations Auto-sklearn tried and how many failed with [this function](https://automl.github.io/auto-sklearn/master/api.html#autosklearn.classification.AutoSklearnClassifier.sprint_statistics). Could you maybe also give some details on the dataset, I'm not familiar with this.
