### ISSUE TITLE
Dummy Prediction Timeout Error

### ISSUE THREAD

**Issue by KeikiHekili** [automl/auto-sklearn#800]
Hello. I'm trying to run one of the auto-sklearn examples, and I keep getting a timeout error, even after increasing the `per_run_time_limit` to 7200. Below is the code and the outputted error message. Of note, I'm running this on OSX, so I'm not sure if that is part of the problem. I then ran this program in Terminal, and saw more error messages crop up. Any help is welcome, thanks. 

Code:
```
import autosklearn.classification
import sklearn.model_selection
import sklearn.datasets
import sklearn.metrics
X, y = sklearn.datasets.load_digits(return_X_y=True)
X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)
automl = autosklearn.classification.AutoSklearnClassifier(
    per_run_time_limit=9600,
    ml_memory_limit=4000)
automl.fit(X_train, y_train)
y_hat = automl.predict(X_test)
print("Accuracy score", sklearn.metrics.accuracy_score(y_test, y_hat))
```

Error message
```
[ERROR] [2020-03-14 19:15:31,496:AutoML(1):d74860caaa557f473ce23908ff7ba369] Error creating dummy predictions: {'error': 'Timeout', 'configuration_origin': 'DUMMY'} 
Traceback (most recent call last):
  File "autoSKlearnExample.py", line 11, in <module>
    automl.fit(X_train, y_train)
  File "/usr/local/lib/python3.7/site-packages/autosklearn/estimators.py", line 664, in fit
    dataset_name=dataset_name,
  File "/usr/local/lib/python3.7/site-packages/autosklearn/estimators.py", line 337, in fit
    self._automl[0].fit(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/autosklearn/automl.py", line 996, in fit
    load_models=load_models,
  File "/usr/local/lib/python3.7/site-packages/autosklearn/automl.py", line 208, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/usr/local/lib/python3.7/site-packages/autosklearn/automl.py", line 384, in _fit
    num_run = self._do_dummy_prediction(datamanager, num_run)
  File "/usr/local/lib/python3.7/site-packages/autosklearn/automl.py", line 313, in _do_dummy_prediction
    raise ValueError("Dummy prediction failed: %s " % str(additional_info))
ValueError: Dummy prediction failed: {'error': 'Timeout', 'configuration_origin': 'DUMMY'} 
```

Error message in Terminal
```
$ /usr/local/Cellar/python/3.7.6_1/bin/python3 autoSKlearnExample.py
/usr/local/lib/python3.7/site-packages/pyparsing.py:3174: FutureWarning: Possible set intersection at position 3
  self.re = re.compile(self.reString)
Time limit for a single run is higher than total time limit. Capping the limit for a single run to the total time given to SMAC (3598.997310)
[WARNING] [2020-03-14 19:30:56,073:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:30:56,099:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
Segmentation fault: 11
$ [WARNING] [2020-03-14 19:30:58,108:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:00,113:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:02,119:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:04,123:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:06,129:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:08,136:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
[WARNING] [2020-03-14 19:31:10,141:EnsembleBuilder(1):d74860caaa557f473ce23908ff7ba369] No models better than random - using Dummy Score!
```

**Comment by mfeurer** [comment]
Hi, it's hard to say whether that's an issue with OSX. Could you please give some information about the size of your dataset? Have you also tried with smaller subsets of the data and does that also fail?

**Comment by KeikiHekili** [comment]
The data set is roughly 5000 points with 13 variables. I ran it on a Linux system, and it worked fine.

**Comment by mfeurer** [comment]
> and it worked fine.

So this means it works? If not, is it possible for you to share the data and script so we can try to reproduce this on our side?

**Comment by KeikiHekili** [comment]
It works on Linux, but so far not OSX. I'll clean up the script and post it here when I get a chance.

**Comment by mfeurer** [comment]
I see. I'm afraid that I won't be able to help with OSX problems as we don't support OSX. I would suggest using docker or virtual machines on OSX.

**Comment by mfeurer** [comment]
Closing this as it is an OSX issue and there wasn't any activity for the last three months. Please reopen or create a new issue if you need further help.

**Comment by rd27995** [comment]
I get almost the same error message - 

ValueError: Dummy prediction failed with run state StatusType.TIMEOUT and additional output: {'error': 'Timeout', 'configuration_origin': 'DUMMY'}.

After receiving this warning - 

[WARNING] [2021-03-11 11:14:55,702:Client-AutoML(1):faa37853-829d-11eb-be96-002590fc6804] Dataset too large for memory limit 3072MB, reducing number of samples from 3738731 to 105683.

If it is reducing the number of samples automatically, why there is a timeout error?
