### ISSUE TITLE
AttributeError: 'BinomialDeviance' object has no attribute 'get_init_raw_predictions'

### ISSUE THREAD

**Issue by sarthaksharma01** [automl/auto-sklearn#844]
I am trying to use my trained model in a flask web app, for this I used joblib but in the end, I get the above error please assist me to get rid of it.

C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 
and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
The scikit-learn version is 0.22.2.post1.
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.feature_selection.rfe module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection.rfe. Anything that cannot be imported from sklearn.feature_selection.rfe is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.ensemble.gradient_boosting module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:313: UserWarning: Trying to unpickle estimator GradientBoostingClassifier from version 
0.20.3 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\deprecation.py:144: FutureWarning: The sklearn.tree.tree module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.tree. Anything that cannot be imported from sklearn.tree is now part of the private API.
  warnings.warn(message, FutureWarning)
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:313: UserWarning: Trying to unpickle estimator DecisionTreeRegressor from version 0.20.3 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:313: UserWarning: Trying to unpickle estimator RFECV from version 0.20.3 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [29/Apr/2020 23:38:05] "GET / HTTP/1.1" 200 -
[2020-04-29 23:38:37,701] ERROR in app: Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "app.py", line 36, in main
    prediction = mj.predict(input_variables)[0]
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\utils\metaestimators.py", line 116, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\feature_selection\_rfe.py", line 252, in predict
    return self.estimator_.predict(self.transform(X))
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\ensemble\_gb.py", line 2165, in predict
    raw_predictions = self.decision_function(X)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\ensemble\_gb.py", line 2121, in decision_function
    raw_predictions = self._raw_predict(X)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\ensemble\_gb.py", line 1655, in _raw_predict
    raw_predictions = self._raw_predict_init(X)
  File "C:\Users\Sarthak\AppData\Roaming\Python\Python38\site-packages\sklearn\ensemble\_gb.py", line 1649, in _raw_predict_init
    raw_predictions = self.loss_.get_init_raw_predictions(
AttributeError: 'BinomialDeviance' object has no attribute 'get_init_raw_predictions'
127.0.0.1 - - [29/Apr/2020 23:38:37] "POST / HTTP/1.1" 500 -

**Comment by mfeurer** [comment]
Hey, the issue is that the you're using a gradient-boosting model which is built with sklearn 0.20, while the installation in your flask app uses sklearn 0.22.

However, I don't think this is related to Auto-sklearn as Auto-sklearn is not mentioned in the issue or traceback at all.

**Comment by Chitaranjanpradhan** [comment]
Traceback (most recent call last):
  File "bot.py", line 159, in <module>
    is_intent = class_analyzer.predict([spacy_get_vec(s, True)])[0] == 'intent'
  File "C:\Users\chita\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 2165, in predict
    raw_predictions = self.decision_function(X)
  File "C:\Users\chita\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 2121, in decision_function
    raw_predictions = self._raw_predict(X)
  File "C:\Users\chita\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 1655, in _raw_predict
    raw_predictions = self._raw_predict_init(X)
  File "C:\Users\chita\Anaconda3\lib\site-packages\sklearn\ensemble\_gb.py", line 1649, in _raw_predict_init
    raw_predictions = self.loss_.get_init_raw_predictions(
AttributeError: 'BinomialDeviance' object has no attribute 'get_init_raw_predictions'

**Comment by eddiebergman** [comment]
Hi @Chitaranjanpradhan,

We would appreciate more than just a raw plain text traceback for the future. This traceback doesn't even pass through `autosklearn` at all and so there is nothing we can do to help you with what you've provided.

Have you read the answer given by mfeurer above? Maybe this can help, i.e. there's a version mismatch. Are you using this with flask as the original poster did?

Best,
Eddie
