### ISSUE TITLE
Custom classifier metafeature calculation breaks when going from 0.6 to 0.7

### ISSUE THREAD

**Issue by he-ritter** [automl/auto-sklearn#861]
## Describe the bug ##
When going from version 0.6 to 0.7, the metafeature calculation for this particular custom classifier is broken. I also have an XGBoost classifier, which is not affected.

## To Reproduce ##
The following classifier works on version 0.6, but in using it for metafeature calculation in 0.7 throws an error:
```
import torch
from torch.utils.data import DataLoader, Dataset
from torch.optim import Adam
import torch.nn.functional as F
import torch.nn as nn
from ConfigSpace.configuration_space import ConfigurationSpace
from ConfigSpace.hyperparameters import UniformFloatHyperparameter, \
    UniformIntegerHyperparameter, CategoricalHyperparameter
from autosklearn.pipeline.constants import DENSE, SIGNED_DATA, \
    UNSIGNED_DATA, PREDICTIONS
from autosklearn.pipeline.components.base \
    import AutoSklearnClassificationAlgorithm
import numpy as np

class ClassNNWrapper(AutoSklearnClassificationAlgorithm):

    class ClassNet(nn.Module):
        def __init__(
                    self,
                    input_size,
                    output_size,
                    hidden_dim,
                    dropout_prob,
                    activation,
                    layers=7):
            super().__init__()
            self.input_size = input_size
            self.output_size = output_size
            self.hidden_dim = hidden_dim
            self.dropout_prob = dropout_prob
            self.layers = layers
            self.activation = activation
            self.init_model()
    
        def init_model(self):
            self.dense = []
            self.batch_norm = []
            self.dropout = []
            #self.first_batch_norm = nn.BatchNorm1d(self.input_size, self.input_size)
            self.first_dense = nn.Linear(self.input_size, self.hidden_dim)
            self.last_dense = nn.Linear(self.hidden_dim, self.output_size)
    
            for i in range(self.layers):
                self.dense.append(nn.Linear(self.hidden_dim, self.hidden_dim))
                self.batch_norm.append(nn.BatchNorm1d(self.hidden_dim, self.hidden_dim))
                self.dropout.append(nn.Dropout(self.dropout_prob))
    
            self.dense = nn.ModuleList(self.dense)
            self.batch_norm = nn.ModuleList(self.batch_norm)
            self.dropout = nn.ModuleList(self.dropout)
    
        def forward(self, x):
            #x = self.first_batch_norm(x)
            x = self.activation(self.first_dense(x))
    
            for dense, bn, drop in zip(self.dense, self.batch_norm, self.dropout):
                x = self.activation(dense(x))
                x = bn(x)
                x = drop(x)
    
            x = F.softmax(self.last_dense(x))
            return x


    class AutoSkDataset(Dataset):
        def __init__(self, X, Y):
            super().__init__()
            self.X = X
            self.Y = Y
    
        def __len__(self):
            return len(self.X)
    
        def __getitem__(self, ixs):
            if torch.is_tensor(ixs):
                ixs = ixs.tolist()
    
            Y_ret = self.Y[ixs, :].ravel() if self.Y.ndim > 1 else self.Y[ixs]
            return self.X[ixs, :], Y_ret


    def __init__(self, hidden_dim_factor, dropout_prob, activation, epochs, layers=7, random_state=None):
        torch.backends.cudnn.enabled = False
        self.hidden_dim_factor = hidden_dim_factor
        self.dropout_prob = dropout_prob
        self.activation = activation
        self.epochs = epochs
        self.layers = layers
        if random_state is not None:
            torch.manual_seed(random_state.randint(0, 50000))


    def fit(self, X, Y, sample_weight=None):
        self.input_size = X.shape[1]
        self.output_size = len(np.unique(Y.ravel()))
        
        self.device = torch.device('cuda' if torch.cuda.is_available() else "cpu")

        self.model = self.ClassNet(
            self.input_size,
            self.output_size,
            max(1, int(self.input_size * self.hidden_dim_factor)),
            self.dropout_prob,
            self.activation,
            self.layers
            ).to(self.device).float()

        self.data = DataLoader(
            self.AutoSkDataset(X, Y),
            batch_size=128,
            shuffle=True
            )

        self.param_optim = Adam(self.model.parameters())
        self.criterion = nn.CrossEntropyLoss().to(self.device)
        self._fit()

        return self

    def _fit(self):
        self.model.train()
        for i in range(self.epochs):
            for x, y in self.data:
                self.param_optim.zero_grad()
                x = x.to(self.device).float()
                y = y.to(self.device).long()
                #x.to(self.device)
                #y.to(self.device)

                out = self.model(x)

                loss = self.criterion(out, y)
                loss.backward()

                self.param_optim.step()


    def predict(self, X):
        with torch.no_grad():
            self.model.eval()
            pred = np.argmax(self.model(torch.Tensor(X).to(self.device).float()).cpu().numpy(), axis=1)
        return pred


    def predict_proba(self, X):
        with torch.no_grad():
            self.model.eval()
            pred = self.model(torch.Tensor(X).to(self.device).float()).cpu().numpy()
        return pred


    @staticmethod
    def get_properties(dataset_properties=None):
        return {
            'shortname': 'ClassNN',
            'name': 'Neural Network Classifier',
            'handles_regression': False,
            'handles_classification': True,
            'handles_multiclass': True,
            'handles_multilabel': False,
            'is_deterministic': True,
            'input': (DENSE, SIGNED_DATA),
            'output': (PREDICTIONS,)
        }


    @staticmethod
    def get_hyperparameter_search_space(dataset_properties=None):
        cs = ConfigurationSpace()
        hidden_dim_factor = UniformFloatHyperparameter(
            name='hidden_dim_factor', lower=0.5, upper=1.2, default_value=1
        )
        dropout_prob = UniformFloatHyperparameter(
            name='dropout_prob', lower=0.01, upper=0.5, default_value=0.05
        )
        activation = CategoricalHyperparameter(
            name='activation', choices=[F.leaky_relu, F.tanh]
        )
        layers = UniformIntegerHyperparameter(
            'layers', 3, 8, default_value=5)
        epochs = UniformIntegerHyperparameter(
            'epochs', 20, 100, default_value=50)
        cs.add_hyperparameters([hidden_dim_factor, dropout_prob, activation, layers, epochs])
        return cs
```

## Expected behavior ##
The classifier should also be able to be used for metafeature calculation in version 0.7.

## Actual behavior, stacktrace or logfile ##
The classifier is ignored in the metafeature calculation. When all classifiers except this one are removed, all datasets fail with an error. This did not happen in version 0.6 (also in the case where this classifier is the only one available to auto-sklearn).

```
Traceback (most recent call last):
  File "/home/ubuntu/autosk_clf/scripts/scripts/run_auto-sklearn_for_metadata_generation.py", line 74, in <module>
    feat_type=cat)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/estimators.py", line 681, in fit
    dataset_name=dataset_name,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/estimators.py", line 351, in fit
    self._automl[0].fit(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/automl.py", line 1026, in fit
    load_models=load_models,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/automl.py", line 213, in fit
    only_return_configuration_space=only_return_configuration_space,
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/automl.py", line 413, in _fit
    exclude_preprocessors=self._exclude_preprocessors)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/automl.py", line 892, in _create_search_space
    exclude_preprocessors=exclude_preprocessors)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/util/pipeline.py", line 52, in get_configuration_space
    return _get_classification_configuration_space(info, include, exclude)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/util/pipeline.py", line 94, in _get_classification_configuration_space
    include=include, exclude=exclude).\
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 77, in __init__
    random_state, init_params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 35, in __init__
    self.config_space = self.get_hyperparameter_search_space()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 224, in get_hyperparameter_search_space
    dataset_properties=self.dataset_properties)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/pipeline/classification.py", line 172, in _get_hyperparameter_search_space
    exclude=exclude, include=include, pipeline=self.steps)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/autosklearn/pipeline/base.py", line 306, in _get_base_search_space
    assert np.sum(matches) != 0, "No valid pipeline found."
AssertionError: No valid pipeline found.
```

## Environment and installation: ##

Please give details about your installation:

OS: Ubuntu 18.04
Installation is on a VM without a venv.
Python version: 3.6
Auto-sklearn version: 0.7

**Comment by mfeurer** [comment]
Thanks a lot for bringing this up. @franchuterivera had a look into this and was able to reproduce the error. There was indeed a change when going from 0.6 to 0.7 which messed up the functionality to enforce that only positive values (SIGNED input) is passed to an estimator. I'm afraid we can't easily fix that right now.

However, I don't see a reason why your estimator requires only SIGNED input. Is it possible that you change the input to UNSIGNED? Then it should work again.

**Comment by he-ritter** [comment]
Thank you for doing an in depth look into this error, and thanks for the hint! Of course this classifier can take unsigned input. That's why you shouldn't do copy paste programming :)
For anyone interested to use this classifier, be aware that the final softmax activation is also wrong since CrossEntropyLoss is used.

**Comment by mfeurer** [comment]
> That's why you shouldn't do copy paste programming :)

Did you copy from one of the examples? If yes, we should update that example.

**Comment by he-ritter** [comment]
No, I copied the code from some test file I had lying around. The examples actually show the correct way of implementing a classifier.

**Comment by mfeurer** [comment]
Okay, then I'm closing this as the issue appears to be resolved.
