### ISSUE TITLE
Log_loss issue with cross-validation

### ISSUE THREAD

**Issue by jsebanaz90** [automl/auto-sklearn#873]
Hi, 

I'm using AutoSklearnClassifier for multi-class problems. I want to assess the final performance of auto-sklearn using log_loss metric and, therefore, auto-sklearn needs to optimize for the same metric it is evaluated on (log_loss). However, when I pass the 'metric' attribute to the fit() method I receive the following error.

Thank you very much.

Here my source code:

**################Here my source code################**
def main(dataset_name):
    
    dataset = dataset_name
        
    df = pd.read_csv('{}.csv'.format(dataset))
    x_cols = [c for c in df.columns if c != 'target']
    X = df[x_cols]
    y = df['target']
    list_ = list(df.target.unique())

    X_train, X_test, y_train, y_test = \
        sklearn.model_selection.train_test_split(X, y, random_state=1)

    automl = autosklearn.classification.AutoSklearnClassifier(
        time_left_for_this_task=120,
        per_run_time_limit=30,
        resampling_strategy='cv',
        resampling_strategy_arguments={'folds': 10},
    )
  
    automl.fit(X_train.copy(), y_train.copy(),metric=autosklearn.metrics.log_loss)
    automl.refit(X_train.copy(), y_train.copy())

    predictions = automl.predict_proba(X_test)
    print("Log_loss score", sklearn.metrics.log_loss(y_test, predictions))

main(sys.argv[1])

**############And here the error that I got##############**

Traceback (most recent call last):
  File "AutoSklearn_multiclass_PARALL.py", line 86, in <module>
    main(sys.argv[1])
  File "AutoSklearn_multiclass_PARALL.py", line 78, in main
    automl.refit(X_train.copy(), y_train.copy())
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/estimators.py", line 508, in refit
    self._automl[0].refit(X, y)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/automl.py", line 941, in refit
    return super().refit(X, y)
  File "/home/amasegosa/.conda/envs/snakes/lib/python3.5/site-packages/autosklearn/automl.py", line 541, in refit
    raise ValueError("Refit can only be called if 'ensemble_size != 0'")
ValueError: Refit can only be called if 'ensemble_size != 0'

**Comment by jsebanaz90** [comment]
Hi @mfeurer, I have added these lines of code:

    automl.fit(X_train.copy(), y_train.copy(), metric=autosklearn.metrics.log_loss)
    automl.fit_ensemble(y_train.copy(), ensemble_size = 50)
    automl.refit(X_train.copy(), y_train.copy())

Basically I included fit_ensemble() method, is this a right solution to my initial issue?

**Comment by mfeurer** [comment]
Hey @jsebanaz90, the `refit` itself should have done the trick by itself and I don't understand why there wasn't an ensemble in the first place. Does the updated code work for you?

**Comment by mfeurer** [comment]
Closing this due to inactivity. Please reopen if this issue still persists.
