### ISSUE TITLE
predict fails in preprocessing, even no_preprocessing is selected

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#90]
```
seed = 1
c = AutoSklearnClassifier(
        shared_mode=True, tmp_folder=atsklrn_tempdir, output_folder=atsklrn_tempdir,
        delete_tmp_folder_after_terminate=False, delete_output_folder_after_terminate=False,
        ensemble_size=0, initial_configurations_via_metalearning=0,
        include_preprocessors=('no_preprocessing',),
        seed=seed)
c._task = BINARY_CLASSIFICATION
c._metric = F1_METRIC
c._precision = '32'
c._dataset_name = 'Truffles'

c.run_ensemble_builder(
    time_left_for_ensembles=0,
    max_iterations=1,
    ensemble_size=5,
    ).wait()

time.sleep(10)
print(c.show_models())
y_pred = c.predict(X_test)
```

```
#some more classifiers above
(0.200000, SimpleClassificationPipeline(configuration={
  'balancing:strategy': 'weighting',
  'classifier:__choice__': 'random_forest',
  'classifier:random_forest:bootstrap': 'False',
  'classifier:random_forest:criterion': 'entropy',
  'classifier:random_forest:max_depth': 'None',
  'classifier:random_forest:max_features': 1.6519823800472522,
  'classifier:random_forest:max_leaf_nodes': 'None',
  'classifier:random_forest:min_samples_leaf': 14,
  'classifier:random_forest:min_samples_split': 13,
  'classifier:random_forest:min_weight_fraction_leaf': 0.0,
  'classifier:random_forest:n_estimators': 100,
  'imputation:strategy': 'mean',
  'one_hot_encoding:use_minimum_fraction': 'False',
  'preprocessor:__choice__': 'no_preprocessing',
  'rescaling:__choice__': 'min/max'})),
(0.200000, SimpleClassificationPipeline(configuration={
  'balancing:strategy': 'weighting',
  'classifier:__choice__': 'sgd',
  'classifier:sgd:alpha': 8.157889958167601e-05,
  'classifier:sgd:average': 'False',
  'classifier:sgd:eta0': 0.042599381735495594,
  'classifier:sgd:fit_intercept': 'True',
  'classifier:sgd:learning_rate': 'optimal',
  'classifier:sgd:loss': 'perceptron',
  'classifier:sgd:n_iter': 25,
  'classifier:sgd:penalty': 'l2',
  'imputation:strategy': 'median',
  'one_hot_encoding:minimum_fraction': 0.040130045634589266,
  'one_hot_encoding:use_minimum_fraction': 'True',
  'preprocessor:__choice__': 'no_preprocessing',
  'rescaling:__choice__': 'normalize'})),
]
/home/ekobylkin/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/imputation.py:342: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 11343049 but corresponding boolean dimension is 3117678
  missing = np.arange(X.shape[not self.axis])[invalid_mask]
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-ensemble.py", line 70, in <module>
    y_pred = c.predict(X_test)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 286, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 591, in predict
    return np.argmax(self.predict_proba(X), axis=1)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 300, in predict_proba
    return super(AutoSklearnClassifier, self).predict_proba(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 616, in predict_proba
    prediction = model.predict_proba(X_)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/pipeline/classification.py", line 110, in predict_proba
    Xt = transform.transform(Xt)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/pipeline/components/data_preprocessing/rescaling.py", line 19, in transform
    return self.preprocessor.transform(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/pipeline/implementations/MinMaxScaler.py", line 121, in transform
    X.data[X.indptr[i]:X.indptr[i + 1]] *= self.scale_[i]
IndexError: index 3117678 is out of bounds for axis 0 with size 3117678
```

**Comment by mfeurer** [comment]
This custom preprocessor was removed for the latest bugfix release 0.1.3.
