### ISSUE TITLE
pip install autosklearn gives the error: Exception: You probably meant to install and run auto-sklearn

### ISSUE THREAD

**Issue by dsbowen** [automl/auto-sklearn#930]
## Describe the bug ##
Error when pip installing auto-sklearn.

## To Reproduce ##
1. `python3 -m venv venv`
2. `. venv/bin/activate`
3. `curl https://raw.githubusercontent.com/automl/auto-sklearn/master/requirements.txt | xargs -n 1 -L 1 pip install`
4. `pip3 install autosklearn`

## Expected behavior ##
Successful installation of auto-sklearn.

## Actual behavior, stacktrace or logfile ##
```
Collecting autosklearn
  Using cached autosklearn-0.1.1.tar.gz (1.5 kB)
Building wheels for collected packages: autosklearn
  Building wheel for autosklearn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dsbowen/crt/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ylv8we0e/autosklearn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ylv8we0e/autosklearn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qx0t9whr
       cwd: /tmp/pip-install-ylv8we0e/autosklearn/
  Complete output (29 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/autosklearn
  copying autosklearn/__init__.py -> build/lib/autosklearn
  copying autosklearn/cli.py -> build/lib/autosklearn
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ylv8we0e/autosklearn/setup.py", line 47, in <module>
      'autosklearn = autosklearn.cli:cli',
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/dsbowen/crt/venv/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 326, in run
      self.run_command('install')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-ylv8we0e/autosklearn/setup.py", line 20, in run
      raise Exception("You probably meant to install and run auto-sklearn")
  Exception: You probably meant to install and run auto-sklearn
  ----------------------------------------
  ERROR: Failed building wheel for autosklearn
```

## Environment and installation: ##

* Windows 10 x64 using WSL/Ubuntu 16
* Installation in virtual environment
* Python version 3.6.8
* Auto-sklearn version (attempting) 0.8.0

## Attempted fixes ##

* upgraded swig to 3.0.12-1
* upgraded pip to 20.2.2 (tried with pip and pip3)

**Comment by mfeurer** [comment]
Thanks for reporting this issue. It appears that you have an old version of auto-sklearn in your cache (in fact, very old, from the end of 2016). Could you please try installing the latest version, for example by `pip install auto-sklearn==0.8` or `pip install auto-sklearn --no-cache`?

**Comment by dsbowen** [comment]
Thanks, working just fine now!
