### ISSUE TITLE
prediction tries to load non-existing seed result

### ISSUE THREAD

**Issue by Motorrat** [automl/auto-sklearn#94]
The temp directory is deleted before each time the file is run. This time the max seed was 811 (10 seeds with the increment of 90) but the predict() method failed trying to load the model 1081.7.model. Probably this is based on the list of runs somewhere else, may be in the working directory.

```
####### Finished seed=811 # 14:05 #
Multicore fit completed # 14:05 #
Building ensemble # 14:05 #
Ensemble built # 14:05 #
Traceback (most recent call last):
  File "nfs_share/truffles-autosklearn-multy-all.py", line 114, in <module>
    y_pred = c.predict(X_test)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 286, in predict
    return super(AutoSklearnClassifier, self).predict(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 591, in predict
    return np.argmax(self.predict_proba(X), axis=1)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/estimators.py", line 300, in predict_proba
    return super(AutoSklearnClassifier, self).predict_proba(X)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 606, in predict_proba
    self._load_models()
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/automl.py", line 645, in _load_models
    self.models_ = self._backend.load_models_by_identifiers(identifiers)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 197, in load_models_by_identifiers
    models[identifier] = self.load_model_by_seed_and_id(seed, idx)
  File "/home/ekobylkin/anaconda2/lib/python2.7/site-packages/AutoSklearn-0.0.1.dev0-py2.7-linux-x86_64.egg/autosklearn/util/backend.py", line 206, in load_model_by_seed_and_id
    with open(model_file_path, 'rb') as fh:
IOError: [Errno 2] No such file or directory: './nfs_share/atsklrn_tmp/.auto-sklearn/models/1081.7.model'
```

**Comment by mfeurer** [comment]
Does this problem still occur?

**Comment by Motorrat** [comment]
yes, from time to time.

**Comment by mfeurer** [comment]
I just pushed a new auto-sklearn version (0.3.0). @Motorrat please reopen if the issue still exists.
